### ISSUE TITLE
ESBMC Release v7.2

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1027]
Dear all,

Our last release was in February/2023; many features, improvements, and bug fixes have been merged into the master since then.

So, releasing v7.2 of ESBMC within the following two weeks would be great.

Would you have some new features/improvements/bug fixes to include in this release v7.2?

Best,
Lucas

**Comment by kunjsong01** [comment]
### Feature/Bug fixes done:
So between v7.1 (23 Feb 2023) and the current master branch tip (21 May 2023), 
for ESBMC++ the v7.2 release notes can include:  
1. Support for polymorphism and CXXMemberCallExpr (as backed by the passing rate in polymorphism_bringup benchmarks)
2. Bug fixes for OMs {ios, cstring, cmath, istream, ostream, stdexcept, cstdio, exception, streambuf, new, cstdarg, definitions, iomanip, cassert, cstddef} (as backed by the sanity check TCs and passing rate in string/streams benchmarks)

> Would you have some new features/improvements/bug fixes to include in this release v7.2?
I don't have any active PRs at the moment. Given the two weeks window, I'll try to finish bulletpoint 1 below to push it into the upcoming v7.2 release. 

**Features/Bug fixes WIP or TODO:** 
1. **[Bug fixes][padding and pointers]**$\textcolor{orange}{\textsf{[WIP]}}$ padding using symbolic types (911-issue1) + dangling pointer(894)
2. **[Feature][Frontend]**$\textcolor{purple}{\textsf{[TODO]}}$ Template

**Comment by lucasccordeiro** [comment]
Hi guys,

The PR for the release notes of ESBMC v7.2 is available here: https://github.com/esbmc/esbmc/pull/1046.

Please review ;-)

**Comment by intrigus-lgtm** [comment]
I'd say v7.2 [has been released](https://github.com/esbmc/esbmc/releases/tag/v7.2) :)

**Comment by lucasccordeiro** [comment]
Many thanks, @intrigus-lgtm. Well spotted ;-)
