### ISSUE TITLE
esbmc-wrapper.py interprets "forgotten memory" as an "unknown" result for the memory property

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#1029]
From https://github.com/esbmc/esbmc/pull/1019#issuecomment-1551019121
> In `valid-memsafety` there is 1 new correct -> unknown (`c/goblint-regression/09-regions_19-nested_nr-deref.i`) that did find a NULL dereference before, but now finds
`
dereference failure: forgotten memory: dynamic_2_value
`

In addition to a possible NULL-pointer dereference this benchmark does indeed also not free its allocated memory, so I gather the above verdict given by ESBMC is valid. However, as the title says, the `esbmc-wrapper.py` interprets this result as "unknown": https://github.com/esbmc/esbmc/blob/670ecf0ce25abb48c2759f3ac13a26be245da2e2/scripts/competitions/svcomp/esbmc-wrapper.py#L118-L120

Is this behaviour of the wrapper and/or ESBMC in this case intended?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes ?

**Comment by fbrausse** [comment]
From <https://sv-comp.sosy-lab.org/2023/rules.php>:
![image](https://github.com/esbmc/esbmc/assets/3314468/66225713-821f-4df6-b60e-7983682cdaec)

So it is my understanding that forgotten memory should be `false(valid-memtrack)` aka `Result.fail_memtrack` in the script. Curiously, this particular `return` line has recently changed back and forth a few times according to `git blame`: https://github.com/esbmc/esbmc/commit/0b5bdad87701b1896b2ca691dcf4bccc096293ca https://github.com/esbmc/esbmc/commit/b872ac81a469f6d207294cef6653b40ed86ce8c4 https://github.com/esbmc/esbmc/commit/b21b903debd9569f41eadf0d4be722920e087b4b

@lucasccordeiro @mikhailramalho Do you remember why you changed it to `unknown`?

**Comment by rafaelsamenezes** [comment]
> Is this behaviour of the wrapper and/or ESBMC in this case intended?

At the competition we did because we were having too many wrong results. It might be worth to revisit them.

Since we are checking the rules... I'm still not sure what's the difference between memtrack to memcleanup. Unless we assume that variables maintain their values after they go out of scope.

**Comment by fbrausse** [comment]
> > Is this behaviour of the wrapper and/or ESBMC in this case intended?
> 
> At the competition we did because we were having too many wrong results. It might be worth to revisit them.
> 
> Since we are checking the rules... I'm still not sure what's the difference between memtrack to memcleanup. Unless we assume that variables maintain their values after they go out of scope.

They somehow define the property in terms of valgrind.
![image](https://github.com/esbmc/esbmc/assets/3314468/37b5dc19-4b28-40e5-9d58-1d8d2a92d471)

Checking one example from #1259
- c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_45_bad.i

It's a pretty simple example, allocate 800 bytes of memory, assign it to global variable, don't free it, terminate. Valgrind reports
```
==4062== LEAK SUMMARY:
==4062==    definitely lost: 0 bytes in 0 blocks
==4062==    indirectly lost: 0 bytes in 0 blocks
==4062==      possibly lost: 0 bytes in 0 blocks
==4062==    still reachable: 800 bytes in 1 blocks
==4062==         suppressed: 0 bytes in 0 blocks
```
Patching the program to not assign to the global variable
```diff
@@ -868,7 +868,7 @@ void CWE401_Memory_Leak__int64_t_calloc_45_bad(void)
   
   printLongLongLine(*data);
   
-  CWE401_Memory_Leak__int64_t_calloc_45_badData = data;
+  // CWE401_Memory_Leak__int64_t_calloc_45_badData = data;
   
   badSink();
   
```
then valgrind prints
```
==4287== LEAK SUMMARY:
==4287==    definitely lost: 800 bytes in 1 blocks
==4287==    indirectly lost: 0 bytes in 0 blocks
==4287==      possibly lost: 0 bytes in 0 blocks
==4287==    still reachable: 0 bytes in 0 blocks
==4287==         suppressed: 0 bytes in 0 blocks
```
