### ISSUE TITLE
[cpp-frontend] CXXConstructorDecl

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1032]
$ esbmc bitfields.cpp
ESBMC version 7.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
bitfields.cpp:20:11: warning: implicit truncation from 'int' to bit-field changes value from 16777215 to 3 [-Wbitfield-constant-conversion]
  beans.d = 0xFFFFFF;
          ^ ~~~~~~~~
Converting
ERROR: Declaration has an empty name:
CXXConstructorDecl 0x58d85f0 </usr/include/stdlib.h:67:9> col:9 implicit  'void ()' inline default trivial noexcept-unevaluated 0x58d85f0

Aborted

````CPP
#include <cstdlib>
#include <cstring>
#include <cassert>

struct has_bitfield {
  unsigned int a;
  unsigned int b : 2;
  unsigned int c : 2;
  unsigned int d : 2;
} beans;

int main(void)
{
  assert(beans.a == 0);
  assert(beans.b == 0);
  assert(beans.c == 0);
  assert(beans.d == 0);
  beans.d = 1;
  assert(beans.d == 1);
  beans.d = 0xFFFFFF;
  assert(beans.d == 3);

  memset(&beans, 0, sizeof(beans));
  assert(beans.d == 0);
  return 0;
}
````

**Comment by kunjsong01** [comment]
we probably need to redirect all POD types to C conversion flow, but might be tricky when dealing with `CXXConstructExpr` for instantiation. If this approach works, it will also fix https://github.com/esbmc/esbmc/issues/1006. 

all in all it worths a try.

**Comment by kunjsong01** [comment]
C++14 N4140 § 8.5.1
```
An aggregate is an array or a class (Clause 9) with no user-provided constructors (12.1), no private or
protected non-static data members (Clause 11), no base classes (Clause 10), and no virtual functions (10.3).
```

An example would be: 
```cpp
struct uint3
  {
    unsigned int x, y, z;
  };

uint3 indexOfThread[1024];
```
(taken from https://github.com/esbmc/esbmc/issues/1006)

Regarding the previous concern:
> but might be tricky when dealing with CXXConstructExpr for instantiation.

So for an aggregate init, we can probably just use the existing conversion flow for C in ESBMC. 
Although this kind of init usually implicitly calls trivial implicit  CXXConstructorDecl, I reckon it's probably safe to just ignore it and follow the existing C's flow.

**Comment by kunjsong01** [comment]
after adding `-I library` where library pointing to our C++ OMs. The error becomes https://github.com/esbmc/esbmc/issues/1006

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1040.
