### ISSUE TITLE
ESBMC is not converting ieee_float to double correctly

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1037]
The definition `double one_modf = 1.0;` makes ESBMC generate the following expression:

```
constant_floatbv
* value : 1.000000
* type : floatbv
  * fraction : 52
  * exponent : 11
```

Which seems correct... however invoking `to_double` causes some weird behavior: the number is not normal anymore. Also, this seems to be triggered by the `from_integer`

```cpp
int one = 1;
assert(isnormal(one)); // Holds

double d_one = 1;
assert(isnormal(d_one)); // Holds

ieee_floatt ieee_one(ieee_float_spect(52,11));

ieee_one.from_double(d_one);
assert(isnormal(ieee_one.to_double())); // Holds

ieee_one.from_double(one);
assert(isnormal(ieee_one.to_double())); // Holds

ieee_one.from_integer(one);
assert(isnormal(ieee_one.to_double()));  // Fails
```

@mikhailramalho any suggestions?

**Comment by mikhailramalho** [comment]
What's the double returned by to_double()?

**Comment by rafaelsamenezes** [comment]
6.9529314086768e-310

**Comment by mikhailramalho** [comment]
What's the bit representation of this double?

If it's 63 '0's followed by 1, then from_integer is probably doing a bit
cast of the integer 1.

**Comment by fbrausse** [comment]
6.9529314086768e-310 is some denormalized double in the close-to-zero range. Bits: `0x 00007ffe 00000000`. The smallest denormalized positive double is 4.94065645841e-324 with bits `0x 00000000 00000001` and the smallest normalized double is 2.22507385851e-308 with bits `0x 00100000 00000000`.

**Comment by rafaelsamenezes** [comment]
After running the from_integer:

```
ieee_one.get_exponent() := 0
  ieee_one.get_fraction() := 4503599627370496
  ieee_one.get_sign() := false
```

`4503599627370496` = `0x 00100000 00000000` as @fbrausse mentioned. Btw, after moving this test to catch2 I am having the same behavior in `from_double`. As a side note, I found out this issue while testing the Interval Analysis... and the interval computation of floats was nondeterministic.

**Comment by mikhailramalho** [comment]
Is there a from expr method, that takes a constant_int? Or constant_expr? I
remember using something like that in the past.

**Comment by fbrausse** [comment]
https://github.com/esbmc/esbmc/blob/1d30deeb731959437debbd7ea6001cd29089315f/src/util/ieee_float.cpp#L1186

This should be a `unsigned long long`

**Comment by rafaelsamenezes** [comment]
Yeah, that fixes both cases.

**Comment by lucasccordeiro** [comment]
Can you create a PR with the fix and regression tests?Sent from my iPhoneOn 23 May 2023, at 17:16, Rafael Sá Menezes ***@***.***> wrote:﻿
Yeah, that fixes both cases.

**Comment by mikhailramalho** [comment]
Is this still an issue? I'm seeing several warnings that esbmc can't convert float zero to double.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes : could you please check this issue?

**Comment by mikhailramalho** [comment]
I saw it in regression/python-intensive/cmath_intermediate_core/main.py:
```
WARNING: ESBMC fails to convert constant_floatbv
* value : 0.000000
* type : floatbv
  * fraction : 52
  * exponent : 11 into double

**Comment by mikhailramalho** [comment]
Can we get a fix for this? Super annoying warning, in some cases, it's being printed several hundred times
