### ISSUE TITLE
[C++ verification] function/class-scope aggregate init

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1043]
TC: 
```cpp
#include <cstdlib>
#include <cstring>
#include <cassert>

struct has_bitfield {
  unsigned int a;
  unsigned int b : 2;
  unsigned int c : 2;
  unsigned int d : 2;
};

//struct has_bitfield beans;

void do_pod()
{
  struct has_bitfield beans;
  assert(beans.a == 0);
  assert(beans.b == 0);
  assert(beans.c == 0);
  assert(beans.d == 0);
  beans.d = 1;
  assert(beans.d == 1);
  beans.d = 0xFFFFFF;
  assert(beans.d == 3);

  memset(&beans, 0, sizeof(beans));
  assert(beans.d == 0);
}

int main(void)
{
  do_pod();
  return 0;
}
```

cmd: ./esbmc-new 1032_function.cpp -I library/

result: "VERIFICATION FAILED", should be "VERIFICATION SUCCESSFUL"

**Comment by kunjsong01** [comment]
value-init aggregate in global scope works fine thought (see https://github.com/esbmc/esbmc/pull/1040 )

**Comment by XLiZHI** [comment]
Hi @kunjsong01,

As far as I know, the local variable (beans) in this code is not initialised automatically (in C and C++). I think the initial values of `beans.a` and the bit fields `beans.b`, `beans.c`, `beans.d` are undefined. I think our frontend works as expected.

If we initialise this struct as a global variable, then we get "VERIFICATION SUCCESSFUL".

**Comment by fbrausse** [comment]
> Hi @kunjsong01,
> 
> As far as I know, the local variable (beans) in this code is not initialised automatically (in C and C++). I think the initial values of `beans.a` and the bit fields `beans.b`, `beans.c`, `beans.d` are undefined. I think our frontend works as expected.
> 
> If we initialise this struct as a global variable, then we get "VERIFICATION SUCCESSFUL".

I agree, automatic storage variables of trivial/POD type are not initialized to zero. Also, in this case it's easy to check:
```
$ clang++ -fsanitize=memory -g gh-1043.cc 
gh-1043.cc:23:11: warning: implicit truncation from 'int' to bit-field changes value from 16777215 to 3 [-Wbitfield-constant-conversion]
   23 |   beans.d = 0xFFFFFF;
      |           ^ ~~~~~~~~
1 warning generated.
$ ./a.out 
==14398==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55c0b1fa7930 in do_pod() /home/kane/scorch/esbmc/debug/gh-1043.cc:17:3
    #1 0x55c0b1fa7e8d in main /home/kane/scorch/esbmc/debug/gh-1043.cc:32:3
    #2 0x7f0d9796e909  (/lib64/libc.so.6+0x23909)
    #3 0x7f0d9796e9c4 in __libc_start_main (/lib64/libc.so.6+0x239c4)
    #4 0x55c0b1f172b0 in _start (/home/kane/scorch/esbmc/debug/a.out+0x322b0)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/kane/scorch/esbmc/debug/gh-1043.cc:17:3 in do_pod()
Exiting
```
Line 17 is the first assert reading from uninitialized memory: `assert(beans.a == 0);`

See also https://en.cppreference.com/w/cpp/language/default_initialization, which delegates initialization of automatic storage trivial types to default initialization of its members, and the [Notes](https://en.cppreference.com/w/cpp/language/default_initialization#Notes) say:
> Default-initialization of non-class variables with automatic and dynamic storage duration produces objects with indeterminate values (static and thread-local objects get [zero initialized](https://en.cppreference.com/w/cpp/language/zero_initialization)).

**Comment by lucasccordeiro** [comment]
@XLiZHI : could you please submit a PR that adds some regression tests related to this function/class-scope aggregate init?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1588.
