### ISSUE TITLE
[C++ verification] struct initialization

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1044]
#1006 in this case, initialization for aggregate (including POD).

The following example defines a data type with three members (x, y, z) and a constructor to initialize the members:
`esbmc main.cpp` 
```
struct dim3
  {
    unsigned int x, y, z;

    dim3(unsigned int vx = 1, unsigned int vy = 1, unsigned int vz = 1)
    {
      x = vx;
      y = vy;
      z = vz;
    }
  };

dim3 blockDim;

int main() 
{
  return 0;
}
```
Verification result: no enough arguments

symbol table shows:
`blockDim=dim3(( dim3 *)1, 1, 1);`

trees:
```
| |-CXXRecordDecl 0x89b5e90 <col:1, col:8> col:8 implicit referenced struct dim3
| |-FieldDecl 0x89b5f38 <line:3:5, col:18> col:18 x 'unsigned int'
| |-FieldDecl 0x89b5fa0 <col:5, col:21> col:21 y 'unsigned int'
| |-FieldDecl 0x89b6008 <col:5, col:24> col:24 z 'unsigned int'
| |-CXXConstructorDecl 0x89b6290 <line:5:5, col:96> col:5 used dim3 'void (unsigned int, unsigned int, unsigned int)'
| | |-ParmVarDecl 0x89b6090 <col:10, col:28> col:23 used vx 'unsigned int' cinit
| | | `-ImplicitCastExpr 0x89b6388 <col:28> 'unsigned int' <IntegralCast>
| | |   `-IntegerLiteral 0x89b6368 <col:28> 'int' 1
| | |-ParmVarDecl 0x89b6110 <col:31, col:49> col:44 used vy 'unsigned int' cinit
| | | `-ImplicitCastExpr 0x89b63c0 <col:49> 'unsigned int' <IntegralCast>
| | |   `-IntegerLiteral 0x89b63a0 <col:49> 'int' 1
| | |-ParmVarDecl 0x89b6190 <col:52, col:70> col:65 used vz 'unsigned int' cinit
| | | `-ImplicitCastExpr 0x89b63f8 <col:70> 'unsigned int' <IntegralCast>
| | |   `-IntegerLiteral 0x89b63d8 <col:70> 'int' 1
| | |-CXXCtorInitializer Field 0x89b5f38 'x' 'unsigned int'
| | | `-ImplicitCastExpr 0x89b6480 <col:77> 'unsigned int' <LValueToRValue>
| | |   `-DeclRefExpr 0x89b6440 <col:77> 'unsigned int' lvalue ParmVar 0x89b6090 'vx' 'unsigned int'
| | |-CXXCtorInitializer Field 0x89b5fa0 'y' 'unsigned int'
| | | `-ImplicitCastExpr 0x89b6500 <col:84> 'unsigned int' <LValueToRValue>
| | |   `-DeclRefExpr 0x89b64c0 <col:84> 'unsigned int' lvalue ParmVar 0x89b6110 'vy' 'unsigned int'
| | |-CXXCtorInitializer Field 0x89b6008 'z' 'unsigned int'
| | | `-ImplicitCastExpr 0x89b6580 <col:91> 'unsigned int' <LValueToRValue>
| | |   `-DeclRefExpr 0x89b6540 <col:91> 'unsigned int' lvalue ParmVar 0x89b6190 'vz' 'unsigned int'
| | `-CompoundStmt 0x89b65d8 <col:95, col:96>
| `-CXXConstructorDecl 0x89b6690 <line:1:8> col:8 implicit dim3 'void (const dim3 &)' inline default trivial noexcept-unevaluated 0x89b6690
|   `-ParmVarDecl 0x89b67c0 <col:8> col:8 'const dim3 &'
|-VarDecl 0x89b65f8 <line:8:1, col:6> col:6 blockDim 'dim3' callinit
| `-CXXConstructExpr 0x89b6890 <col:6> 'dim3' 'void (unsigned int, unsigned int, unsigned int)'
|   |-CXXDefaultArgExpr 0x89b6830 <<invalid sloc>> 'unsigned int'
|   |-CXXDefaultArgExpr 0x89b6850 <<invalid sloc>> 'unsigned int'
|   `-CXXDefaultArgExpr 0x89b6870 <<invalid sloc>> 'unsigned int'
```
The struct is not of type aggregate because it has a defined constructor, so we may need to consider new cases.

```
dereference failure: invalid pointer
{-1} alloc&0#1 == ARRAY_OF(0)
{-2} is_dynamic&0#1 == ARRAY_OF(0)
|--------------------------
{1} execution_statet::\guard_exec?0!0 => !(!alloc&0#1[POINTER_OBJECT(( dim3 *)1)] && is_dynamic&0#1[POINTER_OBJECT(( dim3 *)1)] || ( dim3 *)1 == invalid-object)
```

**Comment by kunjsong01** [comment]
In the CUDA benchmarks, which test case (or OM in the include tree) requires this feature?

**Comment by XLiZHI** [comment]
> In the CUDA benchmarks, which test case (or OM in the include tree) requires this feature?

@kunjsong01 Thanks for your reply.

The code that caused the error is here:
https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/device_launch_parameters.h#L24-L26

Earlier we resolved  #1006  which is here:
https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/device_launch_parameters.h#L35-L36

The dim3 is implemented here:
https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/vector_types.h#L373

**Comment by kunjsong01** [comment]
So the actual implementation of `dim3` is: 
https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/vector_types.h#L376-L378

in which presumably case __cpluplus is defined when being included in *.cu file --- Is that correct?

**Comment by XLiZHI** [comment]
> So the actual implementation of `dim3` is:
> 
> https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/vector_types.h#L376-L378
> 
> in which presumably case __cpluplus is defined when being included in *.cu file --- Is that correct?

I think so, At present, I do not use any test case. I first test each OM independently, and then use it to verify the CUDA program after ensuring that they can be verified successfully (to ensure that the counter example is from the verified program and not the OM).

I don't think the `defined(__cplusplus)` here is necessary because our OM is based on C++, This is probably a legacy of the original CUDA API, as CUDA is available on C/C++.

We solved a different struct problem before (below).
https://github.com/esbmc/esbmc/blob/04e03148d8d5684bd1eb04a60169412fe85c4601/src/cpp/library/CUDA/vector_types.h#L143-L146

So this is a new situation.

**Comment by kunjsong01** [comment]
closed via https://github.com/esbmc/esbmc/pull/1086
