### ISSUE TITLE
[overflow-check] ESBMC crashes with the overflow-check option with this C program

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1051]
$ esbmc overflow_crash.c --overflow-check
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.661s
Segmentation fault

````C
// FormAI DATASET v1.0. Category: Searching algorithm ; Style: bold
#include<stdio.h>
#include<stdlib.h>

void search(int arr[], int n, int x) {
    int flag = 0, index = 0;
    for(int i = 0; i < n; i++) {
        if(arr[i] == x) {
            flag = 1;
            index = i;
            break;
        }
    }
    if(flag) {
        printf("%d is found at index %d", x, index);
    } else {
        printf("%d is not present in array", x);
    }
}

int main() {
    int n, x;
    printf("Enter size of array: ");
    scanf("%d", &n);

    int *arr = (int*) malloc(n * sizeof(int));
    printf("Enter %d elements: ", n);
    for(int i = 0; i < n; i++) {
        scanf("%d", &arr[i]);
    }

    printf("Enter element to search: ");
    scanf("%d", &x);

    search(arr, n, x);

    return 0;
}
````

**Comment by ChenfengWei0** [comment]
I believe the bug is inside the function `input_overflow_check()`:
```c++
const symbolt &arg = *ns.lookup(arg_names.at(i));
const irep_idt type_id = arg.type.id();  // segfault here
```

It seems that I didn't consider `malloc` at all when I implemented the `scanf/fscanf`. Issue #984 also mentioned another bug relative to `malloc`. 

I will make a PR to add support to the `malloc` situation in the scanf overflow check.

**Comment by lucasccordeiro** [comment]
Many thanks, @ChenfengWei0.

**Comment by tihanyin** [comment]
I have tested the new merge, and it is working now.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1063.
