### ISSUE TITLE
overflow-check is not detecting unsigned integer overflow/underflow

### ISSUE THREAD

**Issue by ghost** [esbmc/esbmc#1056]
When ESBMC is run on the following code snippet with --overflow-check switch, verification passes. However, I was expecting it to flag an underflow at the operation "delta = j - i". When I ran CBMC with --unsigned-overflow-check on the same snippet, CBMC indeed flagged that line. Am I missing anything while running ESMBC with --overflow-check?

#include <stdio.h>
#include <assert.h>

int main(int argc, char **argv)
{
  unsigned int delta = 0;
  unsigned int i=5;
  unsigned int j=3;

  delta = j - i;
  printf("\nDelta %u", delta);

  return 0;
}

**Comment by lucasccordeiro** [comment]
Many thanks for reporting this issue, @sayakray-intel.

@brcfarias: can I ask you to check it?

**Comment by lucasccordeiro** [comment]
Dear @sayakray-intel,

We have just fixed the issue reported here. 

If you update your master branch and recompile ESBMC, you can successfully verify this program as:

esbmc file.c  --unsigned-overflow-check --compact-trace

````
Building error trace

[Counterexample]

State 6 file underflow.c line 6 function main thread 0
----------------------------------------------------
  delta = 0 (00000000 00000000 00000000 00000000)

State 7 file underflow.c line 7 function main thread 0
----------------------------------------------------
  i = 5 (00000000 00000000 00000000 00000101)

State 8 file underflow.c line 8 function main thread 0
----------------------------------------------------
  j = 3 (00000000 00000000 00000000 00000011)

State 9 file underflow.c line 10 function main thread 0
----------------------------------------------------
Violated property:
  file underflow.c line 10 function main
  arithmetic overflow on sub
  !overflow("-", j, i)


VERIFICATION FAILED
````

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1058.
