### ISSUE TITLE
ESBMC crashes if large value is specified in scanf 

### ISSUE THREAD

**Issue by tihanyin** [esbmc/esbmc#1066]
In this small example, scanf() is used to take a large integer as input. Evidently, the code lacks safety and can lead to unpredictable outcomes, commonly referred to as "undefined behavior".
ESBMC 7.2 crashes in this example due to incorrect conversion.

```c
#include <stdio.h>
int main() {
    int n;
    printf("Enter an integer: ");
    scanf("%10000000000d", &n);
    printf("%d\n",n);
    return 0;
}
```

Crash:

`esbmc test.c --overflow
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.381s
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
Aborted (core dumped)
`

**Comment by fbrausse** [comment]
> Evidently, the code lacks safety and can lead to unpredictable outcomes, commonly referred to as "undefined behavior".

Your program does not have UB. The ESBMC crash obviously should not happen, though.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: could you please check this issue?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: could you please check this issue?

Yes, I will work on it.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1076

**Comment by lucasccordeiro** [comment]
Many thanks for fixing this issue, @ChenfengWei0.
