### ISSUE TITLE
[C++ verification] Inconsistent names for class template type symbol

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1075]
./esbmc-new cbmc/Templates2/main.cpp -I library/

```
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.158s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
esbmc-new: ../src/util/base_type.cpp:108: virtual bool base_type_eqt::base_type_eq_rec(const type2tc &, const type2tc &): Assertion `symbol' failed.
Aborted (core dumped)
```

Preliminary analysis:
The context only contains "Symbol......: tag-int_array<3>" but ESBMC tries to find symbol "tag-int_array" in the context.

**Comment by kunjsong01** [comment]
same problem as https://github.com/esbmc/esbmc/issues/1074#issuecomment-1587546801, just happening in a different place in `goto_symext::argument_assignments`.

**Comment by kunjsong01** [comment]
closed via https://github.com/esbmc/esbmc/pull/1079

**Comment by lucasccordeiro** [comment]
Many thanks, @kunjsong01.
