### ISSUE TITLE
ESBMC  crashes : Can't construct rvalue reference to array type during dereference

### ISSUE THREAD

**Issue by tihanyin** [esbmc/esbmc#1087]
ESBMC 7.2 crashes on the following small C example:

```c

//FormAI DATASET v0.1 Category: Resume Parsing System ; Style: multiplayer
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Player struct to hold player information
typedef struct Player {
    char name[20];
    int score;
} Player;

// Function to display player information
void displayPlayer(Player p) {
    printf("Player: %s\n", p.name);
    printf("Score: %d\n", p.score);
}

// Function to compare player scores for sorting
int compare(Player a, Player b) {
    return b.score - a.score;
}

int main() {
    int num_players;
    printf("Enter number of players:");
    scanf("%d", &num_players);
    Player* players = (Player*)malloc(num_players * sizeof(Player));

    // Input player information
    for (int i = 0; i < num_players; i++) {
        printf("\nEnter details of player %d:\n", i+1);
        printf("Name: ");
        scanf("%s", players[i].name);
        printf("Score: ");
        scanf("%d", &players[i].score);
    }

    // Sort players based on score
    qsort(players, num_players, sizeof(Player), (void*)compare);

    // Display sorted player information
    printf("\nSorted player information:\n");
    for (int i = 0; i < num_players; i++) {
        displayPlayer(players[i]);
    }

    // Free memory allocated for players
    free(players);

    return 0;
}
```

ESBMC output:

esbmc --unwind 1 DATA8/FormAI_88177.c
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.126s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Not unwinding 
no body for function qsort
ERROR: Can't construct rvalue reference to array type during dereference
(It isn't allowed by C anyway)

Aborted (core dumped)

**Comment by lucasccordeiro** [comment]
@fbrausse : do we still have this problem? :-) I remember that you fixed many of these issues in the past.

**Comment by fbrausse** [comment]
@lucasccordeiro Indeed, though most of the previous instances were about unions which had been treated as byte-arrays and thus caused this error. This one is trying to construct the `char name[20]` from the dynamic allocation at a dynamic offset. I'll take a look.

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you whether you would have any updates about this issue?
