### ISSUE TITLE
Qt OMs contains duplicate of C++ standard abstractions

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1145]
Both the QtCore and QtGui folders contain an implementation of `string`. The implementation is different from the main abstract model (at cpp/library).

Is there any reason for those headers (a Qt only specific optimization) or we can just remove it?

**Comment by lucasccordeiro** [comment]
@feliperodri worked on these models.

@feliperodri: could you please give some advice here? :-)

**Comment by feliperodri** [comment]
@rafaelsamenezes @lucasccordeiro AFAIK, there should be no difference between the models related to optimizations. You can remove it and try to run the test case again to check for any regressions. We should be able to rely on on `cpp/library/string` model and just create a wrapper for Qt.

**Comment by rafaelsamenezes** [comment]
Thanks @feliperodri
