### ISSUE TITLE
[C++ verification]  Function call to non-intrinsic prefixed

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1147]
version: d58cc47801dafae4cdef24aaa03d3fbda52a392d

cmd: `esbmc main.cpp`

```
#include <pthread.h>

pthread_t __ESBMC_get_thread_id(void);

int main(){
    int threadid;
    threadid = __ESBMC_get_thread_id();
    
    return 0;
}
```
Results:
```
ERROR: Function call to non-intrinsic prefixed with __ESBMC (fatal)
The name in question: c:@F@__ESBMC_get_thread_id#
(NB: the C spec reserves the __ prefix for the compiler and environment)
Aborted
```
This happens only for `cpp` files; changing the file to `c` works fine

**Comment by XLiZHI** [comment]
Preliminary investigation:

https://github.com/esbmc/esbmc/blob/d58cc47801dafae4cdef24aaa03d3fbda52a392d/src/goto-symex/symex_main.cpp#L384-L387

The problem is that in this function, in C++ we get the **symname** variable as `c:@F@__ESBMC_get_thread_id#`. In C, the symname variable is `c:@F@__ESBMC_get_thread_id`.

The difference is an extra # sign

**Comment by mikhailramalho** [comment]
The problem is probably the prefix, we probably only check for upper case
'F', not lower case like in the second case.

This check is done in symex_main, IIRC

**Comment by XLiZHI** [comment]
Hi @mikhailramalho,

Thanks for your reply.

> only check for upper case 'F', not lower case like in the second case

In fact both of them are upper case, probably due to a delay in my previous edit.

The only difference is "#", I suspect this could be due to the different handling of the C++ front end.

**Comment by mikhailramalho** [comment]
Right, so maybe we are comparing the string in symex? Instead of using the
has_prefix call?

**Comment by XLiZHI** [comment]
> Right, so maybe we are comparing the string in symex? Instead of using the has_prefix call?

Yes, exactly! 

So far my solution is to rewrite the following judgment:
https://github.com/esbmc/esbmc/blob/d58cc47801dafae4cdef24aaa03d3fbda52a392d/src/goto-symex/symex_main.cpp#L401

And replace it with `else if(has_prefix(symname, "c:@F@__ESBMC_get_thread_id"))`

But I'm not sure if this change poses a risk.

**Comment by mikhailramalho** [comment]
It should be fine, I'd go ahead and replace everything with has_prefix

**Comment by XLiZHI** [comment]
#1150

**Comment by lucasccordeiro** [comment]
Thanks, @XLiZHI.
