### ISSUE TITLE
Umbrella issue for string OM 

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1156]
ESBMC's string support

### Closing criteria of this issue:
1. `string` OM shall be includable without any parse or conversion errors.
2. `regression/esbmc-cpp/string/` shall have a good pass rate.

N.B. First ignore the warnings and fix the errors to make the OM includable and run the corresponding test suite to evaluate it. Then decide whether we need to fix the warnings based on the warning signature and regressions result.

### This issue serves as an Umbrela for string issues:
Errors/Failed assertions:
- ~~https://github.com/esbmc/esbmc/issues/1145~~
- ~~https://github.com/esbmc/esbmc/issues/1159~~
- ~~https://github.com/esbmc/esbmc/issues/991~~
- ~~https://github.com/esbmc/esbmc/issues/1162~~
- ~~https://github.com/esbmc/esbmc/issues/1203~~

Warnings:
- ~~https://github.com/esbmc/esbmc/issues/1157~~
- ~~https://github.com/esbmc/esbmc/issues/1158~~

**Comment by kunjsong01** [comment]
related to https://github.com/esbmc/esbmc/issues/1355

**Comment by XLiZHI** [comment]
Fixed all assertions and warnings.

> regression/esbmc-cpp/string/ shall have a good pass rate.

pass rate: 82.91%

**Comment by lucasccordeiro** [comment]
> pass rate: 82.91%

Very good ;-) 

How much did we get with ESBMC v2.1?

**Comment by XLiZHI** [comment]
> How much did we get with ESBMC v2.1?

I haven't used esbmc v2.1 yet, and I need to learn how to build and run regression tests :)

**Comment by lucasccordeiro** [comment]
> I haven't used esbmc v2.1 yet, and I need to learn how to build and run regression tests :)

It will be important for our journal paper.

Can you check whether @kunjsong01 has documented it somewhere?

Please check this paper https://onlinelibrary.wiley.com/doi/epdf/10.1002/stvr.1793, too.

**Comment by kunjsong01** [comment]
Hi @lucasccordeiro @XLiZHI , 

I completed some experiments with v2.1 against each test suite in August 2023 and documented the pass rate in our SBMF'23 paper https://arxiv.org/abs/2308.05649 

For string test suites, we got 99% pass rate with ESBMC v2.1.

**Comment by XLiZHI** [comment]
> Hi @lucasccordeiro @XLiZHI ,
> 
> I completed some experiments with v2.1 against each test suite in August 2023 and documented the pass rate in our SBMF'23 paper https://arxiv.org/abs/2308.05649
> 
> For string test suites, we got 99% pass rate with ESBMC v2.1.

Hi @kunjsong01, Thanks a lot!
