### ISSUE TITLE
string OM: comparing non-pointer with NULL

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1157]
cmd: ./esbmc-new OM_sanity_checks/string/main.cpp

Got multiple warnings of comparing non-pointer with NULL: 
```
In file included from OM_sanity_checks/string/main.cpp:1:
/tmp/esbmc-cpp-headers-eb73-ce9a-f720/string:629:20: warning: comparison between NULL and non-pointer ('char' and NULL) [-Wnull-arithmetic]
                __ESBMC_assert(c != NULL,
                               ~ ^  ~~~~
```

**Comment by kunjsong01** [comment]
Preliminary analysis: 

Got lots of assertion trying to compare char with NULL, e.g. in string insert method:
```cpp
	iterator insert(iterator p, char c) {
		__ESBMC_assert(p.pos >= 0,
				"The first parameter must to be greater than zero");
		__ESBMC_assert(c != NULL,
				"The second parameter must to be different than NULL");
```

It's probably coming from C because of a null character is needed to terminate a string. 

They might need to be removed. No need to check the value of the char.

**Comment by lucasccordeiro** [comment]
@XLiZHI: can I ask you please to check this issue?

**Comment by XLiZHI** [comment]
close via #1685

**Comment by lucasccordeiro** [comment]
Implemented as suggested by @kunjsong01 ;-)

**Comment by lucasccordeiro** [comment]
We have removed these assertions:

````CPP
__ESBMC_assert(c != NULL,
				"The second parameter must to be different than NULL");
````
