### ISSUE TITLE
string OM: missing returns for non-void functions

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1158]
cmd: ./esbmc-new OM_sanity_checks/string/main.cpp

Got multiple warnings for missing returns:
```
/tmp/esbmc-cpp-headers-eb73-ce9a-f720/string:1515:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
```

**Comment by lucasccordeiro** [comment]
@XLiZHI: can I ask you please to check this issue?

**Comment by XLiZHI** [comment]
close via #1685

**Comment by lucasccordeiro** [comment]
We have essentially returned `npos` if the character is not found.
