### ISSUE TITLE
Failed to build ESBMC

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1169]
Hi, I'm not able to build ESBMC due to the error message:

```
[cmake] CMake Error at src/c2goto/CMakeLists.txt:32 (cmake_language):
[cmake]   Unknown CMake command "cmake_language".
[cmake] Call Stack (most recent call first):
[cmake]   src/c2goto/CMakeLists.txt:47 (foreach_in_cross_product_rec)
[cmake]   src/c2goto/CMakeLists.txt:47 (foreach_in_cross_product_rec)
[cmake]   src/c2goto/CMakeLists.txt:47 (foreach_in_cross_product_rec)
[cmake]   src/c2goto/CMakeLists.txt:53 (foreach_in_cross_product_rec)
[cmake]   src/c2goto/CMakeLists.txt:82 (foreach_in_cross_product)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/home/kunjian/ESBMC_Project/esbmc/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/kunjian/ESBMC_Project/esbmc/build/CMakeFiles/CMakeError.log".
[proc] The command: /usr/bin/cmake --no-warn-unused-cli -DClang_DIR=/home/kunjian/local/llvm15-debug -DLLVM_DIR=/home/kunjian/local/llvm15-debug -DZ3_DIR=/home/kunjian/ESBMC_Project/z3 -DENABLE_OLD_FRONTEND=On -DBUILD_TESTING=On -DBUILD_STATIC=Off -DCMAKE_BUILD_TYPE=Debug -DENABLE_REGRESSION=On -DENABLE_SOLIDITY_FRONTEND=On -DBoolector_DIR=/home/kunjian/ESBMC_Project/boolector-release -DENABLE_MATHSAT=ON -DMathsat_DIR=/home/kunjian/ESBMC_Project/mathsat -DENABLE_YICES=On -DYices_DIR=/home/kunjian/ESBMC_Project/yices -DCVC4_DIR=/home/kunjian/ESBMC_Project/cvc4 -DGMP_DIR=/home/kunjian/ESBMC_Project/gmp -DBitwuzla_DIR=/home/kunjian/ESBMC_Project/bitwuzla-release -DENABLE_COVERAGE=Off -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/home/kunjian/ESBMC_Project/esbmc -B/home/kunjian/ESBMC_Project/esbmc/build -G Ninja exited with code: 1
```

Q1. Does it also happen to other people? or is it just me?

Two more related questions as I just noticed that there were some changes in BUILDING.md...

Q2. Is clang-11 still supported? I'm still using clang-11.0.0 since the dependency says
![Screenshot 2023-07-10 at 08 00 02](https://github.com/esbmc/esbmc/assets/32592800/6929023a-99ee-478d-8374-ee063a33697e)

Q3. Are we going to use CHERI-clang-13 instead of the standard clang-13 for future build? 
![Screenshot 2023-07-10 at 08 03 15](https://github.com/esbmc/esbmc/assets/32592800/15753998-5dd1-41e0-ac09-6fee17031ac2)

**Comment by fbrausse** [comment]
> Q1. Does it also happen to other people? or is it just me?

The PR #905 has increased the min-version requirement for CMake to >= v3.18, due to the usage of `cmake_language`, see <https://cmake.org/cmake/help/latest/command/cmake_language.html>. I will add it to the dependency list. I hope updating it is not a problem. If it is, let me know and I'll try to find another solution to the cartesion product problem I've tried to solve with the construct mentioned in your call trace.

> Q2. Is clang-11 still supported? I'm still using clang-11.0.0 since the dependency says
> Q3. Are we going to use CHERI-clang-13 instead of the standard clang-13 for future build?

From my point of view, building ESBMC with the CHERI-clang is optional. The version spec in the dependencies listed in the build instructions should apply, otherwise it's a bug. I'm still building with clang-11 here, too (without the problem).

**Comment by kunjsong01** [comment]
Some notes on update CMake on ubuntu 20.04: 

Since ubuntu 20.04 uses cmake 3.16, apt-get was not able to upgrade cmake to 3.18+. 
So will need to update it manually. The answer in https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu works. 

After upgrading the cmake and having created the symbolic links in /usr/loca/bin on my PC, just found that the build environment checks CMake availability by running `/usr/local/bin/cmake --version` but trying to run CMake configure from `/usr/bin/cmake <a bunch of ESBMC cmake args...>`. 

So I've got a CMake configure error complaining about failed to run `/usr/bin/cmake <a bunch of ESBMC cmake args...>` . 
If you also see such error, just add more symbolic links in /usr/bin: 
```
sudo ln -s /opt/cmake-3.*your_version*/bin/* /usr/bin
```
