### ISSUE TITLE
[documentation] write documentation about the code coverage

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1187]
@ChenfengWei0: Can you please write a short documentation about the code coverage check you have implemented?

https://ssvlab.github.io/esbmc/documentation.html

**Comment by ChenfengWei0** [comment]
Yes

**Comment by lucasccordeiro** [comment]
Many thanks, @ChenfengWei0 ;-)

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: Can I ask you whether you had a chance to write the documentation? :-)

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: Can I ask you whether you had a chance to write the documentation? :-)

Yes I will do it now.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/ssvlab/ssvlab.github.io/pull/10.
