### ISSUE TITLE
Add automated nightly releases

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1191]
We should do something similar to [orbit](https://github.com/google/orbit/blob/main/.github/workflows/release.yml) and make automated weekly releases of ESBMC.

**Comment by fbrausse** [comment]
Weekly? Nightly? Whatever is chosen is probably helpful for <https://github.com/esbmc/esbmc/issues/359#issuecomment-1636141165>. I would also suggest to run SV-COMP regularly. The latest 300s update doesn't look too good: https://github.com/esbmc/esbmc/commit/06a5435b8b33f7bb5affb4b429d1a0604533c324
