### ISSUE TITLE
string OM: Assertion failure while generating GOTO programs

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1203]
We've managed to get over the conversion and adjustment step, but got an assertion failure during GOTO conversion. 

cmd: ./esbmc-new OM_sanity_checks/string/main.cpp

Error: 
```ruby
Converting
Generating GOTO Program
esbmc-new: /home/kunjian/ESBMC_Project/esbmc/src/irep2/irep2_expr.h:2872: member2t::member2t(const type2tc &, const expr2tc &, const irep_idt &): Assertion `source->type->type_id == type2t::struct_id || source->type->type_id == type2t::union_id' failed.
```

Triage: 
- High priority (high-medium-low)
- Blocking
- Estimate: 3d
- Logged: 3h(1 Aug), 0.5d(10 Aug)

**Comment by kunjsong01** [comment]
Simplified TC: 
```cpp
#include <cassert>

class string {
public:
  int _size;
  char* str;

  string() {
    _size = 2;
  }

  char* do_something() {
    assert(_size == 2);
    this->str = new char[this->_size + 1]; // <--- this is the problematic expression
    return this->str;
  }
};

int main()
{
  assert(1);
  string myStr;
  char* p;
  p = myStr.do_something();
  p[0] = 'h';
  p[1] = 'i';
  p[2] = '\0';
  assert(p[1] == 'i');
  //assert(p[1] != 'i'); // should be 'i'
  delete p;
  return 0;
}
```

Edit: 
The assertion failed as part of the `migrate_expr` in:
https://github.com/esbmc/esbmc/blob/32fe5cd209e0659f78ab3b5b94ac493c8813980b/src/util/migrate.cpp#L1388

When migrating `this->_size` as in `new char[this->_size + 1];`, assertion failed due to the source type is not struct_id, nor union_id, but pointer (which it really is)
```cpp
(gdb) p source.get()->dump()
symbol
* name : c:@S@string@F@do_something#this
* renamelev : Level 0
* level1_num : 0
* level2_num : 0
* thread_num : 0
* node_num : 0
* type : pointer
  * subtype : symbol
      * symbol_name : tag-string
$1 = void
```

**Comment by lucasccordeiro** [comment]
@kunjsong01: you can chat with @fbrausse about this issue.

@fbrausse knows this assertion very well :-)

````
Assertion `source->type->type_id == type2t::struct_id || source->type->type_id == type2t::union_id' failed.
````

**Comment by fbrausse** [comment]
We shouldn't construct member-expressions on pointers. The `->` is a dereference resulting in a struct- or union-typed expression. That's what we should construct the member-expr on.

**Comment by fbrausse** [comment]
For the C frontend this works, building a member of a dereference:
```c
struct S {
};

struct A {
	int (*f)(struct S *);
};

int A_f(struct S *);

int main()
{
	struct A *a = malloc(sizeof(*a));
	struct S s;
	a->f = &A_f;
	a->f(&s);
}
```

**Comment by lucasccordeiro** [comment]
@XLiZHI: Can I ask you to check this issue?

You can sync with @fbrausse to check the best solution for this issue.

**Comment by XLiZHI** [comment]
close via #1686

**Comment by lucasccordeiro** [comment]
Well done, @XLiZHI ;-)
