### ISSUE TITLE
[documentation] write how to use the SMT-lib backend in ESBMC

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1207]
@fbrausse: can I ask you to write a short documentation on how to run the SMT-lib backend in ESBMC in https://ssvlab.github.io/esbmc/documentation.html?

You could reuse the description of your PR: https://github.com/esbmc/esbmc/pull/1193

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you whether you had a chance to look at this issue?

**Comment by fbrausse** [comment]
@lucasccordeiro I've added a usage description of the SMT backends and SMTLIB output in <https://github.com/ssvlab/ssvlab.github.io/commit/b7a8412db24531d345b7f7ef2e16411aafbe13ae> and also fixed some validator errors in <https://github.com/ssvlab/ssvlab.github.io/commit/814ca6ad8f65aa7a8bacb763fe3cd3b88856a2ed>.

**Comment by lucasccordeiro** [comment]
@fbrausse: Thank you very much!
