### ISSUE TITLE
"ld: unknown option: -z" on OSX

### ISSUE THREAD

**Issue by shmarovfedor** [esbmc/esbmc#1212]
I am getting this error when trying to compile ESBMC on OSX: `ld: unknown option: -z`. This happens when `cmake` tries to configure Z3:

`CMake Error at src/solvers/z3/CMakeLists.txt:34 (message):
  Could not use Z3:`

Also when I try compiling without Z3, this error appears eventually during the ESBMC compilation.

**Comment by fbrausse** [comment]
Does this help? It should probably depend on the linker in use instead of `APPLE`, but I don't know what it's CMAKE_CXX_COMPILER_ID is on macOS.
```patch
diff --git a/src/solvers/smtlib/CMakeLists.txt b/src/solvers/smtlib/CMakeLists.txt
index b9fe618ee6..008d5e524f 100644
--- a/src/solvers/smtlib/CMakeLists.txt
+++ b/src/solvers/smtlib/CMakeLists.txt
@@ -22,6 +22,8 @@ target_include_directories(smtlib
 set(stacksize 20971520)  # 20 MB ought to be enough for everyone
 if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /STACK:${stacksize}" CACHE STRING "Linker flags" FORCE)
+elseif(APPLE)
+  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-stack_size,${stacksize}" CACHE STRING "Linker flags" FORCE)
 else()
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-z,stack-size=${stacksize}" CACHE STRING "Linker flags" FORCE)
 endif()
```

**Comment by shmarovfedor** [comment]
Almost works :-) 

`ld: -stack_size must be multiple of segment alignment (16KB)`

**Comment by fbrausse** [comment]
Strange error. According to my understanding of math, 2^14 is a factor of 10*2^21.

**Comment by fbrausse** [comment]
Well, setting the stack size is important for `--smtlib` on the regression suite. The 20 MiB I've chosen because 10 MiB weren't enough (for a Debug build on Linux). If you could find a number of similar magnitude that works for OS X that should be fine.

**Comment by shmarovfedor** [comment]
Very strange. This seems to have solved the problem (i.e., setting 20MB in hex instead of decimal):

```# The smtlib backend needs a larger-than-default stack size (at least in Debug
# builds) because the data structures built for the S-exprs in solver responses
# could be very large and the std::list destructors use a lot of stack space
set(stacksize 0x1400000)  # 20 MB ought to be enough for everyone
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /STACK:${stacksize}" CACHE STRING "Linker flags" FORCE)
else()
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-stack_size,${stacksize}" CACHE STRING "Linker flags" FORCE)
endif()
```

I haven't compiled it yet though, but the `cmake` configuration managed to complete successfully

**Comment by fbrausse** [comment]
> setting 20MB in hex instead of decimal

Indeed. Quite obscure choice of them to fix the base to 16 when parsing the string, see <https://opensource.apple.com/source/ld64/ld64-274.2/src/ld/Options.cpp.auto.html>.

**Comment by rafaelsamenezes** [comment]
I can confirm that this also happens in M1.

>  I don't know what it's CMAKE_CXX_COMPILER_ID 

AppleClang

>  It should probably depend on the linker in use

We can use https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html
