### ISSUE TITLE
Incorrect floating point comparison with NaN in pre-conditions

### ISSUE THREAD

**Issue by emanino** [esbmc/esbmc#1226]
Hi all,

ESBMC returns a counterexample for the code snippet below. It claims that the assert can be triggered if x=NaN. This is correct since NaN==NaN is false. However, x should never be equal to NaN, since the assume would return false too (NaN >= 0 is false)!

```
int main()
{
    double x = nondet_float();
	
	__ESBMC_assume(x >= 0);
	
	__ESBMC_assert(x == x, "");

    return 0;
}
```

I also tried modifying the condition in the assume to the macro `isgreaterequal(x, 0)` defined in `math.h` which guarantees compliance to the IEEE 754 standard. However, this does not fix the issue.

Any idea?

**Comment by fbrausse** [comment]
You can use `--z3` or `--cvc` to solve this correctly. All the other SMT-backends do not seem to encode the floating point equality correctly.

**Comment by lucasccordeiro** [comment]
@emanino: Thanks for reporting this issue.

Closed via https://github.com/esbmc/esbmc/pull/1227.
