### ISSUE TITLE
Problems with generating smtlib using --smtlib --output

### ISSUE THREAD

**Issue by HymnOfLight** [esbmc/esbmc#1239]
I was trying to generate smtlib for this file below:
[annVocalic_L0_R10fxp.zip](https://github.com/esbmc/esbmc/files/12217080/annVocalic_L0_R10fxp.zip)
The parameters are: 
esbmc annVocalic_L0_R10fxp.c --no-div-by-zero-check --force-malloc-success --no-align-check --no-pointer-check --no-bounds-check --interval-analysis --smtlib --output annVocalic_L0_R10fxp.smt
I got a really huge file, and it is still growing: 
![image](https://github.com/esbmc/esbmc/assets/30403502/a4669d47-5d01-4ff6-b634-d59a8cb22673)

But when I try to verify this file without generating smtlib file I can get the verification result in seconds:
![image](https://github.com/esbmc/esbmc/assets/30403502/2de20f4b-ae86-4306-a070-cfcd283d0c54)

The same thing happened when I tried another file, I can get a counterexample very quickly but the smtlib file is huge:
[ACASXU_run2a_1_1_batch_2000_simp.zip](https://github.com/esbmc/esbmc/files/12217183/ACASXU_run2a_1_1_batch_2000_simp.zip)
![image](https://github.com/esbmc/esbmc/assets/30403502/d2ff1383-6d13-409e-b9a9-61b98e2c5ab1)

I recommended to try this one. It doesn't require any dependencies.

**Comment by fbrausse** [comment]
Could you please also provide the missing header file(s):
```
annVocalic_L0_R10fxp.c:2:10: fatal error: '../../../dsverifier/definitions.h' file not found
```

We recently fixed a similar issue with the smtlib backend in #1223. It is possible this issue might already be fixed on current master.

**Comment by fbrausse** [comment]
For the second file I get a very fast encoding to SMT-LIBv2:
```
esbmc gh-1239/ACASXU_run2a_1_1_batch_2000_simp.c --no-div-by-zero-check --force-malloc-success --no-align-check --no-pointer-check --no-bounds-check --interval-analysis --smtlib --output ACASXU_run2a_1_1_batch_2000_simp.smt2
[...]
Encoding to solver time: 0.019s
Solving with solver Text output
Runtime decision procedure: 0.000s
```

**Comment by HymnOfLight** [comment]
> Could you please also provide the missing header file(s):
> 
> ```
> annVocalic_L0_R10fxp.c:2:10: fatal error: '../../../dsverifier/definitions.h' file not found
> ```
> 
> We recently fixed a similar issue with the smtlib backend in #1223. It is possible this issue might already be fixed on current master.
[headers.zip](https://github.com/esbmc/esbmc/files/12219149/headers.zip)
Hi please check these header files.

**Comment by lucasccordeiro** [comment]
Hi @fbrausse,

I think I have these files.

[dsverifier.zip](https://github.com/esbmc/esbmc/files/12219248/dsverifier.zip)

**Comment by fbrausse** [comment]
Many thanks, I believe this bug is already taken care of on current master:
```
../esbmc -I a/b/c annVocalic_L0_R10fxp.c --no-div-by-zero-check --force-malloc-success --no-align-check --no-pointer-check --no-bounds-check --interval-analysis --smtlib --output /dev/null
[...]
Encoding to solver time: 1.534s
Solving with solver Text output
Runtime decision procedure: 0.000s
```
The output file is 16 mega bytes. Could you confirm whether the latest nightly build https://github.com/esbmc/esbmc/releases/tag/nightly-f7bdaee6802eb6cfd6fc15d256cbb3b9564246b6 solves the problem for you?

**Comment by HymnOfLight** [comment]
> Many thanks, I believe this bug is already taken care of on current master:
> 
> ```
> ../esbmc -I a/b/c annVocalic_L0_R10fxp.c --no-div-by-zero-check --force-malloc-success --no-align-check --no-pointer-check --no-bounds-check --interval-analysis --smtlib --output /dev/null
> [...]
> Encoding to solver time: 1.534s
> Solving with solver Text output
> Runtime decision procedure: 0.000s
> ```
> 
> The output file is 16 mega bytes. Could you confirm whether the latest nightly build https://github.com/esbmc/esbmc/releases/tag/nightly-f7bdaee6802eb6cfd6fc15d256cbb3b9564246b6 solves the problem for you?

Yes I downloaded this latest version, and the problem solved. Thank you very much.
