### ISSUE TITLE
[sv-comp] check whether we're using the SV-COMP 2023 benchmarks

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1249]
Our statistics show 26459 file, but SV-COMP reports only 23805.

**Comment by rafaelsamenezes** [comment]
We are currently using: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/tree/3d3b5d7d91b78f49e6cc3874002d23fdc4b3d1b4

**Comment by lucasccordeiro** [comment]
Which version is Dirk using in SV-COMP 2023?

**Comment by fbrausse** [comment]
According to https://link.springer.com/chapter/10.1007/978-3-031-30820-8_29 the git-tag `svcomp23` was used:
![image](https://github.com/esbmc/esbmc/assets/3314468/54d4b04b-b79b-429b-9b14-02e7f73002ee)

Since #1334 switches to that tag, I linked this issue to it.

**Comment by lucasccordeiro** [comment]
Great!

Thanks, @fbrausse.
