### ISSUE TITLE
[data-races-check] unsupported cases

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1255]
`esbmc main.c --data-races-check`  same if add `--no-por`

```
#include <pthread.h>

void* t1(void *arg) {
    int* shared = (int*) arg;
    *shared = 4;                 //race here

    return NULL;
}

void* t2(void *arg) {
    int* shared = (int*) arg;
    *shared = 2;                //race here

    return NULL;
}

int main() {
    pthread_t id1, id2;
    int shared_data = 0;

    pthread_create(&id1, NULL, t1, &shared_data);
    pthread_create(&id2, NULL, t2, &shared_data);

    pthread_join(id1, NULL);
    pthread_join(id2, NULL);

    return 0;
}
```
There is a data race in the above code, I checked our TCs about data race check, I found that this case is not covered.

By the way, CUDA OM is implemented based on this formalism, and I think this is why we failed to detect data races.

**Comment by lucasccordeiro** [comment]
Hi @XLiZHI,

Our data race check does not add assertions for pointer variables, so we would need to extend this check to handle such cases.

Alternatively, can you replace these pointers with global variables in the CUDA operational models?

**Comment by lucasccordeiro** [comment]
@XLiZHI:

You could start checking whether the value set analysis is providing the correct outcome:

https://github.com/esbmc/esbmc/blob/master/src/esbmc/esbmc_parseoptions.cpp#L1703
https://github.com/esbmc/esbmc/blob/master/src/pointer-analysis/value_set_analysis.h

After that, you could check the addition of the data race checks at:

https://github.com/esbmc/esbmc/blob/master/src/goto-programs/add_race_assertions.cpp#L81

**Comment by XLiZHI** [comment]
```
#include <pthread.h>

void t1(int *A) {
    *A = 1;                          <------write
}

void t2(int *A) {
    *A = 2;                         <-------write
}

struct arg {
    int *a;
    void (*func)(int *);
};

arg dev_one;
arg dev_one1;

void *execute(void *args) {
    dev_one.func(dev_one.a);
    return NULL;
}

void *execute1(void *args) {
    dev_one1.func(dev_one1.a);
    return NULL;
}

int main() {
    int data = 2;

    dev_one.a = &data;
    dev_one.func = t1;

    dev_one1.a = &data;
    dev_one1.func = t2;

    pthread_t id1, id2;

    pthread_create(&id1, NULL, execute, NULL);
    pthread_create(&id2, NULL, execute1, NULL);

    pthread_join(id1, NULL);
    pthread_join(id2, NULL);

    return 0;
}
```
This is a simplified version of COM that reproduces the undetected data race problem.

**Comment by lucasccordeiro** [comment]
@XLiZHI: Is there some chance that you can debug further the data race check to support the first example in this issue?

**Comment by XLiZHI** [comment]
close via #1456
