### ISSUE TITLE
[smt backend] add the new Bitwuzla release to ESBMC

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#1285]
Release: https://github.com/bitwuzla/bitwuzla/releases/tag/0.1.1

Paper: https://link.springer.com/chapter/10.1007/978-3-031-37703-7_1

API changes: https://github.com/bitwuzla/bitwuzla/blob/main/NEWS.md#c-api

**Comment by fbrausse** [comment]
This has been taken care of, twice ;) #1286 and #1318.

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse ;-)
