### ISSUE TITLE
Add build configurations

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#13]
Add a BuildType.cmake module, similar to BuildStatic.

It should contain:
- Release
- Debug
- RelWithDebInfo

**Comment by rafaelsamenezes** [comment]
This should already work out-of-box with CMake. Just add: 

`-DCMAKE_BUILD_TYPE=Release`
`-DCMAKE_BUILD_TYPE=Debug`
`-DCMAKE_BUILD_TYPE=RelWithDebInfo`
`-DCMAKE_BUILD_TYPE=MinSizeRel`

More info at the CMake docs: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

**Comment by mikhailramalho** [comment]
That's not actually what I requested in your first PR.

I wanted a default option for CMAKE_BUILD_TYPE and to limit the options you can select when using ccmake or cmake-gui.

PR #102 implements this behaviour.
