### ISSUE TITLE
error while loading shared libraries: libbitwuzlabb.so: No such file or directory

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#1302]
Steps to reproduce:
1. install bitwuzla into some local prefix directory
    ```
    git clone -b 0.1.1 git@github.com:bitwuzla/bitwuzla.git bitwuzla-0.1.1 &&
    cd bitwuzla-0.1.1 &&
    mkdir prefix &&
    ./configure.py --shared --prefix $PWD/prefix &&
    ninja -C build install &&
    export BITW=$PWD/prefix
    ```
2. configure ESBMC to use this directory
    ```
    cd esbmc &&
    mkdir build &&
    cd build &&
    cmake .. -DBitwuzla_DIR=${BITW} -DBUILD_STATIC=OFF &&
    ninja
    ```
3. run `src/esbmc/esbmc`:
    ```
    src/esbmc/esbmc: error while loading shared libraries: libbitwuzlabb.so: cannot open shared object file: No such file or directory
    ```

`ldd src/esbmc/esbmc | grep "not found"` reports (for me)
```
	libbitwuzlabb.so => not found
	libbitwuzlabv.so => not found
	libbitwuzlals.so => not found
```

These libraries are in ${BITW}/lib64 for me, but the rpath is not set. This most likely is the meson-related problem https://github.com/mesonbuild/meson/issues/2567 which they claim has been fixed in v0.55 via https://github.com/mesonbuild/meson/pull/7103 though I don't understand how to apply whatever the fix finally might have been.

This is a workaround:
```
patchelf --add-rpath '$ORIGIN/../lib64' ${BITW}/lib64/libbitwuzla.so
```

It looks like this issue is one of Bitwuzla's build system and not of ours. But I've opened it here anyway in case someone has the same problem. We should follow up with the Bitwuzla folks about this.

**Comment by fbrausse** [comment]
@lucasccordeiro Can we update Bitwuzla to revision 1b39f0965b1b2df27db4a2014992ae422fa18790 (or their main branch)?

**Comment by lucasccordeiro** [comment]
Yes, sure.

Please go ahead ;-)
