### ISSUE TITLE
Collate test cases for rvalue reference support

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#1322]
As part of our TDD-driven continuous improvement for ESBMC++, we need to have a good test suite for rvalue reference and move semantics. 

Test coverage: 
- move constructor
- move assignment
- std::move
- any use case reported from ESBMC++ users

**Comment by lucasccordeiro** [comment]
@XLiZHI: can I ask you to please check this issue?

**Comment by XLiZHI** [comment]
Close via #1595 and #1614

**Comment by lucasccordeiro** [comment]
Many thanks, @XLiZHI.
