### ISSUE TITLE
Discussion of same goto functions

### ISSUE THREAD

**Issue by Anthonysdu** [esbmc/esbmc#1328]
Hi all,

I have a goto file by `esbmc --goto-functions-only`,

there are many functions with the same name in this generated file:

```
read_pmcr_el0 (c:arch_helpers.h@F@read_pmcr_el0):
  ...        
  instructions
  ...

read_pmcr_el0 (c:arch_helpers.h@F@read_pmcr_el0#-mc-1):
  ...        
  instructions
  ...

read_pmcr_el0 (c:arch_helpers.h@F@read_pmcr_el0#-mc-2):
  ...        
  instructions
  ...

...
```
And it calls the function as:

```
unsigned long int return_value$_read_pmcr_el0$3;
FUNCTION_CALL:  return_value$_read_pmcr_el0$3=read_pmcr_el0()
feat_reg0=feat_reg0 | ((return_value$_read_pmcr_el0$3 & (~0 >> 64 - 5) << 11) >> 11) + 0 << 23;
```

The question is how esbmc do symex for it? Will it call all of the functions with this name? Thanks.

**Comment by mikhailramalho** [comment]
These are functions created by the c_link code; it could be a function definition in a header that multiple files include.

**Comment by Anthonysdu** [comment]
> These are functions created by the c_link code; it could be a function definition in a header that multiple files include.

Thanks!
