### ISSUE TITLE
ESBMC aborts with "Can't construct rvalue reference to array type during dereference" in valid program

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#134]
In the following program:
```
#include<stdlib.h>
#include<assert.h>

struct A {
  char alloc;
  int b[];
} a;

int main() {
  struct A *e = calloc(1, sizeof(struct A) + 3*sizeof(int));
  (*e).b[3] = a.b[0];
  assert((*e).b[3] == 0);
  *e;
  free(e);
}
```

ESBMC aborts in `*e`, with the following message:
```
Can't construct rvalue reference to array type during dereference
(It isn't allowed by C anyway)
Aborted (core dumped)
```

**Comment by lucasccordeiro** [comment]
The implementation of our function `__memset_impl` seems to lead to error messages like this one:

```
Can't construct rvalue reference to array type during dereference
(It isn't allowed by C anyway)
````

**Comment by fbrausse** [comment]
With #606 I'm getting
```
Counterexample:

State 50 file gh-134.c line 10 function main thread 0
----------------------------------------------------
  e = ( struct A *)(&dynamic_1_array[0])

State 52 file gh-134.c line 11 function main thread 0
----------------------------------------------------
Violated property:
  file gh-134.c line 11 function main
  dereference failure: array bounds violated


VERIFICATION FAILED
```
That's a step forward, I believe.

**Comment by lucasccordeiro** [comment]
Excellent, @fbrausse ;-)

We're looking forward to integrating this patch into the master soon ;-)

**Comment by lucasccordeiro** [comment]
@fbrausse: Have you added this C program as a regression test to your PR?

**Comment by fbrausse** [comment]
@lucasccordeiro there are still fixes to be done for this issue, it should be VERIFICATION SUCCESSFUL, shouldn't it? At least the rvalue stuff is out of the way and now it seems to be the same as #300.

**Comment by lucasccordeiro** [comment]
@fbrausse: You can add this test case as a `KNOWNBUG` :-)

**Comment by fbrausse** [comment]
> there are still fixes to be done for this issue, it should be VERIFICATION SUCCESSFUL, shouldn't it?

With fresh eyes: no, it shouldn't. The array-bounds are indeed overrun by
```c
  (*e).b[3] = a.b[0];
```
Everything is correct, sorry for the noise. Will add this test case in another PR.
