### ISSUE TITLE
Conversion from clang::PrintingPolicy to bool

### ISSUE THREAD

**Issue by alecs184** [esbmc/esbmc#136]
I'm compiling the current ESBMC version cloned from the master with clang:6.0.0: 

../../src/clang-c-frontend/clang_c_convert.cpp:2449:73: error: no viable conversion from
      'clang::PrintingPolicy' to 'bool'
      clang::TypeName::getFullyQualifiedName(fd.getType(), *ASTContext, Policy);
                                                                        ^~~~~~
/home/alecs184/clang/include/clang/AST/QualTypeNames.h:75:40: note: passing argument to
      parameter 'WithGlobalNsPrefix' here
                                  bool WithGlobalNsPrefix = false);
                                       ^
../../src/clang-c-frontend/clang_c_convert.cpp:2520:51: error: no viable conversion from
      'clang::PrintingPolicy' to 'bool'
    ASTContext->getTagDeclType(&rd), *ASTContext, Policy);
                                                  ^~~~~~
/home/alecs184/clang/include/clang/AST/QualTypeNames.h:75:40: note: passing argument to
      parameter 'WithGlobalNsPrefix' here
                                  bool WithGlobalNsPrefix = false);
                                       ^
2 errors generated.
Makefile:545: recipe for target 'clang_c_convert.lo' failed
make[3]: *** [clang_c_convert.lo] Error 1
make[3]: Leaving directory '/home/alecs184/HanuIII/Project_ESBMC/esbmc-private/build/clang-c-frontend'
Makefile:585: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/alecs184/HanuIII/Project_ESBMC/esbmc-private/build/clang-c-frontend'
Makefile:566: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/alecs184/HanuIII/Project_ESBMC/esbmc-private/build'
Makefile:456: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lucasccordeiro** [comment]
Hello @alecs184,

It looks like `getFullyQualifiedName` now expects a `Boolean` instead of `PrintingPolicy`.

@mikhailramalho and @rafaelsamenezes: Which version are we currently supporting of Clang?

Thanks,
Lucas

**Comment by rafaelsamenezes** [comment]
Currently we are supporting Clang version 9 only.

The CI script should help with all dependencies that we use: https://github.com/esbmc/esbmc/blob/master/.github/workflows/release.yml#L17-L19

BTW, [an error ](https://github.com/esbmc/esbmc/blob/master/scripts/cmake/FindLLVM.cmake#L22)should have been thrown for an invalid Clang version during CMake. @alecs184 , may I ask your environment?

**Comment by alecs184** [comment]
I read in the release notes that only Clang 6.0.0 is supported.

Shall the release notes be updated?

**Comment by rafaelsamenezes** [comment]
The [release-notes](https://github.com/esbmc/esbmc/blob/master/scripts/release-notes.txt) is referring to a specific release of ESBMC which can be accessed using tags. 

This dependency should be added into the README/Wiki.

**Comment by rafaelsamenezes** [comment]
I will close this issue. If you have any problems with Clang feel free to reopen it.

- The issue https://github.com/esbmc/esbmc/issues/137 will refer to fixing the documentation.
