### ISSUE TITLE
Interval analysis yields unsound unreach-proof

### ISSUE THREAD

**Issue by Novak756** [esbmc/esbmc#1363]
Hi, given the program
```c
extern void __VERIFIER_error(void);
extern unsigned short __VERIFIER_nondet_ushort(void);
int main(){
	unsigned short T2_460 = __VERIFIER_nondet_ushort();
	if((unsigned int) ((unsigned int) (((unsigned short)(T2_460)) + ((unsigned int) 0))) <= (unsigned int) ((unsigned int) 65536)){
		if(!((unsigned int) (((unsigned int) 112) - ((unsigned int) (((unsigned short)(T2_460)) + ((unsigned int) 72)))) < (unsigned int) ((unsigned int) 63))){
			__VERIFIER_error();
		}
	}    
       return 0;
}
```
ESBMC returns `VERIFICATION SUCCESSFUL` when running with the flag `--interval-analysis` (`esbmc --interval-analysis bug.c`).
However the bug should be reachable and when running without flags ESBMC does find the error.

Commit version: 57d538ea93ad58343a1c089a04e5192c1cd2c5e3
Backend Solver: Boolector 3.2.1
OS: Ubuntu 20.04

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please check this issue?

**Comment by rafaelsamenezes** [comment]
I am unable to replicate it on my local WSL2. Both `esbmc bug.c` and `esbmc bug.c --interval-analysis` give me the same results.
@Novak756 could you give me more info about how you invoked cmake for the build?

**Comment by Novak756** [comment]
Hi , I used `cmake .. -GNinja -DDOWNLOAD_DEPENDENCIES=On -DBUILD_STATIC=ON -DENABLE_BOOLECTOR=ON -DBoolector_DIR=$PWD/../../boolector-release -DENABLE_Z3=ON -DZ3_DIR=$PWD/../../z3 -DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat -DENABLE_YICES=On -DYices_DIR=$PWD/../../yices -DENABLE_CVC4=ON -DCVC4_DIR=$PWD/../../cvc4 -DGMP_DIR=$PWD/../../gmp -DENABLE_BITWUZLA=ON -DENABLE_BITWUZLA=ON -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release`
`cmake --build . -j1`
`ninja install`
I didn't manage to build the cheri-c llvm so I used the download-dependencies flag to fetch llvm.
I also attached the [Dockerfiles](https://github.com/esbmc/esbmc/files/12685002/Dockers.zip) I used, if that helps.

**Comment by Novak756** [comment]
Also in case it helps, the full output I get when running with --interval-analysis:
```plaintext
ESBMC version 7.3.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing /host/bug.c
Converting
Generating GOTO Program
GOTO program creation time: 0.056s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Symex completed in: 0.000s (15 assignments)
Slicing time: 0.000s (removed 9 assignments)
Generated 1 VCC(s), 1 remaining after simplification (6 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.1
Runtime decision procedure: 0.000s
BMC program time: 0.001s

VERIFICATION SUCCESSFUL
```

**Comment by Novak756** [comment]
[@rafael ](https://github.com/rafaelsamenezes) I'm very, very, very  sorry, but I just noticed that I posted the wrong program...
The correct program that triggers the behaviour is:
```c
extern void __VERIFIER_error(void);
extern unsigned short __VERIFIER_nondet_ushort(void);
int main(){
	unsigned short T2_460 = __VERIFIER_nondet_ushort();
	if((unsigned int) ((unsigned int) (((unsigned short)(T2_460)) + ((unsigned int) 0))) <= (unsigned int) ((unsigned int) 65536)){
		if(!((unsigned int) (((unsigned int) 112) - ((unsigned int) (((unsigned short)(T2_460)) + ((unsigned int) 72)))) < (unsigned int) ((unsigned int) 63))){
			__VERIFIER_error();
		}
	}    
       return 0;
}
```
The behaviour should be as described above

**Comment by Novak756** [comment]
Are you able to reproduce the error with the corrected version of bug.c? I still get the wrong result on the latest commit (cb4c9bdcc915e90786ad8054bc16d7cb6f945767).

**Comment by rafaelsamenezes** [comment]
> Are you able to reproduce the error with the corrected version of bug.c? I still get the wrong result on the latest commit 

Yes, I am able to reproduce it now

**Comment by lucasccordeiro** [comment]
@Novak756: bug fixed. Thank you for your report!

Can I ask you to try the version in the master?

Please let us know if you find other issues.
