### ISSUE TITLE
Default memlimit on C++ regression tests conflicts with AddressSanitizer

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#1381]
On a CMAKE_BUILD_TYPE=Sanitizer build of current master, I'm getting these crashes:
```
ESBMC version 7.3.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
=================================================================
ERROR: Failed to mmap
```
for nearly all C++ regression tests, which have the `--memlimit 14000000` setting. That's 14 mio. MiB, way more than I have. When removing this setting, most of the regression tests work.

Can we remove this memlimit setting from the regression tests? Why is it there and why just for C++ tests?

*Edit:* Turns out, the default unit is `m` if none is given. So 14000000 is 14 TB. I'm sure that's not the right default.

**Comment by lucasccordeiro** [comment]
You can remove these limits. 

We added this option when we extended ESBMC for C++ programs.

**Comment by fbrausse** [comment]
Thanks, Lucas. Will do.
