### ISSUE TITLE
ESBMC is unable to print out the SSA

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1389]
`esbmc main.c --ssa-trace`

```
#include <assert.h>
#include <pthread.h> 

int X = 0;
int Y = 0;

void* thread() {
  if(Y)
    Y = 1;
}

int main() {
  pthread_t t1;
  pthread_create(&t1, NULL, thread, NULL);
  X = 1;
  assert(X==1);
  return 0;
}
```

All SSA-related prints in flag are invalidated, has this happened to anyone?

```
  --ssa-symbol-table                    show symbol table along with SSA
  --ssa-guards 
  --ssa-sliced                          print the sliced SSAs
  --ssa-no-location
  --ssa-trace                           print SSA during SMT encoding
  --ssa-smt-trace                       print generated SMT during SMT encoding
  --symex-ssa-trace                     print generated SSA during symbolic execution
```

**Comment by fbrausse** [comment]
> Generated 8 VCC(s), 0 remaining after simplification (-470 assignments)

The `0 remaining after simplification` is the reason there is no SSA. If there are no VCCs then there's no need to unroll the steps into SSA. If you replace `X = 1` with `X = nondet_int()` you'll see the SSA flags working.

**Comment by XLiZHI** [comment]
> > Generated 8 VCC(s), 0 remaining after simplification (-470 assignments)
> 
> The `0 remaining after simplification` is the reason there is no SSA. If there are no VCCs then there's no need to unroll the steps into SSA. If you replace `X = 1` with `X = nondet_int()` you'll see the SSA flags working.

I see, thank you for your explanation!
