### ISSUE TITLE
Could not build ESBMC due to a CMake error

### ISSUE THREAD

**Issue by mihaistate** [esbmc/esbmc#1394]
I have a Linux Mint VM. When I try to build ESBMC with all the solvers being set up, I get this llvm missing file error. I installed llvm by executing the commands from the last answer of this thread: https://askubuntu.com/questions/1286131/how-do-i-install-llvm-10-on-ubuntu-18-04. I didn't find a folder in the local or bin directories that would contain a LLVMConfig.cmake file. I tried this, but didn't solve the issue : export LLVM_DIR=/bin/ (the bin folder contains the llvm packages).

![image](https://github.com/esbmc/esbmc/assets/92514330/a7361397-d5cd-4920-aa43-7e393fc2d7c9)

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please check this issue?

**Comment by rafaelsamenezes** [comment]
Hi, @mihaistate. Using the apt shipped LLVM is currently not supported on our build chain. The recommended approach is using the prebuilt releases of it (you can download from their GitHub repo) when building ESBMC. In your case, it should be enough to just pass `-DDOWNLOAD_DEPENDENCIES=On` and remove `LLVM_DIR` and `Clang_DIR` from your cmake command.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please update our building instructions with this information?

**Comment by mihaistate** [comment]
@rafaelsamenezes Thanks! I followed the instructions from here: https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm and when I run the build command, I get these errors. The configuration command that I used is cmake -S llvm -B build -GNinja -DLLVM_ENABLE_PROJECTS='clang;lld' -DCMAKE_INSTALL_PREFIX=usr/local -DCMAKE_BUILD_TYPE=Debug -DDLVM_ENABLE_ASSERTIONS=ON -DLLVM_USE_LINKER=lld -DLLVM_PARALLEL_{COMPILE,LINK}_JOBS=N.
![image](https://github.com/esbmc/esbmc/assets/92514330/714831bf-1c4c-4bd5-8159-c22ee68283a2)

**Comment by fbrausse** [comment]
@mihaistate I don't think you need to build LLVM/Clang from scratch. In order to get started with ESBMC just run
```
cd esbmc && rm -r build && mkdir build && cd build && cmake -DDOWNLOAD_DEPENDENCIES=ON ..
```
This will download and use a pre-built binary version of LLVM/Clang for Ubuntu (which Mint is based on, as far as I know). If that works, you can then add the additional solvers mentioned in your initial post. If it doesn't work, please let us know together with the output of the cmake command.

**Comment by fbrausse** [comment]
PS: On Ubuntu-based distros it might be enough to install the `libclang-cpp-dev` package to get all LLVM/Clang dependencies, then you shouldn't even need the `-DDOWNLOAD_DEPENDENCIES=ON` cmake switch. For reference, with these Ubuntu packages configuring ESBMC works for me:
```
libclang-cpp11-dev libclang-cpp11 libclang-common-11-dev llvm-11-runtime clang-11 llvm-11-linker-tools llvm-11-tools llvm-11 llvm-11-dev libclang-11-dev libclang1-11
```
Alternatively you could take a look what the [scripts/build.sh](https://github.com/esbmc/esbmc/blob/master/scripts/build.sh) script is doing.

**Comment by mihaistate** [comment]
@fbrausse Thank you! I have all the above packages, expect llvm-11-linker-tools, which I tried to install manually (couldn't locate it with apt) from here: https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/llvm-11-linker-tools_11.1.0-6_amd64.deb.html, but it throwed an unsatisfied dependency: libc6(=>2.34) and couldn't solve it. 

Besides that, I have a package config not found error: ClangConfig.cmake, clang-config.cmake, so I run the build commands for the CHERI CLang package and have this error: 
![image](https://github.com/esbmc/esbmc/assets/92514330/dcdebdb3-4705-48d5-87ea-11f27af8e00b)

I have the lld driver installed and have already done my research on this error and couldn't find anything that helped me. 

The updated build command for ESBMC that I tried is cmake .. -GNinja -DDOWNLOAD_DEPENDENCIES=On -DBUILD_TESTING=On -DENABLE_REGRESSION=On -DBUILD_STATIC=On -DBoolector_DIR=$PWD/../../boolector-release -DZ3_DIR=$PWD/../../z3 -DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat -DENABLE_YICES=On -DYices_DIR=$PWD/../../yices -DCVC4_DIR=$PWD/../../cvc4 -DGMP_DIR=$PWD/../../gmp -DBitwuzla_DIR=$PWD/../../bitwuzla-release -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release

**Comment by fbrausse** [comment]
@mihaistate Thanks for the update. The ESBMC cmake command looks fine.

As for the CHERI one: Let's take a step back, I'm still not entirely clear what you want to achieve. The BUILDING.md instructions do contain a reference to the CHERI-Clang, that's true. But it's not required and ESBMC can be built just against the normal Clang (as shipped by distros or the binaries downloaded via DOWNLOAD_DEPENDENCIES). I will update the instructions shortly.

Do you want to use the experimental CHERI-C support in ESBMC or do you just want to verify standard C/C++ programs? If just standard C/C++ then I would suggest to skip the CHERI build. What's the output of the ESBMC cmake command you posted last?

**Comment by mihaistate** [comment]
This is the output for the above build command for ESBMC. I would like to have it built only to be able to use the ESBMC-AI tool: https://github.com/Yiannis128/esbmc-ai. So, I guess that I may not need CHERI for that, right? 
![image](https://github.com/esbmc/esbmc/assets/92514330/ea627fd5-0ff7-4453-b1c6-f4e22f511319)

**Comment by fbrausse** [comment]
> I would like to have it built only to be able to use the ESBMC-AI tool: https://github.com/Yiannis128/esbmc-ai. So, I guess that I may not need CHERI for that, right?

Right, no need for CHERI, skip that. And I'm sorry for the confusing instructions.

From the CMake output it seems to default to the system's llvm-10, which unfortunately is too old. We need llvm-11 or higher. Can you add `-DLLVM_DIR=/usr/lib/llvm-11/lib/cmake/llvm -DClang_DIR=/usr/lib/cmake/clang-11` to the command line? (I am assuming that these directories exist since you installed the packages mentioned earlier.)

**Comment by mihaistate** [comment]
![image](https://github.com/esbmc/esbmc/assets/92514330/6074056f-6ec6-4873-8a86-9065b70d14a9)

![image](https://github.com/esbmc/esbmc/assets/92514330/1352b26d-f199-4982-8acc-3c6ecf24d7c6)

Thank you for your suggestions! I managed to update llvm-11, now I also have llvm-12, for which I get the same errors

**Comment by fbrausse** [comment]
> llvm-12, for which I get the same errors

Indeed, my mistake, sorry. Building statically against the system's llvm unfortunately does not work. There is an open ticket about a similar issue (#1359), but it's still unclear how to resolve it on our side. You have 2 options:
1. static build: please remove and re-create the "build" directory and re-run the cmake command with `-DDOWNLOAD_DEPENDENCIES=ON` and *without* the `-DLLVM_DIR` and `-DClang_DIR` being set.
2. shared build: please remove and re-create the "build" directory and re-run the cmake command with `-DBUILD_STATIC=OFF` instead of `ON`.

**Comment by mihaistate** [comment]
Here I kept the DLLVM and DClang_DIR arguments and turned BUILD_STATIC to OFF:
![image](https://github.com/esbmc/esbmc/assets/92514330/6e883db7-605c-4a4c-ad0a-6eeac927b186))

I removed the DDLVM and DClang_DIR arguments and turned on the BUILD_STATIC:
![image](https://github.com/esbmc/esbmc/assets/92514330/4c5e38a0-4290-4316-83bf-ab6d05f23992)

**Comment by fbrausse** [comment]
> Here I kept the DLLVM and DClang_DIR arguments and turned BUILD_STATIC to OFF:

Well, you've switched LLVM to v12 but kept Clang at v11. That can't work.

Please make sure to remove the "build" directory and re-create it before attempting anew. CMake sometimes caches values set previously and isn't happy changing them on the fly.

**Comment by mihaistate** [comment]
I used this command and it works:cmake .. -GNinja -DDOWNLOAD_DEPENDENCIES=ON -DBUILD_TESTING=On -DENABLE_REGRESSION=ON -DBUILD_STATIC=ON -DBoolector_DIR=$PWD/../../boolector-release -DZ3_DIR=$PWD/../../z3 -DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat -DENABLE_YICES=On -DYices_DIR=$PWD/../../yices -DCVC4_DIR=$PWD/../../cvc4 -DGMP_DIR=$PWD/../../gmp -DBitwuzla_DIR=$PWD/../../bitwuzla-release -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release. Just to mention, I updated my Linux Mint to the latest version in the meantime.

This command, cmake --build . && ninja install, throws some errors, but, since I use esbmc just to build esbmc-ai, I eventually opted for downloading the executable instead of building it from source. For now, I am not going to build esbmc anymore.

**Comment by fbrausse** [comment]
@mihaistate If that works for you, great! We have also updated our build instructions and I'm thinking about adding an interactive script that should simplify the build setup. In case you run into any other issues please let us know. I'll close this issue, please feel free to reopen in case there are more problems.
