### ISSUE TITLE
Improve Coverage Report

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1399]
During the end summary, a list of the assertions and locations should be displayed to the user.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: could you please implement this feature?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: could you please implement this feature?

Yes

**Comment by lucasccordeiro** [comment]
Thank you.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0 : shall we close this issue via https://github.com/esbmc/esbmc/pull/1337?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0 : shall we close this issue via #1337?

Yes.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1337.
