### ISSUE TITLE
A false positive result?

### ISSUE THREAD

**Issue by Anthonysdu** [esbmc/esbmc#1401]
Different result for this program
```
#include <assert.h>
int main() {
    int granules[10] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100};
    unsigned long int offset = (&granules[0] + 6) - &granules[0];
    assert(offset < 8);
    return 0;
}
```

esbmc master: 
```
State 1 file main.c line 4 column 5 function main thread 0
----------------------------------------------------
  offset = (unsigned long int)((&granules[0] + 6) - &granules[0])

State 2 file main.c line 5 column 5 function main thread 0
----------------------------------------------------
Violated property:
  file main.c line 5 column 5 function main
  assertion offset < 8
  offset < 8


VERIFICATION FAILED
```
cbmc:
```
** Results:
main.c function main
[main.assertion.1] line 5 assertion offset < 8: SUCCESS
```

**Comment by fbrausse** [comment]
Indeed, putting
```c
    int n = offset;
    assert(n < 8);
```
reveals
```
State 2 file gh-1401.c line 5 column 5 function main thread 0
----------------------------------------------------
  n = 24 (00000000 00000000 00000000 00011000)
```

**Comment by lucasccordeiro** [comment]
@fbrausse: Can I ask you whether you could check this issue?

**Comment by fbrausse** [comment]
@lucasccordeiro Yup, will do. @Anthonysdu if it's urgent, please let me know, otherwise it might take a bit until I get to this.

**Comment by Anthonysdu** [comment]
Yes it's very urgent :) feel free if I can assist you

**Comment by fbrausse** [comment]
@Anthonysdu The issue seems to be here: https://github.com/esbmc/esbmc/blob/689902eb4a602257ba816cbbe7c14ef2dd7b6c68/src/solvers/smt/smt_memspace.cpp#L124

`the_ptr_offs` is in bytes (as produced by the pointer_offset2t expressions above), but it should be divided *evenly* by the (byte-)size of the operand's types (which should be equal). How the "evenly" can be asserted I don't know right now. But the division by the byte-size should be easy to do.

**Comment by fbrausse** [comment]
> How the "evenly" can be asserted I don't know right now.

This should be asserted elsewhere, in particular the pointer must be aligned to the pointed-to type's alignment. This is actually related to #1220 where exactly that condition is also assumed. That issue provides an example where it doesn't hold and we fail to detect it. To me this looks like a check that should be performed whenever a pointer-typed expression is being created through type- or bitcasts.
