### ISSUE TITLE
Problem testing Openssl library 

### ISSUE THREAD

**Issue by fatimahkj** [esbmc/esbmc#141]
Hi, 
I tried to test the OpenSSL library with ESBMC. I chose one c file to test a specific function. However, I got an error of file not found even when I include the path of this header file, as shown in the attached picture. Also, I tried to combine all the file using -E. It didn't work. 
Please do you have any idea of how to solve it?

![Screenshot from 2020-02-17 11-23-20](https://user-images.githubusercontent.com/47563480/74650593-f6b26300-5179-11ea-931a-2b3792ef644e.png)

Many thanks,

**Comment by fatimahkj** [comment]
I solved the problem. 

Thanks any way

**Comment by mikhailramalho** [comment]
No problems, feel free to ask any question.
