### ISSUE TITLE
Inductive step can't handle infinite goto loops

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1411]
The pattern:

```c
int my_assume(int n)
{
_EXIT: goto _EXIT;
}

int main() {
        int c = __VERIFIER_nondet_int();
        if(!c) my_assume(c);

        for(int i = 0; i < 5; i++);

        __ESBMC_assert(0, "");
}
```

Inductive step says that this program is true (` ./src/esbmc/esbmc   --unwind 3  check.c --inductive-step`). This is an issue as it causes wrong true veredicts.

As a sidenote,  replacing the goto loop to a while 1 (or an assume 0) solves the issue.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1412.
