### ISSUE TITLE
ESBMC crashes on symbolic unions

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1426]
By changing the regression `esbmc/github_732-2-2` to have nondet functions:

```c
typedef union {
  int x[12000];
} t1;

typedef struct {
  int x;
  t1 y;
} t2;

t2 nondet_t2();

int main()
{
  t2 a = nondet_t2();
  int *b = &a.x;
  b[1] = a.x;
  assert(*b);
}
```

Causes esbmc to fail with: `esbmc/src/util/c_expr2string.cpp:1200: virtual std::string c_expr2stringt::convert_union(const exprt&, unsigned int&): Assertion !init.empty()' failed. Aborted`

**Comment by lucasccordeiro** [comment]
@fbrausse: Can I ask you whether you could check this issue?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/1427.
