### ISSUE TITLE
Fetching array elements inside tuples currently unimplemented 

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#143]
A problem when checking program loops/s3 using boolector from test-comp. The file attached contains the information about the execution.
[esbmc-output.txt](https://github.com/esbmc/esbmc/files/4222113/esbmc-output.txt)

Is this an ESBMC or Boolector problem?

**Comment by mikhailramalho** [comment]
This is a limitation of our SMT backend.

It shouldn't mess with the cex though, it will just be slightly incomplete.

**Comment by lucasccordeiro** [comment]
Reduced program that exposes the problem:

```C
#include <pthread.h>
typedef struct {
  int a[20];
  int b;
  int amount
} c;
c d;
e(c *f, g) {
  f->a[f->b] = g;
  f->amount++;
  if (f->b)
    ;
}
k(f) {
  int i;
  e(&d, i);
}
main() {
  pthread_t j;
  pthread_create(j, NULL, k, &d);
}
```

**Comment by lucasccordeiro** [comment]
Here are some regression tests that are failing:

```
01_pthread62
01_pthread60
github_148_fail
33_s3_srvr_blast_04
```

**Comment by lucasccordeiro** [comment]
First attempt to solve this issue: https://github.com/esbmc/esbmc/pull/362

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/commit/94b1ae7d9b076d7928cc6a936e7a8decc2288876.
