### ISSUE TITLE
ESBMC missing an assertion failure with option --fixedbv

### ISSUE THREAD

**Issue by andrea1775** [esbmc/esbmc#1451]
Hi,
I just found that ESBMC misses the assertion failure for the following code if we pass option --fixedbv:
```
#include <assert.h>
extern void __VERIFIER_assume(int cond);
extern int __VERIFIER_nondet_int();

int main() {
  float x = __VERIFIER_nondet_int();
  __VERIFIER_assume(x < 111116288);
  assert(x < 0);
  return 0;
}
```
The output of the command `esbmc --fixedbv test.c` is:
ESBMC version 7.4.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing test.c
Converting
Generating GOTO Program
GOTO program creation time: 0.043s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Symex completed in: 0.000s (14 assignments)
Slicing time: 0.000s (removed 9 assignments)
Generated 1 VCC(s), 1 remaining after simplification (5 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector arithmetic
Encoding to solver time: 0.001s
Solving with solver Boolector 3.2.2
Runtime decision procedure: 0.000s
BMC program time: 0.001s

VERIFICATION SUCCESSFUL

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you please to check this issue?

**Comment by fbrausse** [comment]
@andrea1775 May I ask in what context you are using ESBMC's `--fixedbv` switch and what semantics you expect from it? With this switch ESBMC's default for `float` is set to a 16.16 fixed-format, where the (signed) integral part has 16 bits and the fractional part has 16 bits as well. For `double` you would get a 32.32 fixed-point format.

The constant in the assumption you're using is `0x69f8000` in hex, and, (implicitly) truncated to 16 integral bits that's `0x8000`, i.e., the smallest fixed-point number. So the assumption is equivalent to false or 0. After that, any assertion will hold, even `assert(0)`, so the assertion is not actually missed. When you reduce the constant to let's say 32767, then ESBMC will be able to find a counter-example. In that case I get:
```
[Counterexample]


State 1 file gh-1451-1.c line 6 column 3 function main thread 0
----------------------------------------------------
  x = 16127f (00111110 11111111 00000000 00000000)

State 3 file gh-1451-1.c line 8 column 3 function main thread 0
----------------------------------------------------
Violated property:
  file gh-1451-1.c line 8 column 3 function main
  assertion x < 0
  x < 0f


VERIFICATION FAILED
```

**Comment by andrea1775** [comment]
Ok thanks for the reply. Now it makes sense. I didn't know that ESBMC would just prune the leading bits with that option.
