### ISSUE TITLE
ESBMC for FreeRTOS - error--data-races-check

### ISSUE THREAD

**Issue by BryanOlmos91** [esbmc/esbmc#1498]
Hi all, 

I am trying to detect race conditions for FreeRTOS.  I can compile the code with ESBMC version 7.0.0 64-bit x86_64 Linux.
The code that I am trying to verify is located at: https://github.com/Infineon/mtb-example-hal-posix-freertos.
I received this error, when I add the option --data-races-check: :

![data-races-check-error-message](https://github.com/esbmc/esbmc/assets/151013997/e8c7c2dc-1cd8-47fa-b92c-88516fc7e459)

Is ESBMC able to check C code for FreeRTOS? Do you have any previous experience with data race detection for FreeRTOS?

This is the executed command:
 
esbmc source/main.c source/posix_demo.c ../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers/source/cy_syspm.c bsps/TARGET_APP_CY8CEVAL-062S2/cybsp.c ../mtb_shared/mtb-hal-cat1/release-v2.5.4/source/cyhal_hwmgr.c ../mtb_shared/mtb-hal-cat1/release-v2.5.4/source/cyhal_syspm.c -DCOMPONENT_APP_CY8CEVAL_062S2 -DCOMPONENT_CAT1 -DCOMPONENT_CAT1A -DCOMPONENT_CM0P_SLEEP -DCOMPONENT_CM4 -DCOMPONENT_CM4_0 -DCOMPONENT_Debug -DCOMPONENT_FREERTOS -DCOMPONENT_GCC_ARM -DCOMPONENT_MW_ABSTRACTION_RTOS -DCOMPONENT_MW_CAT1CM0P -DCOMPONENT_MW_CLIB_SUPPORT -DCOMPONENT_MW_CMSIS -DCOMPONENT_MW_CORE_LIB -DCOMPONENT_MW_CORE_MAKE -DCOMPONENT_MW_FREERTOS -DCOMPONENT_MW_FREERTOS_POSIX -DCOMPONENT_MW_MTB_HAL_CAT1 -DCOMPONENT_MW_MTB_PDL_CAT1 -DCOMPONENT_MW_RECIPE_MAKE_CAT1A -DCOMPONENT_MW_RETARGET_IO -DCOMPONENT_PSOC6_02 -DCOMPONENT_SOFTFP -DCORE_NAME_CM4_0=1 -DCY8C624ABZI_S2D44 -DCY_APPNAME_mtb_example_hal_posix_freertos -DCY_RETARGET_IO_CONVERT_LF_TO_CRLF -DCY_SUPPORTS_DEVICE_VALIDATION -DCY_TARGET_BOARD=APP_CY8CEVAL_062S2 -DCY_USING_HAL -DDEBUG -DTARGET_APP_CY8CEVAL_062S2 -I./include -Ibsps/TARGET_APP_CY8CEVAL-062S2 -Ibsps -I. -Ibsps/TARGET_APP_CY8CEVAL-062S2/config/GeneratedSource -Ibsps/TARGET_APP_CY8CEVAL-062S2/config -Iinclude -I../mtb_shared/freertos-posix/release-v1.0.0/include/private -I../mtb_shared/freertos-posix/release-v1.0.0/include -I../mtb_shared/freertos-posix/release-v1.0.0 -I../mtb_shared/freertos-posix/release-v1.0.0/source -I../mtb_shared/freertos-posix/release-v1.0.0/source/portable -I../mtb_shared/freertos-posix/release-v1.0.0/source/portable/infineon/psoc -I../mtb_shared/freertos-posix/release-v1.0.0/source/portable/infineon -I../mtb_shared/retarget-io/release-v1.5.0 -I../mtb_shared/abstraction-rtos/release-v1.7.4/include -I../mtb_shared/abstraction-rtos/release-v1.7.4 -I../mtb_shared/abstraction-rtos/release-v1.7.4/include/COMPONENT_FREERTOS -I../mtb_shared/cat1cm0p/release-v1.3.0/COMPONENT_CAT1A -I../mtb_shared/cat1cm0p/release-v1.3.0 -I../mtb_shared/clib-support/release-v1.4.2 -I../mtb_shared/clib-support/release-v1.4.2/TOOLCHAIN_GCC_ARM -I../mtb_shared/cmsis/release-v5.8.0/Core/Include -I../mtb_shared/cmsis/release-v5.8.0/Core -I../mtb_shared/cmsis/release-v5.8.0 -I../mtb_shared/core-lib/release-v1.4.1/include -I../mtb_shared/core-lib/release-v1.4.1 -I../mtb_shared/freertos/release-v10.5.0/Source/include -I../mtb_shared/freertos/release-v10.5.0/Source -I../mtb_shared/freertos/release-v10.5.0 -I../mtb_shared/freertos/release-v10.5.0/Source/portable/COMPONENT_CM4 -I../mtb_shared/freertos/release-v10.5.0/Source/portable -I../mtb_shared/freertos/release-v10.5.0/Source/portable/COMPONENT_CM4/TOOLCHAIN_GCC_ARM -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/COMPONENT_CAT1A/include/pin_packages -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/COMPONENT_CAT1A/include -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/COMPONENT_CAT1A -I../mtb_shared/mtb-hal-cat1/release-v2.5.4 -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/COMPONENT_CAT1A/include/triggers -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/include -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/include_pvt -I../mtb_shared/mtb-hal-cat1/release-v2.5.4/source -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/devices/COMPONENT_CAT1A/include -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/devices/COMPONENT_CAT1A -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/devices -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0 -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/devices/COMPONENT_CAT1A/include/ip -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers/include -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers/third_party/ethernet/include -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers/third_party/ethernet -I../mtb_shared/mtb-pdl-cat1/release-v3.8.0/drivers/third_party -Dwint_t="unsigned int" --unwind 5 --no-unwinding-assertions --data-races-check

If I remove the option --data-races-check, the result is: 

![ok-message](https://github.com/esbmc/esbmc/assets/151013997/13ed46ee-6691-4af7-90a4-81daa8a93a90)

If you want to try this example you can use the tool: ModusToolbox ( https://www.infineon.com/cms/en/design-support/tools/sdk/modustoolbox-software/ ). It will give access to all the libraries.

**Comment by lucasccordeiro** [comment]
Dear @BryanOlmos91,

We're just in the process of improving our data-race check further. So, your question comes at a perfect moment for us to help us refine our implementation.

@XLiZHI: could you please check this issue?

In the past, we had some colleagues applying ESBMC to verify RTOS; ESBMC has succeeded in finding bugs later confirmed by developers. I can get the names of those colleagues if that helps you.

**Comment by XLiZHI** [comment]
Hi, @BryanOlmos91,

Thank you for opening this issue.

I notice you're using version 7.0.0. Would you mind trying to use option `--show-goto-value-sets` and remove `--data-races-check`? If you get the same error message, I think the problem is in the **static analysis**, not the data race check.

**Comment by BryanOlmos91** [comment]
Hi @XLiZHI, 

Exactly, I added --show-goto-values-sets and I got the same error: 

![image](https://github.com/esbmc/esbmc/assets/151013997/43dbcb8c-c2c0-40f8-b7e4-0803d51fb6d4)

If you need me to execute more commands, please let me know.

**Comment by XLiZHI** [comment]
Hi @BryanOlmos91 ,

Many thanks, I think we understand the problem.

**Comment by lucasccordeiro** [comment]
@BryanOlmos91: Can I ask you to use our latest release, available at https://github.com/esbmc/esbmc/releases?

Also, if you could send us the reduced program that caused the crash, that would be wonderful. You can follow the instructions in our Wiki to produce this reduced C program: https://github.com/esbmc/esbmc/wiki/Reducing-C-Programs

**Comment by BryanOlmos91** [comment]
Hi @lucasccordeiro ,

I used the last release and I received the same error. Please find attached the original main.i and the reduced main.i. Many thanks for your support.

[creduce_freertos.zip](https://github.com/esbmc/esbmc/files/13414936/creduce_freertos.zip)

**Comment by lucasccordeiro** [comment]
Many thanks, @BryanOlmos91.

We will debug this crash in ESBMC and get back to you soon.

**Comment by lucasccordeiro** [comment]
BTW, here is the reduced C program produced by @BryanOlmos91:

````C
typedef struct {
  int a
} b;
c() { ((b *)60000)->a = 0; }
main();
````

**Comment by XLiZHI** [comment]
After my initial investigation, I think the problem is not only with **static analysis**, but also with **symbolic execution**.

I did some debugging in `symex_assign` and found that we couldn't dereference `((b *)60000)->a`, giving us an incorrect result: `symex::invalid_object0`.

cmd: `esbmc main.c`
```
typedef struct {
  int a;
} b;

int main()
{
  ((b *)60000)->a = 0;
  assert(((b *)60000)->a == 0);
}
```
result: 
```
[Counterexample]


State 3 file main3.c line 8 column 3 function main thread 0
----------------------------------------------------
Violated property:
  file main3.c line 8 column 3 function main
  assertion
  ( struct __anon_typedef_b_at_main3_c__1_9 *)60000->a == 0


VERIFICATION FAILED
```
This means that the assignment was not successful.

To sum up, I think we should focus on two issues:

1. Can we handle the "directly access and modify memory" case? 
2. Is this safe?

**Comment by lucasccordeiro** [comment]
@XLiZHI: You can check @shmarovfedor's talk from our workshop (https://www.linkedin.com/posts/lucas-cordeiro-3156233_workshop-on-automated-software-verification-activity-7132467558468755456-I2w3?utm_source=share&utm_medium=member_desktop :-).

ESBMC will create a symbol to represent this address in our memory model. In this particular example, ESBMC produces the correct result here, i.e., this type of access is invalid. Attempting to access or modify memory at an arbitrary address can result in various issues (e.g., segmentation faults, crashes, or unexpected program behavior).

This reduced C program doesn't exhibit the original crash in ESBMC.

**Comment by BryanOlmos91** [comment]
Hi @lucasccordeiro ,

Thank you for your support with this issue. In the meanwhile, please can you give me the names of the colleagues who applied ESBMC to verify RTOS or the repository of the projects, in case they are available. I am curious to know what kind of applications they verified.

**Comment by lucasccordeiro** [comment]
Yes, sure.

Here is the LinkedIn profile of the colleague who managed to find real bugs with ESBMC in the unikraft scheduler.

https://www.linkedin.com/in/fareed-arif-a0782a199/.

You can check further information about the bug https://github.com/unikraft/unikraft/issues/381 and the fix https://github.com/unikraft/unikraft/pull/380.

You can also check this animation about the bug:

![uksched-bug-esbmc-demo](https://github.com/esbmc/esbmc/assets/3694109/29cd6f96-b752-4196-9abd-353ecf6bccf6)

**Comment by lucasccordeiro** [comment]
BTW, I have just learned that it is a conventional OS (and not an RTOS): https://unikraft.org/docs/internals/architecture

**Comment by lucasccordeiro** [comment]
@BryanOlmos91: @XLiZHI has fixed the issue in https://github.com/esbmc/esbmc/pull/1514.

I'll close this PR via https://github.com/esbmc/esbmc/pull/1514; if you still find issues in ESBMC, please let us know.

Many thanks for this report.
