### ISSUE TITLE
How Mutex works in ESBMC?

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1524]
Hi everyone,

I've recently been learning how mutex is modeled in ESBMC and how does it work.

https://github.com/esbmc/esbmc/blob/b53d9a8035d06dee3acc732211cefb19d4b5cb12/src/c2goto/headers/pthread.h#L44-L49

https://github.com/esbmc/esbmc/blob/b53d9a8035d06dee3acc732211cefb19d4b5cb12/src/c2goto/library/pthread_lib.c#L318-L327

`#define __ESBMC_mutex_lock_field(a) ((a).__lock)`

My understanding is that `__lock` is set to 1 when the lock is in effect, I speculated that it might be changing the **guard** to implement the lock function, but I couldn't find the exact location of that code. Could you please give me some explanation?

**Comment by lucasccordeiro** [comment]
@XLiZHI : You can check this paper https://ssvlab.github.io/lucasccordeiro/papers/icse2011.pdf. You could also read Section 4.5.1 ModellingMutexLockingOperations (https://ssvlab.github.io/lucasccordeiro/papers/phd_thesis_cordeiro.pdf).

You can check the source code at https://github.com/esbmc/esbmc/blob/master/src/c2goto/library/pthread_lib.c.

**Comment by lucasccordeiro** [comment]
Thanks, @XLiZHI.
