### ISSUE TITLE
string_constant.cpp fails to build on macOS M1

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1570]
The build fails with:

```
FAILED: src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -I/Users/user/Repos/esbmc/src -I/Users/user/Repos/esbmc/build/src -I/Users/user/Repos/esbmc/src/util -I/Users/user/Repos/esbmc/build/_deps/fmt-src/include -isystem /opt/homebrew/include -g -std=gnu++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.6 -fPIC -Winvalid-pch -Xarch_arm64 -include/Users/user/Repos/esbmc/build/src/util/CMakeFiles/util_esbmc.dir/cmake_pch_arm64.hxx -MD -MT src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o -MF src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o.d -o src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o -c /Users/user/Repos/esbmc/src/util/string_constant.cpp
/Users/user/Repos/esbmc/src/util/string_constant.cpp:137:23: error: use of undeclared identifier 'c16rtomb'
           : w == 2 ? c16rtomb(buf, c, &ps)
                      ^
/Users/user/Repos/esbmc/src/util/string_constant.cpp:138:23: error: use of undeclared identifier 'c32rtomb'
                    : c32rtomb(buf, c, &ps);
```

It seems that it is not mandatory for systems to implement these identifiers. @fbrausse do you have any sugestions?

**Comment by fbrausse** [comment]
Does `std::c32rtomb` work? cppreference [claims](https://en.cppreference.com/w/cpp/string/multibyte/c32rtomb) it is part of the language since C++11.

**Comment by rafaelsamenezes** [comment]
Hm, it is "defined":

```
string_constant.cpp.o -c /Users/user/Repos/esbmc/src/util/string_constant.cpp
/Users/user/Repos/esbmc/src/util/string_constant.cpp:137:23: error: reference to unresolved using declaration
      : w == 2 ? std::c16rtomb(buf, c, &ps)
                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/cuchar:68:1: note: using declaration annotated with 'using_if_exists' here
using ::c16rtomb _LIBCPP_USING_IF_EXISTS;
^
/Users/user/Repos/esbmc/src/util/string_constant.cpp:137:18: error: excess elements in scalar initializer
      : w == 2 ? std::c16rtomb(buf, c, &ps)
                 ^                ~~~~~~~~
/Users/user/Repos/esbmc/src/util/string_constant.cpp:138:14: error: reference to unresolved using declaration
      : std::c32rtomb(buf, c, &ps);
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/cuchar:70:1: note: using declaration annotated with 'using_if_exists' here
using ::c32rtomb _LIBCPP_USING_IF_EXISTS;
^
/Users/user/Repos/esbmc/src/util/string_constant.cpp:138:9: error: excess elements in scalar initializer
      : std::c32rtomb(buf, c, &ps);
        ^                ~~~~~~~~
```

**Comment by fbrausse** [comment]
Lovely, the only related info I can find on the interwebs is https://github.com/root-project/root/issues/12762 and <https://github.com/llvm/llvm-project/issues/62573>. Seems like Apple's headers are broken. As the only usage of this functionality is kind-of optional, I guess a CMake check whether these functions exist/are usable would be required.

**Comment by fbrausse** [comment]
@rafaelsamenezes Is there a default encoding used on macOS for narrow (`char *`) strings and wide (`wchar_t *`) strings? If it is known to always be UTF-8/UTF-16/UTF-32 maybe we can work around the missing functions.

**Comment by rafaelsamenezes** [comment]
> Is there a default encoding used on macOS for narrow (char *) strings and wide (wchar_t *) strings?

I don't know. Is there a magic way of finding out or... google?

> As the only usage of this functionality is kind-of optional, I guess a CMake check whether these functions exist/are usable would be required.

At this point we can restrict for every apple system.

**Comment by fbrausse** [comment]
> I don't know. Is there a magic way of finding out or... google?

My google-fu is not enough to find out. But if you could save a text file containing some non-ASCII characters copy-pasted into it from a browser (which should put the native charset into the clipboard), pack it into an archive and upload it, we can find out.

> At this point we can restrict for every apple system.

Right, "restrict" as in "unsupported garbage" if the defaults are wrong. In case we can't find out the defaults, I guess guarding the entire convert_* with `#if !(__APPLE__ && __MACH__)` and returning `value()` otherwise would make it compile again.

**Comment by rafaelsamenezes** [comment]
> save a text file containing some non-ASCII characters copy-pasted into it from a browser (which should put the native charset into the clipboard), pack it into an archive and upload it, we can find out.

I constructed the [file.zip](https://github.com/esbmc/esbmc/files/13820003/file.zip) with

```
&&&
á é í ó ú
```

**Comment by fbrausse** [comment]
> I constructed the [file.zip](https://github.com/esbmc/esbmc/files/13820003/file.zip) with

Ack, so this file is UTF-8. To my knowledge `wchar_t` on macOS is 4 bytes wide, so assuming UTF-32 for that seems reasonable. That means we can re-use wcrtomb() for c32rtomb() and for the 16-bit version we'll have to hand-code a translation. OK, that's fine, I can work with that. Thanks @rafaelsamenezes.
