### ISSUE TITLE
Inconsistent results from pointer comparison

### ISSUE THREAD

**Issue by Anthonysdu** [esbmc/esbmc#1597]
```
#include <assert.h>
extern struct str nondet_struct();
struct str {
  int a;
};
struct str arr[8];

int main() {
  struct str str1 = nondet_struct();
  arr[0] = *(&str1);
  struct str *str2 = &arr[0];
  if ((unsigned long)str2 >= (unsigned long)(-4095))
    assert((unsigned int)(-1 * (long)str2) < 6);
}
```
`esbmc --no-pointer-check`
```
State 1 file main.c line 13 column 5 function main thread 0
----------------------------------------------------
Violated property:
  file main.c line 13 column 5 function main
  assertion (unsigned int)(-1 * (long)str2) < 6
  (unsigned int)((signed long int)(-1) * (signed long int)str2) < 6


VERIFICATION FAILED
```
cbmc: success

**Comment by Anthonysdu** [comment]
A compiled one:

```
#include <assert.h>

struct str {
  int a;
};

struct str nondet_struct(){
  struct str s;
  s.a = 1;
  return s;
}


struct str arr[8];

int main() {
  struct str str1 = nondet_struct();
  arr[0] = *(&str1);
  struct str *str2 = &arr[0];
  if ((unsigned long)str2 >= (unsigned long)(-4095))
    assert((unsigned int)(-1 * (long)str2) < 6);
}
```

Run:
```
#!/bin/bash

for ((i=1; i<=100000; i++))
do
    ./a.out
done
```
No assertion faliure reported.

**Comment by fbrausse** [comment]
What is the inconsistency?

Note that CBMC does not model the full 64 bits of pointers. In case `(long)str2` is negative, -2048 for instance, the assertion would be violated. For instance, the Linux kernel's data is sitting on the negative half of the address space. C itself gives no guarantees.

**Comment by Anthonysdu** [comment]
> What is the inconsistency?
> 
> Note that CBMC does not model the full 64 bits of pointers. In case `(long)str2` is negative, -2048 for instance, the assertion would be violated. For instance, the Linux kernel's data is sitting on the negative half of the address space. C itself gives no guarantees.

Thanks for the explanation!
