### ISSUE TITLE
Integration with OSS-Fuzz

### ISSUE THREAD

**Issue by pmatos** [esbmc/esbmc#160]
You guys should attempt an integration of ESBMC with OSS-Fuzz. It would certainly improve ESBMC stability over time and it should be relatively simple due to the amount of other (already integrated tools) consuming C coded as a fuzzed input.

Ref: https://github.com/google/oss-fuzz

**Comment by pmatos** [comment]
Also: https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/

**Comment by thefischsun** [comment]
Hi -

may be an idea, but the doc says they cut jobs that run longer than 25 secs.

-- fisch

**Comment by pmatos** [comment]
Right - I missed that bit. I understand 25secs might be an issue with esbmc.
The whole point was trying to get esbmc more reliable. I remember trying to use it last year but it fell apart quite quickly on fuzzed C input. I attempted it locally though, not through OSS-Fuzz.

**Comment by pmatos** [comment]
@thefischsun i went back to an experiment I did last summer.
Get CSmith and run (paths set appropriatelly):
```
while true; do csmith/bin/csmith > foo.c; release/bin/esbmc --64 -I/root/csmith/include/csmith-2.4.0/ --k-induction foo.c; if [[ "$?" > 1 ]]; then break; fi; done
```

It takes less than 30secs to find a crash like #162 .
Maybe it would be great, if not fuzzing with OSS-Fuzz to integrate maybe 600secs of this loop into the esbmc CI process.

**Comment by rafaelsamenezes** [comment]
> Maybe it would be great, if not fuzzing with OSS-Fuzz to integrate maybe 600secs of this loop into the esbmc CI process.

I think that this should be simple enough.

1. Integrate the csmith command into CMake as a test
2. Add it into the CI

This should be very useful to us when obtaining coverage reports from our tests
