### ISSUE TITLE
A few notes on the README

### ISSUE THREAD

**Issue by pmatos** [esbmc/esbmc#161]
Hi,

So I tried compiling following the readme. It's pretty good - thanks.

You are missing a few dependencies that might not be dependencies of esbmc but are deps of the build process. Namely:

* wget
* git
* g++
* unzip

You'll see these problems if you follow the readme using a docker image of ubuntu or similar.

**Comment by lucasccordeiro** [comment]
@ericksonalves: could you please submit a PR to fix this issue?

**Comment by rafaelsamenezes** [comment]
@ericksonalves could you check if `build-essential` contains the referred packages?
