### ISSUE TITLE
Duplicate node IDs in GraphML violation witness

### ISSUE THREAD

**Issue by Po-Chun-Chien** [esbmc/esbmc#1621]
The violation witnesses in GraphML format generated by ESBMC may contain duplicate node IDs.

Here's an example [witness](https://github.com/esbmc/esbmc/files/14028514/witness.graphml.zip) obtained by verifying [`szymanski.4.prop1-func-interl.c`](https://gitlab.com/sosy-lab/research/data/word-level-hwmc-benchmarks/-/blob/02bb055de5016fac23431567e23b87e1ab646937/bv/c-lazyMod/beem/szymanski.4.prop1-func-interl.c) with property [`unreach-call.prp`](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/properties/unreach-call.prp)
using ESBMC 7.4.0 (downloaded from the SV-COMP 2024 [archive](https://doi.org/10.5281/zenodo.10198805)).
It can be reproduced with the following command:

```bash
./esbmc-wrapper.py -p unreach-call.prp -s incr --arch 64 szymanski.4.prop1-func-interl.c
```

The witness contains 3 nodes with ID "N0" at lines 50, 393262, and 786478.
This is likely caused by an integer overflow, as shown by the following snippet (line 196648 of the attached witness).

```xml
    <node id="N32767"/>
    <edge id="E32766" source="N32766" target="N32767">
      <data key="startline">4317</data>
      <data key="assumption">var_1456_arg_0 = 0;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N-32768"/>
    <edge id="E32767" source="N32767" target="N-32768">
      <data key="startline">4318</data>
      <data key="assumption">var_1456_arg_1 = 1;</data>
      <data key="threadId">0</data>
    </edge>
```

**Comment by lucasccordeiro** [comment]
Hi @Po-Chun-Chien,

Thanks very much for this report.

Can I ask you whether you would need this fix for some evaluations / upcoming papers?

I ask this question because we'll dedicate effort to our witness generation later this year to support the new format.

**Comment by Po-Chun-Chien** [comment]
> Hi @Po-Chun-Chien,
> 
> Thanks very much for this report.
> 
> Can I ask you whether you would need this fix for some evaluations / upcoming papers?
> 
> I ask this question because we'll dedicate effort to our witness generation later this year to support the new format.

We discovered this issue when evaluating our validator [Btor2-Val](https://gitlab.com/sosy-lab/software/btor2-val) for Btor2 circuits.
Initially, we tried to sort the nodes in topological order.
The duplicate node IDs would form a loop in the graph and make sorting fail.
Now we simply read the nodes in the order they are written in the witness file as a workaround.
So a fix for this issue is not urgent for us.

**Comment by lucasccordeiro** [comment]
Thanks, @Po-Chun-Chien.

Our colleague @ChenfengWei0 will take a look at this issue.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0 : This might be the root cause of this issue: 

https://github.com/esbmc/esbmc/blob/master/src/goto-symex/witnesses.cpp#L14

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: Here is the command-line to reproduce the bug:

````
$ time esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps --no-vla-size-check szymanski.4.prop1-func-interl.c --64 --witness-output witness.graphml --enable-unreachability-intrinsic --no-pointer-check --interval-analysis --no-bounds-check --error
-label ERROR --goto-unwind --unlimited-goto-unwind --k-induction --max-inductive-step 3
````

**Comment by lucasccordeiro** [comment]
@Po-Chun-Chien: we have just fixed this overflow issue. Please let us know if you find further inconsistencies with our wireless generation.

Many thanks,
Lucas
