### ISSUE TITLE
Generate macos release

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#164]
## Summary

We can use Actions to generate the macos release automatically containing Z3 and Boolector.

## Tasks

- Add the static build release using cpack in the [release action](https://github.com/esbmc/esbmc/blob/master/.github/workflows/release.yml). You can use the ubuntu version as a guide together with the [build action](https://github.com/esbmc/esbmc/blob/master/.github/workflows/build.yml)

**Comment by rafaelsamenezes** [comment]
Closed via: https://github.com/esbmc/esbmc/commit/00d3f8797778598ac645b8369c4b1442f692f1d0

The CI now:

- Generates a darwin release.
- Uses Release mode when compiling.

**Comment by mikhailramalho** [comment]
Release or RelWithDebInfo?

A think the default is the latter on Linux.

**Comment by rafaelsamenezes** [comment]
I added `-DCMAKE_BUILD_TYPE=Release` to both

**Comment by mikhailramalho** [comment]
Could you please change it to RelWithDebInfo?

The binary will be bigger but we'll get better bug reports, e.g., issue #162:

Release:
```
$ esbmc --64 -I/root/csmith/include/csmith-2.4.0/ --k-induction foo.c
Converting
Generating GOTO Program
GOTO program creation time: 1.516s
GOTO program processing time: 0.044s

*** Iteration number 1 ***
*** Checking base case
Starting Bounded Model Checking
Not unwinding loop 11 iteration 1 file string.c line 96 function strcmp
Not unwinding loop 25 iteration 1 file csmith.h line 59 function crc32_gentab
Segmentation fault (core dumped)
```

RelWithDebInfo:
```
$ esbmc foo.c --incremental-bmc
Converting
Generating GOTO Program
GOTO program creation time: 4.421s
GOTO program processing time: 0.161s

*** Iteration number 1 ***
*** Checking base case
Starting Bounded Model Checking
Not unwinding loop 11 iteration 1 file string.c line 96 function strcmp
Not unwinding loop 25 iteration 1 file csmith.h line 59 function crc32_gentab
esbmc: ../src/pointer-analysis/dereference.cpp:1733: expr2tc* dereferencet::extract_bytes_from_scalar(const expr2tc&, unsigned int, const expr2tc&): Assertion `num_bytes != 0' failed.
Aborted (core dumped)
```
