### ISSUE TITLE
testllvm.desc regression files

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1658]
Why they exist? Can we just remove it? They are currently not checked and they also differ from the test.desc file

**Comment by fbrausse** [comment]
> Why they exist? Can we just remove it?

No idea. `git blame` says they're older. I vote to remove them.

*Edit:* Could be that those files have been created when moving from the old to the new frontend.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could please submit a PR to remove them?
