### ISSUE TITLE
Failed to determine path to Clang headers on openSUSE

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#1661]
Configuring ESBMC on openSUSE Tumbleweed causes ESBMC to fail with `Failed to determine path to Clang headers: not a directory: /usr/lib64/clang/17.0.6/include`. The correct path is `/usr/lib64/clang/17/include` and using ` -DOVERRIDE_CLANG_HEADER_DIR=<path>` does not help.

I also noticed the same issue in macOS. Currently, I do a symbolic link as a workaround.

**Comment by fbrausse** [comment]
Is there a difference between the "not a directory" path and the correct one?

**Comment by rafaelsamenezes** [comment]
> Is there a difference between the "not a directory" path and the correct one?

Ooops my bad. I fixed the message: `/usr/lib64/clang/17/include` is the correct path

**Comment by fbrausse** [comment]
Weird, I thought I fixed this - but can't find it. Starting from Clang-16 they use only the major version:
```
$ ls /usr/lib/clang/ # on Gentoo it's in /usr/lib
11.1.0  12.0.0  12.0.1  13.0.0  13.0.1  14.0.4  14.0.6  15.0.3  15.0.4  15.0.6  15.0.7  16  17
```
