### ISSUE TITLE
[Security] Disabling security of curl _permanently_ when using `scripts/build.sh`

### ISSUE THREAD

**Issue by intrigus-lgtm** [esbmc/esbmc#1677]
This code here disables the security of curl **permanently** for the current user.
This is **unacceptable**.
https://github.com/esbmc/esbmc/blob/2d6cd6d0bd997bfafa0c28d7ff49904de22c75f5/scripts/build.sh#L91-L94

I also don't see why this is necessary. Boolector appears to only use `curl` twice and not in a way that needs this hack I'd say:
https://github.com/search?q=repo%3ABoolector%2Fboolector%20%22curl%22&type=code

**Comment by rafaelsamenezes** [comment]
> This code here disables the security of curl **permanently** for the current user. This is **unacceptable**.
> 
> https://github.com/esbmc/esbmc/blob/2d6cd6d0bd997bfafa0c28d7ff49904de22c75f5/scripts/build.sh#L91-L94
> 
> I also don't see why this is necessary. Boolector appears to only use `curl` twice and not in a way that needs this hack I'd say: https://github.com/search?q=repo%3ABoolector%2Fboolector%20%22curl%22&type=code

That script is used for CI purposes and indeed should not be run by a common user.  Here are the [building instructions](https://github.com/esbmc/esbmc/blob/master/BUILDING.md).

> I also don't see why this is necessary.

~It broke github actions. Feel free to open a PR.~

Just started some testing. Seems to be fine nowadays.

**Comment by intrigus-lgtm** [comment]
> That script is used for CI purposes and indeed should not be run by a common user. Here are the [building instructions](https://github.com/esbmc/esbmc/blob/master/BUILDING.md).

I did have a look at the building instructions, but something (don't know what anymore) broke.
As I've had to build quite a lot of different software for security research, I usually just check how the projects do CI and use that. Even for a CI script I would usually not expect it to weaken security.

E.g. I would assume that even on Ubuntu 22.04 openjdk-8-jre is not available anymore (On Debian 12 not even openjdk-11 which is used by scripts/build.sh is available):
https://github.com/esbmc/esbmc/blob/410a91981fc3cb70b536c73aeb077f0bd19a4ff4/BUILDING.md?plain=1#L35

But anyway, thanks for fixing the problem :)

**Comment by rafaelsamenezes** [comment]
> > That script is used for CI purposes and indeed should not be run by a common user. Here are the [building instructions](https://github.com/esbmc/esbmc/blob/master/BUILDING.md).
> 
> I did have a look at the building instructions, but something (don't know what anymore) broke.
> As I've had to build quite a lot of different software for security research, I usually just check how the projects do CI and use that. Even for a CI script I would usually not expect it to weaken security.
> 
> E.g. I would assume that even on Ubuntu 22.04 openjdk-8-jre is not available anymore (On Debian 12 not even openjdk-11 which is used by scripts/build.sh is available):
> https://github.com/esbmc/esbmc/blob/410a91981fc3cb70b536c73aeb077f0bd19a4ff4/BUILDING.md?plain=1#L35
> 
> But anyway, thanks for fixing the problem :)

If you find issues at the documentation. Please, report it or open a PR. I don't think any of the maintainers is running Ubuntu or Debian, so the documentation can get outdated.
