### ISSUE TITLE
Issue with clang_convert.cpp

### ISSUE THREAD

**Issue by JacobYiu** [esbmc/esbmc#1706]
![Screenshot 2024-02-22 104247](https://github.com/esbmc/esbmc/assets/52522679/2dccaad1-e478-41a4-a96d-82851008fcd3)

While working on a separate branch unrelated to clang_convert.cpp, I had encountered this bug and was wondering if it was the same for anyone else. This error only occurred because I had CHERI_CLANG installed on my laptop. 

For me to fix the bug, I just had to change the "." to "->"
![image](https://github.com/esbmc/esbmc/assets/52522679/b105c6c5-04e3-4503-9af0-5e9e01fbdd74)

**Comment by fbrausse** [comment]
Yes, you're right, thanks! It's due to an oversight in the recent change in #1674.
