### ISSUE TITLE
Update cmd line interface

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#173]
We currently use a custom cmd line parser, which is error-prone and very limited (see issue #166).

There are better alternatives out there: https://www.boost.org/doc/libs/1_71_0/doc/html/program_options.html

**Comment by rafaelsamenezes** [comment]
@mikhailramalho the best place to change this is [here](https://github.com/esbmc/esbmc/blob/master/src/esbmc/esbmc_parseoptions.cpp#L178) right?

Would this be enough?

Some extra information:

- Description of the options: https://github.com/esbmc/esbmc/blob/master/src/esbmc/options.cpp

**Comment by mikhailramalho** [comment]
This is where the options are set giving the cmd; it is one of the places it should be changed.

IMO, the easier way to cover everything is to get rid of the `util/cmdline` file/object and replace its features with the boost options.

**Comment by ahmedHashwa** [comment]
I suppose #433 fixed that issue.

**Comment by rafaelsamenezes** [comment]
@ahmedHashwa You are correct
