### ISSUE TITLE
Update our message output interface

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#174]
We currently have a custom message output interface, but we use iostream almost everywhere, which is bad for several reasons (global states, it is slow, not thread-safe, etc).

There are better alternatives out there: https://fmt.dev/latest/index.html

**Comment by lucasccordeiro** [comment]
@Mohannad-Aldughaim: May I ask you whether you could implement this issue?

**Comment by Mohannad-Aldughaim** [comment]
Got it. I'll implement it.

**Comment by mikhailramalho** [comment]
This should be a lot of work: there are 798 uses of cout/cerr in our code base.

I suggest you start by looking at the classes `message_handlert` and `ui_message_handlert`. These interfaces should be the base classes for all class that output messages. 

Fmt should be probably implemented in `message_handlert`.

This should also involve the XML dump we need for test-comp, @rafaelsamenezes

**Comment by rafaelsamenezes** [comment]
I am unsure if testcomp should be used with the message_handlert. IMO we should remove this XML handler from the code and add a options similar to witness generation.

Testcomp is not only an XML it is a set of files.

**Comment by Mohannad-Aldughaim** [comment]
I started implementing this issue. I made a testing project to test each print before i use it in the project and also to test it with cmake. Though i encountered some issues which I have questions about:

1- Should the usage of data types such as std::string changed to fmt::format or remain as they are?(fmt supports std::ostream by including <fmt/ostream.h>)

2- Should the library be included (#include <fmt/format.h>) in every file that uses cout/cerr or only in files with (#include <iostream>) ?

3- In fmt there are multiple print methods: print (which is formatted using fmt::format) printf( classic printf) fprintf and sprintf. Between print and printf, does it matter which one to use in terms of the reason cout/cerr is changed?

**Comment by Mohannad-Aldughaim** [comment]
@mikhailramalho may i ask you if you could answer these questions?

**Comment by mikhailramalho** [comment]
1. We should use the `messaget` interface, everything there is `std::string`. No need to use `ostream`.

2. It should only be included in `ui_message.cpp`, every status/debug/warning/error should go through the `messaget` interface.

3. What does the documentation says about these two methods? We should go with the one with less overhead.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/456.
