### ISSUE TITLE
Incompatible type for enum with large members

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [esbmc/esbmc#1758]
It seems like the data type used to model an enum is not considering its members. However, per ISO 9899's requirement for the enumeration type:

> Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, but shall be capable of representing the values of all the members of the enumeration.

Here're the command and example codes to trigger the issue. (ESBMC version: v7.5.0)

``` bash
# command
esbmc test_failure.c --function main --64 # VERIFICATION FAILED
esbmc test_success.c --function main --64 # VERIFICATION SUCCESSFUL
```

``` C
// test_failure.c
extern void reach_error(void);

#define VALUE_MSB1 0x8000000000000000

typedef enum {
    VALUE = VALUE_MSB1
} enum_t;

enum_t foo() {
    return VALUE;
}

int main() {
    if (!(foo() == VALUE_MSB1)) {
        reach_error();
    }
    return 0;
}
```

``` C
// test_success.c
#include <stdint.h>
extern void reach_error(void);

#define VALUE_MSB1 0x8000000000000000

uint64_t foo() {
    return VALUE_MSB1;
}

int main() {
    if (!(foo() == VALUE_MSB1)) {
        reach_error();
    }
    return 0;
}
```

**Comment by fbrausse** [comment]
Thanks, good observation. The problem is here: https://github.com/esbmc/esbmc/blob/bc564405dc961bfe2b9e4162c6dc29681f22db91/src/clang-c-frontend/clang_c_convert.cpp#L1071

enum_type() defaults to the same as `int` would. That's the problem. Ideally, we should get rid of enum_type(), because (at least with the current signature) it cannot perform its intended function.

**Comment by lucasccordeiro** [comment]
@XLiZHI : Can you please fix this issue on our C front-end?

**Comment by mikhailramalho** [comment]
doesn't clang provide the correct enum type? A getUnderlyingType() or similar?
