### ISSUE TITLE
False positive finding by ESBMC 7.5?

### ISSUE THREAD

**Issue by tihanyin** [esbmc/esbmc#1787]
Here is a very simple program:

```c
#include<limits.h>
#include<stdio.h>
int main(){
    unsigned int x;
    x = 2147483647 + 1;
    printf("The maximum for and unsigned is: %u\n", UINT_MAX);
    printf("The value of x is: %u\n", x);
}

```
The output is  `./test`:

```
The maximum for and unsigned is: 4294967295
The value of x is: 2147483648
```
Here we do not have an overflow (unsigned int maximum is 4294967295)

However ESBMC says using `--unsigned-overflow-check` that this program is vulnerable :
`esbmc test.c   --unsigned-overflow-check`

 ```c
----------------------------------------------------
Violated property:
  file test.c line 7 column 5 function main
  arithmetic overflow on add
  !overflow("+", 2147483647, 1)
```
Am I missing something here?

**Comment by lucasccordeiro** [comment]
A quick run here shows:

````
$ esbmc ov.c --unsigned-overflow-check
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing ov.c
Converting
Generating GOTO Program
GOTO program creation time: 0.484s
GOTO program processing time: 0.003s
Starting Bounded Model Checking
Symex completed in: 0.003s (19 assignments)
Slicing time: 0.000s (removed 11 assignments)
Generated 5 VCC(s), 5 remaining after simplification (8 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.2
Runtime decision procedure: 0.000s
BMC program time: 0.004s

VERIFICATION SUCCESSFUL
````

$esbmc --git

````
$ esbmc --git
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
ESBMC built from  ca8ff63950a9ce0f36b9b30f9bfce23f00082f24 2023-11-13 16:17:04.656235
````

Are you running ESBMC on a 64-bit machine?

**Comment by tihanyin** [comment]
> A quick run here shows:
> 
> ```
> $ esbmc ov.c --unsigned-overflow-check
> ESBMC version 7.5.0 64-bit x86_64 linux
> Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
> Parsing ov.c
> Converting
> Generating GOTO Program
> GOTO program creation time: 0.484s
> GOTO program processing time: 0.003s
> Starting Bounded Model Checking
> Symex completed in: 0.003s (19 assignments)
> Slicing time: 0.000s (removed 11 assignments)
> Generated 5 VCC(s), 5 remaining after simplification (8 assignments)
> No solver specified; defaulting to Boolector
> Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
> Encoding to solver time: 0.000s
> Solving with solver Boolector 3.2.2
> Runtime decision procedure: 0.000s
> BMC program time: 0.004s
> 
> VERIFICATION SUCCESSFUL
> ```
> 
> $esbmc --git
> 
> ```
> $ esbmc --git
> ESBMC version 7.5.0 64-bit x86_64 linux
> Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
> ESBMC built from  ca8ff63950a9ce0f36b9b30f9bfce23f00082f24 2023-11-13 16:17:04.656235
> ```
> 
> Are you running ESBMC on a 64-bit machine?

I posted a wrong code. So I corrected. 

```
#include<limits.h>
#include<stdio.h>
int main(){
    unsigned int x;
    x = 2147483647 + 1;
    printf("The maximum for and unsigned is: %u\n", UINT_MAX);
    printf("The value of x is: %u\n", x);
    
}
```

**Comment by maferrag** [comment]
How about the following example :

```
#include<limits.h>
#include<stdio.h>
 
#define A 2147483647
 
int main(){
    unsigned int x;
    x = A + 1;
    printf("The maximum for unsigned is: %u\n", UINT_MAX);
    printf("The value of x is: %u\n", x);
 
}
```

The output :

```
The maximum for unsigned is: 4294967295
The value of x is: 2147483648
```

The output of ESBMC:

```
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing content drive MyDrive BenchmarkLLM testlucas testlucas.c
content drive MyDrive BenchmarkLLM testlucas testlucas.c:10:11: warning: overflow in expression; result is -2147483648 with type 'int' [-Winteger-overflow]
x = A + 1;
^
Converting
Generating GOTO Program
GOTO program creation time: 0.631s
GOTO program processing time: 0.002s
Starting Bounded Model Checking
Symex completed in: 0.000s (19 assignments)
Slicing time: 0.000s (removed 11 assignments)
Generated 5 VCC(s), 5 remaining after simplification (8 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.3
Runtime decision procedure: 0.002s
Building error trace

State 3 file testlucas.c line 10 column 5 function main thread 0
Violated property:
file testlucas.c line 10 column 5 function main
arithmetic overflow on add
!overflow("+", 2147483647, 1)

VERIFICATION FAILED
```

This is a false positive...

**Comment by tihanyin** [comment]
Very interestingly gcc also say overflow warning.... 
test.c: In function ‘main’:
test.c:5:20: warning: integer overflow in expression of type ‘int’ results in ‘-2147483648’ [-Woverflow]
    5 |     x = 2147483647 + 1;
      |                    ^
But we have unsigned int here... For me it is very unusual outcome....
But of course the result is correct (and no overflow here):
```c
$ ./test
The maximum for and unsigned is: 4294967295
The value of x is: 2147483648
```

**Comment by tihanyin** [comment]
It seems that in C standard if we do not specify that the addition is unsigned int it will converted to int... Weird...
This does not give an overflow warning:
```c
#include <limits.h>
#include <stdio.h>

int main(){
    unsigned int x;
    x = 2147483647U + 1U;  // Use 'U' to indicate unsigned constants
    printf("The maximum for and unsigned is: %u\n", UINT_MAX);
    printf("The value of x is: %u\n", x);

    return 0;
}
```

**Comment by fbrausse** [comment]
Hi @tihanyin!
> `x = 2147483647 + 1;`
> Here we do not have an overflow (unsigned int maximum is 4294967295)

Yes, we do. Both operands of `+` are signed ints (by default, if there is no suffix *and* each literal value can be represented by a signed int - if it is too large, the type will be unsigned int) with the left operand being INT_MAX. And INT_MAX + 1 is an overflow.

You're right though, that it is *not* an unsigned overflow (the parameter you passed on the command line). ESBMC is implicitly assuming `--overflow-check` when you pass `--unsigned-overflow-check`. The reason being that signed overflows are undefined behaviour in C, while unsigned overflows are not. We added the unsigned-overflow-check basically as an extension to the already existing one.

The left-hand side `x` of the assignment does not matter for the computation of the right-hand side. Only as a last step, after the computation is done, is the result converted to the type of the left-hand side. Before that, it is still signed int.

> It seems that in C standard if we do not specify that the addition is unsigned int it will converted to int...

Yes, integer literals by default are signed. Also applies for suffixes `L` or `LL`. Unsigned needs to be said explicitly in C - with one exception: If the integer literal cannot be represented by the signed version, then the unsigned version of the type is silently chosen.

Note that for binary arithmetic operations it is enough for just one side to be unsigned in order for the whole operation to be unsigned, e.g. `INT_MAX + 1U` is not an overflow, because it is an addition on unsigned int.

Hi @maferrag!
> x = A + 1;
> arithmetic overflow on add
> This is a false positive...

It is not. :) You're asking to perform a signed addition of two signed ints. The mathematical result 2**31 cannot be represented (on this machine) by a signed int, so you get an overflow.

**Comment by tihanyin** [comment]
> Hi @tihanyin!
> 
> > `x = 2147483647 + 1;`
> > Here we do not have an overflow (unsigned int maximum is 4294967295)
> 
> Yes, we do. Both operands of `+` are signed ints (by default, if there is no suffix _and_ each literal value can be represented by a signed int - if it is too large, the type will be unsigned int) with the left operand being INT_MAX. And INT_MAX + 1 is an overflow.
> 
> You're right though, that it is _not_ an unsigned overflow (the parameter you passed on the command line). ESBMC is implicitly assuming `--overflow-check` when you pass `--unsigned-overflow-check`. The reason being that signed overflows are undefined behaviour in C, while unsigned overflows are not. We added the unsigned-overflow-check basically as an extension to the already existing one.
> 
> The left-hand side `x` of the assignment does not matter for the computation of the right-hand side. Only as a last step, after the computation is done, is the result converted to the type of the left-hand side. Before that, it is still signed int.
> 
> > It seems that in C standard if we do not specify that the addition is unsigned int it will converted to int...
> 
> Yes, integer literals by default are signed. Also applies for suffixes `L` or `LL`. Unsigned needs to be said explicitly in C - with one exception: If the integer literal cannot be represented by the signed version, then the unsigned version of the type is silently chosen.
> 
> Note that for binary arithmetic operations it is enough for just one side to be unsigned in order for the whole operation to be unsigned, e.g. `INT_MAX + 1U` is not an overflow, because it is an addition on unsigned int.
> 
> Hi @maferrag!
> 
> > x = A + 1;
> > arithmetic overflow on add
> > This is a false positive...
> 
> It is not. :) You're asking to perform a signed addition of two signed ints. The mathematical result 2**31 cannot be represented (on this machine) by a signed int, so you get an overflow.

Thanks @fbrausse the very detailed explanation. Yes I also figured out that we need explicitly say the unsigned integer like x = 2147483647U + 1U; Thanks again the detailed explanation.  So everything is correct here, and we indeed have an overflow. It is just very weird how C handle this. Thanks.. I think this can be closed....

**Comment by fbrausse** [comment]
>  It is just very weird how C handle this.

Indeed. In such cases it might also be helpful to give `--parse-tree-only` or `--parse-tree-too` to ESBMC. It will print a representation of the Clang AST including all implicit conversions that happen. For `x = INT_MAX + 1U` for instance it shows this:
![image](https://github.com/esbmc/esbmc/assets/3314468/1b4483c4-2333-4a7f-90fc-2e2b4c791d1e)

As for the weirdness: in C++20 and C23 we did get fortunately a tiny bit further (from Wikipedia on C++20):
> [signed integers](https://en.wikipedia.org/wiki/Signed_integer) are now defined to be represented using [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) (signed integer overflow remains [undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior))[[32]](https://en.wikipedia.org/wiki/C%2B%2B20#cite_note-32)

> Thanks.. I think this can be closed....

OK, thank you. Please do feel free to open issues if you encounter any problems.
