### ISSUE TITLE
[Ctest] memory usage

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#1847]
Can we print the amount of memory usage with Ctest?

I noticed that the python script has this feature, but it is not shown in using ctest:
https://github.com/esbmc/esbmc/blob/602c8d68d934078caea2010adeabefeae321ffe4/regression/testing_tool.py#L149-L150

We needed this feature, and I couldn't use the python script, it kept getting errors.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Could you please check on this issue?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Could you please check on this issue?

**Comment by rafaelsamenezes** [comment]
> Can we print the amount of memory usage with Ctest?

You can probably get it from the output and log files, see [ctest docs](https://cmake.org/cmake/help/latest/manual/ctest.1.html).

**Comment by XLiZHI** [comment]
> > Can we print the amount of memory usage with Ctest?
> 
> You can probably get it from the output and log files, see [ctest docs](https://cmake.org/cmake/help/latest/manual/ctest.1.html).

Thanks @rafaelsamenezes , Can I ask how we can add `flags`, such as `--cvc5`.

**Comment by rafaelsamenezes** [comment]
> > > Can we print the amount of memory usage with Ctest?
> > 
> > 
> > You can probably get it from the output and log files, see [ctest docs](https://cmake.org/cmake/help/latest/manual/ctest.1.html).
> 
> Thanks @rafaelsamenezes , Can I ask how we can add `flags`, such as `--cvc5`.

The easiest way would be to use the `ESBMC_OPTS` environment variable.
