### ISSUE TITLE
Modifying the wrapper 

### ISSUE THREAD

**Issue by fatimahkj** [esbmc/esbmc#185]
Hi, I'm currently trying to modify the wrapper to export the test cases from ESBMC on my source code. I had a problem when I try to let the wrapper accept any input not only the __VERIFIER nondet 

I have this problem, anyone has an idea of how to fix it?
![Screenshot from 2020-05-21 13-53-14](https://user-images.githubusercontent.com/47563480/82562267-cd381780-9b6c-11ea-8c9b-32c34cd008b0.png)

Thanks in advance.

**Comment by rafaelsamenezes** [comment]
This looks like a problem of the method `writeTestCase` using '+' instead of os.path.join. There are two ways to solving it.

1. The bad way: check if __testSuiteDir__ terminates with a '/' or the testcase_file begins with a '/' 

2. The right way: On ```TestCompGenerator(assumptions).writeTestCase(__testSuiteDir__ + "/" + testcase_file```change it to use [```os.path.join```](https://docs.python.org/3/library/os.path.html#os.path.join). Be sure that the second argument does not begin with a "/" 

Since you are customizing the wrapper I don't know if sending a custom version of the wrapper would help. If you need any extra help feel free to send me your wrapper or to ask.

In the normal wrapper I would change
```py
def createTestFile(witness, source):
    assumptions = __getNonDetAssumptions__(witness, source)    
    TestCompGenerator(assumptions).writeTestCase(__testSuiteDir__ + "/testcase.xml")
    metadataParser = MetadataParser(witness)
    metadataParser.parse()
    TestCompMetadataGenerator(metadataParser.metadata).writeMetadataFile()
```

to

```py
def createTestFile(witness, source):
    assumptions = __getNonDetAssumptions__(witness, source)    
    TestCompGenerator(assumptions).writeTestCase(os.path.join(__testSuiteDir__, "testcase.xml"))
    metadataParser = MetadataParser(witness)
    metadataParser.parse()
    TestCompMetadataGenerator(metadataParser.metadata).writeMetadataFile()
```

BTW, this could also happen in function `writeMetadataFile`. The fixed version should be:
```py
def writeMetadataFile(self):
        """ Write metadata.xml file """
    root = ET.Element("test-metadata")
    # TODO: add support to enter function
    ET.SubElement(root, 'entryfunction').text = 'main'
    ET.SubElement(root, 'specification').text = property_file_content.strip()
    properties = {'sourcecodelang', 'sourcecodelang', 'producer',
                  'programfile', 'programhash', 'architecture', 'creationtime'}
    for property in properties:
        ET.SubElement(root, property).text = self.metadata[property]
     
    output = os.path.join(__testSuiteDir__, "metadata.xml")
    ET.ElementTree(root).write(output)
    with open(output, 'r') as original: data = original.read()
    with open(output, 'w') as modified: modified.write('<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE test-metadata PUBLIC "+//IDN sosy-lab.org//DTD test-format test-metadata 1.0//EN" "https://sosy-lab.org/test-format/test-metadata-1.0.dtd">' + data)
```

**Comment by fatimahkj** [comment]
Hi Rafael, 
Thanks for your quick response.
I fixed my wrapper based on what you said. The good thing that It fixed the previous errors but unfortunately I encountered another error. Its Python error

![image](https://user-images.githubusercontent.com/47563480/82569741-8fd98700-9b78-11ea-9865-f60d9d449490.png)

**Comment by rafaelsamenezes** [comment]
There is an Indentation error on line 300. Check if its following the right spacing

**Comment by fatimahkj** [comment]
Yes, I was trying to fix it. I will keep trying.
I will tell you if it works and generates the test cases I need.

Thanks for your help. I really appreciate it.

**Comment by fatimahkj** [comment]
Hi Rafael, 

It works. I had some other issues but finally, I figure them out

Thanks

**Comment by rafaelsamenezes** [comment]
Great to hear, I will close this for now. If you need any extra help feel free to reopen it.
