### ISSUE TITLE
c_link warnings for C++ headers included in multiple source files

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#1859]
Consider two files, say a.cc and b.cc both containing just
```c++
#include <algorithm>
```
Running ESBMC on both files results in plenty of c_link warnings:
```
WARNING: function `max' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `max' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `max' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `min' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `min' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `min' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `max_element' in module `algorithm' is shadowed by a definition in module `algorithm'
WARNING: function `min_element' in module `algorithm' is shadowed by a definition in module `algorithm'
```
Ideally, it wouldn't, because of C++'s [One Definition Rule](https://en.cppreference.com/w/cpp/language/definition). It might be possible to modify the c_link implementation to handle C++ symbols differently than C ones. Alternatively, a new cxx_link implementation could be considered.

This issue was raised by an industrial partner verifying a C++ program. We don't have access to their exact source files.

**Comment by XLiZHI** [comment]
As for the first warning, it happens when `a.cc` `b.cc` contains the same header file:
_example.h_
```
#pragma once
const void max() {}
```
The warning only occurs if `const` is used.

As for the second error, it seems to be related to the virtual function, which I haven't reproduced yet.

**Comment by mikhailramalho** [comment]
Some suggestion to fix it in #883

**Comment by fbrausse** [comment]
> As for the first warning, it happens when `a.cc` `b.cc` contains the same header file: _example.h_
> 
> ```
> #pragma once
> const void max() {}
> ```
> 
> The warning only occurs if `const` is used.
> 
> As for the second error, it seems to be related to the virtual function, which I haven't reproduced yet.

I'm not sure this is a good example showing that c_link is wrong. Running GCC or Clang on it, for me it prints
```
/usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ccEzXqfZ.o: in function `max()':
b.cc:(.text+0x0): multiple definition of `max()'; /tmp/ccTOJHqi.o:a.cc:(.text+0x0): first defined here
```
So the c_link warning is justified in this case.

Either making the function inline or a template (which implicitly inline, and which std::max() is) is closer to the original test case in this issue.

**Comment by XLiZHI** [comment]
closed via https://github.com/esbmc/esbmc/pull/1875
