### ISSUE TITLE
Unable to run ESBMC on PCIe driver

### ISSUE THREAD

**Issue by vipin-ravi-bharadwaj** [esbmc/esbmc#1864]
This is the command I ran to verify PCIe driver -
`esbmc /usr/src/linux/drivers/cxl/pci.c -I /usr/src/linux/arch/x86/include/ -I /usr/src/linux/arch/x86/include/generated/  -I /usr/src/linux/include -I /usr/src/linux/arch/x86/include/uapi -I /usr/src/linux/arch/x86/include/generated/uapi -I /usr/src/linux/include/uapi -I /usr/src/linux/include/generated/uapi --include-file /usr/src/linux/./include/linux/compiler-version.h --include-file /usr/src/linux/./include/linux/kconfig.h --include-file /usr/src/linux/./include/linux/compiler_types.h  -D__KERNEL__ -DMODULE -DKBUILD_BASENAME='"pci"' -DKBUILD_MODNAME='"cxl_pci"' -D__KBUILD_MODNAME=kmod_cxl_pc`

I have replaced '/usr/src' to the path of my linux kernel folder and have verified the path. 

Error encountered log - 

ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing /usr/src/linux-6.8.8/drivers/cxl/pci.c
In file included from <built-in>:2:
/usr/src/linux-6.8.8/./include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found
    5 | #include <generated/autoconf.h>

Found that we need to build the kernel to run esbmc. I ran `make` command and this is the output - 

  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/kconfig/conf.o
  HOSTLD  scripts/kconfig/conf
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_64.h
  HYPERCALLS arch/x86/include/generated/asm/xen-hypercalls.h
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
  HOSTCC  scripts/genksyms/genksyms.o
  YACC    scripts/genksyms/parse.tab.[ch]
  HOSTCC  scripts/genksyms/parse.tab.o
  LEX     scripts/genksyms/lex.lex.c
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sorttable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/sign-file
  HOSTCC  scripts/insert-sys-cert
  WRAP    arch/x86/include/generated/uapi/asm/bpf_perf_event.h
  WRAP    arch/x86/include/generated/uapi/asm/errno.h
  WRAP    arch/x86/include/generated/uapi/asm/fcntl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctls.h
  WRAP    arch/x86/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/x86/include/generated/uapi/asm/param.h
  WRAP    arch/x86/include/generated/uapi/asm/poll.h
  WRAP    arch/x86/include/generated/uapi/asm/resource.h
  WRAP    arch/x86/include/generated/uapi/asm/socket.h
  WRAP    arch/x86/include/generated/uapi/asm/sockios.h
  WRAP    arch/x86/include/generated/uapi/asm/termbits.h
  WRAP    arch/x86/include/generated/uapi/asm/termios.h
  WRAP    arch/x86/include/generated/uapi/asm/types.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/irq_regs.h
  WRAP    arch/x86/include/generated/asm/kmap_size.h
  WRAP    arch/x86/include/generated/asm/local64.h
  WRAP    arch/x86/include/generated/asm/mmiowb.h
  WRAP    arch/x86/include/generated/asm/module.lds.h
  WRAP    arch/x86/include/generated/asm/rwonce.h
  WRAP    arch/x86/include/generated/asm/unaligned.h
  UPD     include/config/kernel.release
  UPD     include/generated/uapi/linux/version.h
  UPD     include/generated/utsrelease.h
  UPD     include/generated/compile.h
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  MKELF   scripts/mod/elfconfig.h
  HOSTCC  scripts/mod/modpost.o
  CC      scripts/mod/devicetable-offsets.s
  UPD     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/sumversion.o
  HOSTCC  scripts/mod/symsearch.o
  HOSTLD  scripts/mod/modpost
  UPD     include/generated/timeconst.h
  CC      kernel/bounds.s
  UPD     include/generated/bounds.h
  CC      arch/x86/kernel/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHKSHA1 include/linux/atomic/atomic-arch-fallback.h
  CHKSHA1 include/linux/atomic/atomic-instrumented.h
  CHKSHA1 include/linux/atomic/atomic-long.h
  DESCEND objtool
<stdin>:1:10: fatal error: libelf.h: No such file or directory
compilation terminated.
  HOSTCC  /usr/src/Dissertation/linux-6.8.8/tools/objtool/fixdep.o
  HOSTLD  /usr/src/Dissertation/linux-6.8.8/tools/objtool/fixdep-in.o
  LINK    /usr/src/Dissertation/linux-6.8.8/tools/objtool/fixdep
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/exec-cmd.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/help.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/pager.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/parse-options.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/run-command.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/sigchain.o
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/subcmd-config.o
  LD      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/libsubcmd-in.o
  AR      /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/libsubcmd.a
  INSTALL /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/include/subcmd/exec-cmd.h
  INSTALL /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/include/subcmd/help.h
  INSTALL /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/include/subcmd/pager.h
  INSTALL /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/include/subcmd/parse-options.h
  INSTALL /usr/src/Dissertation/linux-6.8.8/tools/objtool/libsubcmd/include/subcmd/run-command.h
  INSTALL libsubcmd_headers
  CC      /usr/src/Dissertation/linux-6.8.8/tools/objtool/arch/x86/special.o
In file included from /usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/objtool.h:13,
                 from /usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/arch.h:11,
                 from /usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/check.h:11,
                 from /usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/special.h:10,
                 from arch/x86/special.c:4:
/usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>
      |          ^~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/Dissertation/linux-6.8.8/tools/build/Makefile.build:106: /usr/src/Dissertation/linux-6.8.8/tools/objtool/arch/x86/special.o] Error 1
make[4]: *** [/usr/src/Dissertation/linux-6.8.8/tools/build/Makefile.build:158: arch/x86] Error 2
make[3]: *** [Makefile:66: /usr/src/Dissertation/linux-6.8.8/tools/objtool/objtool-in.o] Error 2
make[2]: *** [Makefile:73: objtool] Error 2
make[1]: *** [/usr/src/Dissertation/linux-6.8.8/Makefile:1360: tools/objtool] Error 2
make: *** [Makefile:240: __sub-make] Error 2

**Versions**: ESBMC version is 7.6.1, running on Ubuntu. Linux kernel version is 6.8.8.

**Comment by fbrausse** [comment]
> /usr/src/Dissertation/linux-6.8.8/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
10 | #include <gelf.h>

You need elfutils installed, which provides /usr/include/gelf.h

**Comment by vipin-ravi-bharadwaj** [comment]
Thank you for your response @fbrausse. I have installed elfutils and tried to run the command again. This time, I am getting Segmentation Fault error. I have attached the error trace below

This is my command - 
`esbmc /usr/src/linux-6.8.8/drivers/cxl/pci.c \
  -I /usr/src/linux-6.8.8/arch/x86/include/ \
  -I /usr/src/linux-6.8.8/arch/x86/include/generated/ \
  -I /usr/src/linux-6.8.8/include \
  -I /usr/src/linux-6.8.8/arch/x86/include/uapi \
  -I /usr/src/linux-6.8.8/arch/x86/include/generated/uapi \
  -I /usr/src/linux-6.8.8/include/uapi \
  -I /usr/src/linux-6.8.8/include/generated/uapi \
  --include-file /usr/src/linux-6.8.8/include/linux/compiler-version.h \
  --include-file /usr/src/linux-6.8.8/include/linux/kconfig.h \
  --include-file /usr/src/linux-6.8.8/include/linux/compiler_types.h \
  -D__KERNEL__ -DMODULE -DKBUILD_BASENAME='"pci"' -DKBUILD_MODNAME='"cxl_pci"' -D__KBUILD_MODNAME=kmod_cxl_pci
`

This is the output - 
ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing /usr/src/linux-6.8.8/drivers/cxl/pci.c
In file included from /usr/src/linux-6.8.8/drivers/cxl/pci.c:4:
In file included from /usr/src/linux-6.8.8/include/linux/io-64-nonatomic-lo-hi.h:5:
In file included from /usr/src/linux-6.8.8/include/linux/io.h:13:
In file included from /usr/src/linux-6.8.8/arch/x86/include/asm/io.h:327:
In file included from /usr/src/linux-6.8.8/include/asm-generic/io.h:994:
In file included from /usr/src/linux-6.8.8/include/linux/vmalloc.h:5:
In file included from /usr/src/linux-6.8.8/include/linux/spinlock.h:60:
In file included from /usr/src/linux-6.8.8/include/linux/thread_info.h:60:
In file included from /usr/src/linux-6.8.8/arch/x86/include/asm/thread_info.h:53:
In file included from /usr/src/linux-6.8.8/arch/x86/include/asm/cpufeature.h:5:
/usr/src/linux-6.8.8/arch/x86/include/asm/processor.h:519:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
  519 |         this_cpu_write(cpu_tss_rw.x86_tss.sp0, sp0);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-6.8.8/include/linux/percpu-defs.h:490:68: note: expanded from macro 'this_cpu_write'
  490 | #define this_cpu_write(pcp, val)        __pcpu_size_call(this_cpu_write_, pcp, val)
      |                                                                           ^~~
/usr/src/linux-6.8.8/include/linux/percpu-defs.h:363:22: note: expanded from macro '__pcpu_size_call'
  363 |         __verify_pcpu_ptr(&(variable));                                 \
      |                             ^~~~~~~~
/usr/src/linux-6.8.8/include/linux/percpu-defs.h:219:47: note: expanded from macro '__verify_pcpu_ptr'
  219 |         const void __percpu *__vpp_verify = (typeof((ptr) + 0))NULL;    \
      |                                                      ^~~
In file included from /usr/src/linux-6.8.8/drivers/cxl/pci.c:11:
In file included from /usr/src/linux-6.8.8/include/linux/pci.h:2106:
/usr/src/linux-6.8.8/arch/x86/include/asm/pci.h:128:20: warning: field 'data' with variable sized type 'struct setup_data' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
  128 |         struct setup_data data;
      |                           ^
Converting
WARNING: No definition attached to enum declaration, this is not standard C. Upstream issue <https://github.com/esbmc/esbmc/issues/1794> tracks this.
Segmentation fault (core dumped)

**Comment by fbrausse** [comment]
Hi @vipin-ravi-bharadwaj, I haven't tried linux-6.8.8, but already with linux-6.6.32 I'm getting
```
src/clang-c-frontend/clang_c_adjust_expr.cpp:591: void clang_c_adjust::adjust_type(typet&): Assertion `sz % a == 0' failed.
```
where sz == 8316 and a == 64 for the packed `struct fpstate` in the kernel. I would suggest we stick to the LTS release 6.1 for now, because that one works.

However, this error is unrelated to your's. Your error occurs when the path `/usr/src/linux-6.8.8` does *not* match the one where `make` has been invoked. Please try to re-run `make` in your kernel's path and potentially also switch to a v6.1 release, just so we're not chasing a moving target. For reference, 6.1.85 works for me.

**Comment by vipin-ravi-bharadwaj** [comment]
Thank you @fbrausse.

I shall try the same with v6.1 and update here.

**Comment by vipin-ravi-bharadwaj** [comment]
Thank you @fbrausse.

I have tried to run the same command with v6.1.85. The below is the error trace

ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing /home/vipin/Downloads/linux-6.1.85/drivers/cxl/pci.c
In file included from /home/vipin/Downloads/linux-6.1.85/drivers/cxl/pci.c:3:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/io-64-nonatomic-lo-hi.h:5:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/io.h:13:
In file included from /home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/io.h:332:
In file included from /home/vipin/Downloads/linux-6.1.85/include/asm-generic/io.h:994:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/vmalloc.h:5:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/spinlock.h:56:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/preempt.h:79:
In file included from /home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/preempt.h:7:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/thread_info.h:60:
In file included from /home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/thread_info.h:53:
In file included from /home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/cpufeature.h:5:
/home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/processor.h:552:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
  552 |         this_cpu_write(cpu_tss_rw.x86_tss.sp0, sp0);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/home/vipin/Downloads/linux-6.1.85/include/linux/percpu-defs.h:508:68: note: expanded from macro 'this_cpu_write'
  508 | #define this_cpu_write(pcp, val)        __pcpu_size_call(this_cpu_write_, pcp, val)
      |                                                                           ^~~
/home/vipin/Downloads/linux-6.1.85/include/linux/percpu-defs.h:375:22: note: expanded from macro '__pcpu_size_call'
  375 |         __verify_pcpu_ptr(&(variable));                                 \
      |                             ^~~~~~~~
/home/vipin/Downloads/linux-6.1.85/include/linux/percpu-defs.h:219:47: note: expanded from macro '__verify_pcpu_ptr'
  219 |         const void __percpu *__vpp_verify = (typeof((ptr) + 0))NULL;    \
      |                                                      ^~~
In file included from /home/vipin/Downloads/linux-6.1.85/drivers/cxl/pci.c:10:
In file included from /home/vipin/Downloads/linux-6.1.85/include/linux/pci.h:1962:
/home/vipin/Downloads/linux-6.1.85/arch/x86/include/asm/pci.h:127:20: warning: field 'data' with variable sized type 'struct setup_data' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
  127 |         struct setup_data data;
      |                           ^
Converting
WARNING: No definition attached to enum declaration, this is not standard C. Upstream issue <https://github.com/esbmc/esbmc/issues/1794> tracks this.
ERROR: main symbol `main' not found
ERROR: CONVERSION ERROR

Kindly let me know how to go about this error.

Thanks.

**Comment by fbrausse** [comment]
> Kindly let me know how to go about this error.

That's very good! Your're basically set for starting the verification of this driver (file). The "error" just says that there's no `main` function, which is understandable. After all, the pci.c file of the CXL driver is not a stand-alone program. So my approach here is to write a `main` function in a separate .c file (which we can additionally pass to ESBMC) and which invoked several of the driver's exported API functions in order to test whether there are any bugs ESBMC identifies by default.

The longer-term goal is not just to identify NULL-ptr dereferences, overflows or invalid memory accesses, but to find out whether the driver implements the CXL protocol correctly. Before we go there, I'd recommend starting with some simple `main` function that calls into the driver in order to see whether we handle the symbolic execution of its functions.

**Comment by vipin-ravi-bharadwaj** [comment]
Hello @fbrausse ,

As per your instructions, I have written a main file to include few API functions. But when I run ESBMC, it get the output - No backend solvers found. Then, to verify the installed solvers, I ran `esbmc --list-solvers` and was not able to find anything installed.

I am trying to reinstall ESBMC by following the instructions present here - https://github.com/esbmc/esbmc/blob/master/BUILDING.md.

I am now facing the below error when I run - 
`cd esbmc && mkdir build && cd build && cmake .. -GNinja -DBUILD_TESTING=On -DENABLE_REGRESSION=On $ESBMC_CLANG -DBUILD_STATIC=${ESBMC_STATIC:-ON} -DBoolector_DIR=$PWD/../../boolector-release -DZ3_DIR=$PWD/../../z3 -DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat -DENABLE_YICES=On -DYices_DIR=$PWD/../../yices -DCVC4_DIR=$PWD/../../cvc4 -DGMP_DIR=$PWD/../../gmp -DBitwuzla_DIR=$PWD/../../bitwuzla-release -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release`

Error - 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Looking for LLVM in: /usr/lib/llvm-11/lib/cmake/llvm CMake Error at scripts/cmake/FindLocalLLVM.cmake:11 (find_package):   Could not find a package configuration file provided by "LLVM" with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set   "LLVM_DIR" to a directory containing one of the above files.  If "LLVM" provides a separate development package or SDK, be sure it has been installed.
 
Call Stack (most recent call first):
  CMakeLists.txt:101 (include)

-- Configuring incomplete, errors occurred!

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

This is my folder structure with the necessary dependencies and solvers
![Screenshot from 2024-07-08 20-08-26](https://github.com/esbmc/esbmc/assets/162708644/53ac41c7-26bf-4dd7-994e-60fd5d97d519)

Kindly let me know how to go about this error.

Thanks in advance.

**Comment by lucasccordeiro** [comment]
@vipin-ravi-bharadwaj: you could try our simple building process:

https://github.com/esbmc/esbmc/blob/master/README.md

````
sudo apt update
sudo apt-get install -y clang-14 llvm-14 clang-tidy-14 python-is-python3 python3 git ccache unzip wget curl bison flex g++-multilib linux-libc-dev libboost-all-dev libz3-dev libclang-14-dev libclang-cpp-dev cmake
git clone https://github.com/esbmc/esbmc.git
mkdir build && cd build
cmake ../esbmc -DENABLE_Z3=1
make -j4
````

**Comment by vipin-ravi-bharadwaj** [comment]
Thank you @lucasccordeiro . I was able to install ESBMC on my system and proceed further.

**Comment by lucasccordeiro** [comment]
Excellent, @vipin-ravi-bharadwaj. Thanks for letting us know.

**Comment by fbrausse** [comment]
@vipin-ravi-bharadwaj What's the status of this issue?

**Comment by vipin-ravi-bharadwaj** [comment]
Hi @fbrausse 

I was able to write a main function and proceed with the verification of the driver.

Thank you for your help @fbrausse and @lucasccordeiro in resolving this issue.
