### ISSUE TITLE
Trouble cloning repository

### ISSUE THREAD

**Issue by ktachak20** [esbmc/esbmc#188]
Tried cloning the repository but gives error message as follows:
```
error: invalid path 'regression/esbmc-cpp/stream/istream_operator>>_bool/main.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

I wonder what am I doing wrong.

**Comment by lucasccordeiro** [comment]
Which command-line are you using to clone? Have you tried `git clone git@github.com:YOURNAME/esbmc.git`?

**Comment by rafaelsamenezes** [comment]
Are you on Windows? Cloning does not work in there because of the ">>" in the file. I am not sure if renaming it would solve, @mikhailramalho do you have access to a Windows machine to test this?

**Comment by mikhailramalho** [comment]
Hi, are you using windows? Some of the directories in our repo have names that are not supported by Windows.

The workaround is to do a git sparse checkout and not cloning `regression/esbmc-cpp`.

**Comment by ktachak20** [comment]
Cloning on linux fixed the issue. I was using windows earlier. Thanks!

**Comment by lucasccordeiro** [comment]
Super! I have seen that you are developing a tool to extract SMT equations from C programs.

You could use the k-induction proof rule of ESBMC to produce intricate SMT equations; they are hard to be solved by state-of-the-art SMT solvers.
