### ISSUE TITLE
ninja install fails with result 'build stopped: subcommand failed'

### ISSUE THREAD

**Issue by ktachak20** [esbmc/esbmc#192]
Tried building esbmc but fails with errors. The error output is given below:
```
[1/84] Building CXX object src/big-int/CMakeFiles/bigint.dir/bigint.cpp.o
FAILED: src/big-int/CMakeFiles/bigint.dir/bigint.cpp.o
/usr/bin/c++  -DBOOST_PYTHON_STATIC_LIB -DWITH_PYTHON -I/usr/include/python3.6m -I../src -static -fPIC -g -fPIC   -std=gnu++14 -MD -MT src/big-int/CMakeFiles/bigint.dir/bigint.cpp.o -MF src/big-int/CMakeFiles/bigint.dir/bigint.cpp.o.d -o src/big-int/CMakeFiles/bigint.dir/bigint.cpp.o -c ../src/big-int/bigint.cpp
../src/big-int/bigint.cpp: In function ‘void build_bigint_python_class()’:
../src/big-int/bigint.cpp:1247:29: error: ‘to_int’ is not a member of ‘BigInt’
     .def("to_int", &BigInt::to_int)
                             ^~~~~~
[2/84] Building CXX object src/solvers/CMakeFiles/solve.dir/smt_python.cpp.o
ninja: build stopped: subcommand failed.
```

I am on a virtual machine with ubuntu 18.04. The following is the build command I used:
```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=On -DENABLE_REGRESSION=On -DENABLE_PYTHON=On -DClang_DIR=$PWD/../../clang9 -DLLVM_DIR=$PWD/../../clang9 -DBUILD_STATIC=On -DBoolector_DIR=$PWD/../../boolector-release -DZ3_DIR=$PWD/../../z3 -DENABLE_YICES=On -DYices_DIR=$PWD/../../yices -DGMP_DIR=$PWD/../../gmp -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../release
```

Earlier I had a 'Memory Exhausted' Error but I increased the swap space which solved the problem. Now this problem occurs. I have been trying for two days. Any help would be appreciated.

As an aside question, will it be okay if I build without 'BUILD_STATIC' option? Will I have python support without it?

**Comment by mikhailramalho** [comment]
Hi @ktachak20,

Yeah, our python API has some bugs... Are you planning to use it? ESBMC will compile just fine without it.

> As an aside question, will it be okay if I build without 'BUILD_STATIC' option? Will I have python support without it?

Building static and enabling python are independent options, you can set both, neither and anything in-between.

**Comment by ktachak20** [comment]
Hi @mikhailramalho,
Thank you for answering. Actually I have built ESBMC before. These errors are from when I was building with python support. I thought it would be more convenient to use the python api as I am more comfortable with python.

Should I close this? Thanks anyway.

**Comment by mikhailramalho** [comment]
No worries, I'll close it. We are dropping the python support for now, as no one in our team seems to be maintaining it anymore.
