### ISSUE TITLE
All comments in C-style

### ISSUE THREAD

**Issue by feliperodri** [esbmc/esbmc#196]
Adopt C-style comments and update the entire codebase.

**Comment by rafaelsamenezes** [comment]
Could you provide an example?

Ideally you should adapt [clang-format](https://github.com/esbmc/esbmc/blob/master/.clang-format) file and run:

```
find src -iname *.h -o -iname *.c -o -iname *.cpp -o -iname *.hpp -iname *.hh | grep -v src/ansi-c/cpp | xargs clang-format -style=file -i -fallback-style=none
```

Note that you should use clang-format on version 9 and this script will only work for `bash`

**Comment by mikhailramalho** [comment]
Should we close this? We discussed it offline and there seems to be no gain in doing it.

**Comment by feliperodri** [comment]
Yes, let's close it.
