### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#197]
Update: This is being worked on the `windows-build` branch

We should be able to support Windows which could help bring new users. This does not need any knowledge of how ESBMC works so it shouldn't be hard.

Requirements:
- Build ESBMC in Windows 10 with Boolector and/or Z3.
- Integrate it into the CI.

Notes:
- If CI fails when using Windows headers, then mark it to continue-on-error and open an issue.
- [vcpkg](https://github.com/microsoft/vcpkg) should make some dependencies easier to obtain but it should be used in conjunction with caching.
- [MSYS2](https://www.msys2.org/) can be used for some hard-to-find windows dependencies such as `flex` and `bison`.
- [LLVM](https://llvm.org/) releases for Windows does not ship with CMake modules, to use them a manual build is required or rewrite [FindLLVM](https://github.com/esbmc/esbmc/blob/master/scripts/cmake/FindLLVM.cmake) to use another logic for Windows. If manually built, then it should be cached.

**Comment by mikhailramalho** [comment]
There at least two scripts used during compilation that will need to be rewritten, the flail.sh and buildstring.sh.

**Comment by rafaelsamenezes** [comment]
Also, [clang-c-language](https://github.com/esbmc/esbmc/blob/master/src/clang-c-frontend/clang_c_language.cpp#L38) should use `boost::filesystem` to join the path

**Comment by rafaelsamenezes** [comment]
> There at least two scripts used during compilation that will need to be rewritten, the flail.sh and buildstring.sh.

Actually, they should work fine in [WSL](https://docs.microsoft.com/pt-br/windows/wsl/about).
