### ISSUE TITLE
Internal assertion failure when handling ternary expression

### ISSUE THREAD

**Issue by ChenfengWei0** [esbmc/esbmc#2000]
```c
#include <assert.h>
#include <stdbool.h>

bool t2()
{
    bool x;
    return x;
}

bool t1()
{
    return 1 == 2 && t2();
}

int main()
{
    int nS;
    int nE = t1();
    bool x = nS ? nE ?: (nS > nE) : (nS < nE);
}
```

**CBMC**
```c
CBMC version 5.80.0 (cbmc-5.80.0) 64-bit x86_64 linux
Parsing test.c
Converting
Type-checking test
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.000575161s
size of program expression: 41 steps
simple slicing removed 0 assignments
Generated 0 VCC(s), 0 remaining after simplification
Runtime Postprocess Equation: 4.0658e-05s
VERIFICATION SUCCESSFUL
```

**ESBMC**
```
ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing test.c
Converting
Generating GOTO Program
esbmc: /root/workspace/ESBMC_Commit/esbmc_master/src/irep2/irep2_expr.h:1961: if2t::if2t(const type2tc&, const expr2tc&, const expr2tc&, const expr2tc&): Assertion `type->type_id == falseval->type->type_id' failed.
[1]    2891 IOT instruction  ./esbmc test.c
```

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: could you please further reduce this example using creduce?

You can find the instructions on our wiki. After you reduce the example, you might also compare the symbol table and goto representation of CBMC and ESBMC.

I suspect that we are building an ill-formed expression in our Clang-C frontend?

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: @mikhailramalho and/or @XLiZHI can give you some guidance here if the bug is located in our clang-c frontend.

**Comment by XLiZHI** [comment]
Hi @ChenfengWei0 ,

For me, the issue is the same as for https://github.com/esbmc/esbmc/pull/1692, the question is whether we can remove our own "Usual arithmetic conversions" method for C validation.

https://github.com/esbmc/esbmc/blob/93e385549b6cd21f9ed6a28ff66a38a66a7c8531/src/clang-c-frontend/clang_c_adjust_expr.cpp#L1351-L1361

_Edit:_ I only modified the C++ frontend in this PR, so when you use the C++ frontend, it works fine.

**Comment by ChenfengWei0** [comment]
Many thanks, @XLiZHI !

> I only modified the C++ frontend

Would it be possible to apply it to C?

**Comment by XLiZHI** [comment]
> Many thanks, @XLiZHI !
> 
> > I only modified the C++ frontend
> 
> Would it be possible to apply it to C?

I tried it in a PR, let's wait for the CI result.
