### ISSUE TITLE
[C++ verification] lacks std function support

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#2029]
Our industrial partners reported C++ functions not supported by ESBMC.

- [x] std::isnan
- [x] std::size_t
- [x] std::max
- [x] std::min
- [x] std::bad_alloc
- [x] std::max_element
- [x] std::map
- [x] std::initializer_list
- [x] std::round
- [x] std::nullptr_t
- [x] std::is_enum
- [x] std::is_same
- [x] std::is_pod
- [x] std::isnan
- [x] std::numeric_limits
- [x] std::min_element
- [x] std::alignment_of
- [x] std::string
- [x] std::fill
- [x] std::enable_if
- [x] std::exp
- [x] std::underlying_type
- [x] std::ceil
- [x] std::nullptr
- [x] std::isnormal
- [x] std::exception
- [x] std::trunc
- [x] std::to_string
- [x] std::unique_ptr
- [x] std::get
- [x] std::tuple
- [x] std::array

**Comment by lucasccordeiro** [comment]
This https://github.com/esbmc/esbmc/pull/2032 should fix this issue.
