### ISSUE TITLE
[C++ Verification] C++ Standard Library Features to Review

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#2046]
This list was sent by one of our industrial partners; it represents the methods they need to verify their C++ design.

- [ ] `std::get`
- [ ] `std::size_t`
- [ ] `std::max`
- [ ] `std::min`
- [ ] `std::to_string`
- [ ] `std::bad_alloc`
- [ ] `std::array`
- [ ] `std::max_element`
- [ ] `std::map`
- [ ] `std::initializer_list`
- [ ] `std::round`
- [ ] `std::nullptr_t`
- [ ] `std::is_enum`
- [ ] `std::is_same`
- [ ] `std::is_pod`
- [ ] `std::isnan`
- [ ] `std::numeric_limits`
- [ ] `std::min_element`
- [ ] `std::alignment_of`
- [ ] `std::string`
- [ ] `std::trunc`
- [ ] `std::fill`
- [ ] `std::enable_if`
- [ ] `std::unique_ptr`
- [ ] `std::exp`
- [ ] `std::underlying_type`
- [ ] `std::ceil`
- [ ] `std::nullptr`
- [ ] `std::tuple`
- [ ] `std::isnormal`
- [ ] `std::exception`

**Comment by XLiZHI** [comment]
It's a duplicate #2029.

**Comment by lucasccordeiro** [comment]
Excellent, @XLiZHI.

Many thanks for pointing this out.
