### ISSUE TITLE
 Error compiling with CVC4

### ISSUE THREAD

**Issue by vanderson-rocha** [esbmc/esbmc#205]
When compiling with the -DCVC4_DIR flag, the following error occurs:

CMake Error at scr/solvers/cvc4/CMakeLists.txt: 12 (find_package):
Could not find a package configuration file provided by "CVC4" with any of the following names:
CVC4Config.cmake
cvc4-config.cmake

The error also occurs even without flag use

SO: Ubuntu 18.04 64Bits
Following instructions from: https://github.com/esbmc/esbmc/blob/master/BUILDING.md

**Comment by rafaelsamenezes** [comment]
Since the latest CVC4 patch we are using it from Git to generate cmake modules. I will update the BUILDING file with the newer instructions.

Meanwhile, you can try:

```
git clone https://github.com/CVC4/CVC4.git && cd CVC4 && git reset --hard b826fc8ae95fc && ./contrib/get-antlr-3.4 && ./configure.sh --optimized --prefix=../cvc4 --static --no-static-binary && cd build && make -j4 && make install
```
