### ISSUE TITLE
Return correct exit code for --parse-tree-only

### ISSUE THREAD

**Issue by sshivaji** [esbmc/esbmc#2064]
--parse-tree-only  is great to validate C++ code before running esbmc. However, the exit code returned by it is always 6. It should return 0 if parse is correct and return a non zero exit code if there is a compile fail.

Example:

esbmc  --parse-tree-only test.c

**Comment by lucasccordeiro** [comment]
@XLiZHI: could you please check this issue?

**Comment by XLiZHI** [comment]
The return value is generated from this line of code:
https://github.com/esbmc/esbmc/blob/a4f82bb492e1ca73317ddefd06fd0b850de00d8f/src/esbmc/esbmc_parseoptions.cpp#L561-L562

What we do with "--parse-tree-only" is terminate the conversation and bmc:
https://github.com/esbmc/esbmc/blob/a4f82bb492e1ca73317ddefd06fd0b850de00d8f/src/esbmc/esbmc_parseoptions.cpp#L1622-L1638

The same goes for compilation errors, esbmc does not classify these "breaks".

**Comment by sshivaji** [comment]
Can we make it so that if the parse-tree is correct without compilation error, it should return exit code of 0 otherwise it can return 6.

The reason is if we want to use ESBMC constructs such as __ESBMC_assume, it will not compile with gcc. One way would be to use esbmc --parse-tree-only, and if that works, then we can pass it on to full ESBMC, otherwise we can resolve parse errors first via automated processes.

**Comment by XLiZHI** [comment]
I see. You need the return value to tell if there was an error compiling.

But it's hard to do this gracefully with the current code structure, there are several functions called between the two functions I mentioned above, all of which return a boolean. Therefore, there is no way to know what caused the interruption of the verification.

One possible solution I came up with is:

```
 if (get_goto_program(options, goto_functions)) 
   if (cmdline.isset("parse-tree-only")) 
      return 0;
   else
      return 6; 
```
Maybe our colleagues have a better idea.

**Comment by sshivaji** [comment]
Yes, that is acceptable, ideally even another option is better, but if parse-tree-only fails, we can still return 6, ie parse-tree-only fails due to compile errors.

**Comment by mikhailramalho** [comment]
I don't think we care about what's the exit code for esbmc, we have no documentation for what exiting with 6, 7 (or any other number) means AFAIK.

Maybe we could do something like:
```
#define check_and_return_if_fail(code)   \
   if (int ret = code(); ret)            \
     return ret; 
```
and then call:
```
check_and_return_if_fail(get_goto_program(options, goto_functions))
```
That way we could propagate the return values and define what they mean. We would need to change everything to return `int` instead of `bool` tho, but that would entail a huge amount of work.

~

how about:
```
      if (cmdline.isset("parse-tree-only"))
        exit(0);
```
Not a great solution IMHO, but at least it's short. We could do that for all `*-only` flags.

**Comment by sshivaji** [comment]
Can we distinguish this run case:

root@9fde7110e561:~# esbmc test_nondet_broken.c --unwind 3 --condition-coverage --no-slice --parse-tree-only
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing test_nondet_broken.c
test_nondet_broken.c:5:1: error: unknown type name 'asdfads'
asdfads
^

With a normal parse-tree-only output such as:

<img width="741" alt="image" src="https://github.com/user-attachments/assets/37258e3d-0e39-436a-ba28-f5072fbd5e8e">

I am open to any solution that returns false if parse tree cannot be generated, and any different return code if it can.

**Comment by XLiZHI** [comment]
> how about:
> 
> ```
>       if (cmdline.isset("parse-tree-only"))
>         exit(0);
> ```
> 
> Not a great solution IMHO, but at least it's short. We could do that for all `*-only` flags.

I agree with this solution, let's open a PR to fix it?

I've tested it and it meets the requirements we mentioned above.

**Comment by sshivaji** [comment]
But will this solve the problem of not returning 0 if there are compile
errors?

I am fine with opening a PR on your solution. I can quickly test it too if it returns the right output.

**Comment by XLiZHI** [comment]
> But will this solve the problem of not returning 0 if there are compile errors?
> […](#)
> Message ID: ***@***.***>

Yes, It returns 6 when there is a compilation error.

**Comment by sshivaji** [comment]
Wow, that is great then, More than works for my needs!

**Comment by lucasccordeiro** [comment]
@XLiZHI: can you please submit a PR with this solution? It works well for @sshivaji.

**Comment by sshivaji** [comment]
Can you open a PR with this then? Looks like it can work!

**Comment by lucasccordeiro** [comment]
@sshivaji: Is this issue fixed in the master branch?

**Comment by sshivaji** [comment]
This issue is fixed in the master branch, thanks a lot for the change!! I will close the issue.

**Comment by lucasccordeiro** [comment]
Many thanks, @sshivaji.
