### ISSUE TITLE
[Coverage] ESBMC does not generate test case with coversBanch="true"

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#2069]
$ esbmc foo.c --branch-coverage --generate-testcase

````C
#include <stdio.h>

int a;
void foo(int x) {
  if (x > 7)
    a = a*4;
  printf("a: %i", a);
}

int main() {
  int x = nondet_int();
  foo(x);
  return 0;
}
````

````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE testcase PUBLIC "+//IDN sosy-lab.org//DTD test-format testcase 1.1//EN" "https://sosy-lab.org/test-format/testcase-1.1.dtd">
<testcase coversError="true">
<input>-67108857</input>
</testcase>
````

**Comment by ChenfengWei0** [comment]
I discussed this with Rafael last Thursday.

Although it's unlikely, we still need to run the `testcov` to ensure that removing `<testcase coversError="true">` won't cause any issues. (Personally, I think we should be fine as the template given by the Test-Comp does not contain this statement)

Also a quick question, does ESBMC participate in the `branch-error` category in Test-Comp? If so, we might need to keep it.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: The idea is not to remove, but to add the coversBranch flag. 

When you run ESBMC with --branch-coverage, we should add this flag to the XML file.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: Is this issue still valid?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: Is this issue still valid?

I think it is not valid any more
