### ISSUE TITLE
CMake broke the old frontend

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#207]
Looks like the reason why esbmc is stuck is related to the cmake build; it is also happening in the old C frontend.

I found at least one missing dependency there: the cpp flex/bison parser depends on the ansi-c one, and there is no clear relation between them. 

I also noticed that there is not clear inclusion of the generated parser in the build, some references mention variables `${FLEX_LIBRARIES} ${BISON_LIBRARIES}` and some others:

https://stackoverflow.com/questions/2491421/cmake-command-syntax-question
https://stackoverflow.com/questions/50827935/how-to-write-a-working-cmake-file-for-flex-bison

So I believe that the parser is not actually being called. @rafaelsamenezes could you check it?

_Originally posted by @mikhailramalho in https://github.com/esbmc/esbmc/issues/198#issuecomment-643847068_

**Comment by rafaelsamenezes** [comment]
Looking at the old Makefiles I couldn't found that dependency for `cpp`, but I did found it for `ansi-c`. In `ansi-c` that dependency exists and is used. So it shouldn't broke the old frontend. However, since I am not very familiar with autoconf I will put this on hold for now.

**Comment by mikhailramalho** [comment]
Fixed by c557236cc.
