### ISSUE TITLE
[Coverage] ESBMC must achieve 100% branch coverage

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#2070]
$ esbmc code_coverage.cpp --unwind 10 --branch-coverage --compact-trace

````C
#include <cassert>
int main() {
  int valve = nondet_int();  // environment
  int input = nondet_int();  // user input
  while (input) {
    if (!valve) {
      assert(valve == 0); // "privacy"
      valve = 1;
    }
    else if (valve == 1) {
      assert(valve > 0); // "performance"
       valve = 2;
    }
    else if (valve == 2) {
      assert(valve >= 2); // "vulnerability"
      valve = 3;
    }
  }
  assert(valve == 3);
}
````

````
[Coverage]

Branches : 16
Reached : 14
Branch Coverage: 87.5%

VERIFICATION FAILED
````

We produce the wrong tests for this particular branch:

![image](https://github.com/user-attachments/assets/b91945e9-a916-4b51-b407-3e63d0e92bad)

![image](https://github.com/user-attachments/assets/490d27a1-70d5-4c07-a567-d63be50e8bf4)

**Comment by ChenfengWei0** [comment]
Hmm...Several things here

1. When collecting branch coverage with `--unwind` option, we should always enable `--no-unwinding-assertions`.  So the coverage should now be:

```
Branches : 16
Reached : 13
Branch Coverage: 81.25%
```

I will make a PR to enable it when detecting `unwind` is enabled.

2. The result in the **C** program is correct. So at least for Test-Comp we will be fine.

```
Branches : 8
Reached : 8
Branch Coverage: 100%
```

3. If we look at the source code, we know that there are 1 `while` and 3 `if`, which means there should be only 8 branches. So the result for **C** is correct (8) and **C++** is incorrect (16). This can also be confirmed by CBMC.
 
The Incorrect result in **C++** is due to the Goto Program. E.g.

```c++
// Command
// esbmc code_coverage.cpp --goto-functions-only

// Source code from line 6-9.
if (!valve) {
  assert(valve == 0); // "privacy"
  valve = 1;
}

// Goto in C++
    IF !(!(_Bool)valve) THEN GOTO 3
    ASSERT valve == 0
    // This inserted assertion leads to the coverage miscalculated
    IF !(valve == 0) THEN GOTO 2
    OTHER 0;

2: ASSIGN valve=1;
    GOTO 7

// Goto in C
  IF !(!(_Bool)valve) THEN GOTO 2
  OTHER 4;

  ASSERT valve == 0
  ASSIGN valve=1;
```

@XLiZHI May I ask if, by any chance, you know how to avoid this insertion in C++? For me I feel like there should be an option to disable this kind of optimisation

**Comment by lucasccordeiro** [comment]
Many thanks, @ChenfengWei0.

@XLiZHI: there is room for improvement for our C++ front end.

**Comment by XLiZHI** [comment]
```c
// Goto in C++
    IF !(!(_Bool)valve) THEN GOTO 3
    ASSERT valve == 0
    // This inserted assertion leads to the coverage miscalculated
    IF !(valve == 0) THEN GOTO 2
    OTHER 0;

2: ASSIGN valve=1;
    GOTO 7

// Goto in C
  IF !(!(_Bool)valve) THEN GOTO 2
  OTHER 4;

  ASSERT valve == 0                   <------------assertion here
  ASSIGN valve=1;
```
~~We also have this assertion in C, I believe the goto difference between C and C ++ is assertion position.~~

~~I don't know much about coverage. Do we need to adjust the position of the assertion?~~

I see that we have extra goto statements in C++ based on assertions, maybe because of that.

**Comment by ChenfengWei0** [comment]
> ```c
> // Goto in C++
>     IF !(!(_Bool)valve) THEN GOTO 3
>     ASSERT valve == 0
>     // This inserted assertion leads to the coverage miscalculated
>     IF !(valve == 0) THEN GOTO 2
>     OTHER 0;
> 
> 2: ASSIGN valve=1;
>     GOTO 7
> 
> // Goto in C
>   IF !(!(_Bool)valve) THEN GOTO 2
>   OTHER 4;
> 
>   ASSERT valve == 0                   <------------assertion here
>   ASSIGN valve=1;
> ```
> 
> ~We also have this assertion in C, I believe the goto difference between C and C ++ is assertion position.~
> 
> ~I don't know much about coverage. Do we need to adjust the position of the assertion?~
> 
> I see that we have extra goto statements in C++ based on assertions, maybe because of that.

The assertion is for coverage. So what happens here is that, in C++ there is an additional auxiliary `IF !(valve == 0) THEN GOTO`, which will cause unexpected assertion instrumentation in coverage mode. So I would like to know if we could disable this auxiliary thing

**Comment by XLiZHI** [comment]
I think the statement `IF! (valve == 0) THEN GOTO` is redundant, it should be the same as C.

We need to find out where the goto statement was generated.

**Comment by XLiZHI** [comment]
```c
          `-CompoundStmt 0x71e1100 <col:17, line:9:5>
            |-ParenExpr 0x71e1080 </usr/include/assert.h:93:6, line:95:69> 'void'
            | `-ConditionalOperator 0x71e1050 <line:93:7, line:95:68> 'void'
            |   |-CXXStaticCastExpr 0x71ddcb0 <line:93:7, col:31> 'bool' static_cast<_Bool> <NoOp>
            |   | `-BinaryOperator 0x71ddc80 <main1.cpp:7:14, col:23> 'bool' '=='
            |   |   |-ImplicitCastExpr 0x71ddc68 <col:14> 'int' <LValueToRValue>
            |   |   | `-DeclRefExpr 0x71ddc28 <col:14> 'int' lvalue Var 0x71dd8f0 'valve' 'int'
            |   |   `-IntegerLiteral 0x71ddc48 <col:23> 'int' 0
            |   |-CXXFunctionalCastExpr 0x71ddd10 </usr/include/assert.h:94:9, col:16> 'void' functional cast to void <ToVoid>
            |   | `-IntegerLiteral 0x71ddcf0 <col:15> 'int' 0
            |   `-CallExpr 0x71e0fb0 <line:95:9, col:68> 'void'
            |     |-ImplicitCastExpr 0x71e0f98 <col:9> 'void (*)(const char *, const char *, unsigned int, const char *) __attribute__((noreturn)) noexcept(true)' <FunctionToPointerDecay>
            |     | `-DeclRefExpr 0x71e0f18 <col:9> 'void (const char *, const char *, unsigned int, const char *) __attribute__((noreturn)) noexcept(true)' lvalue Function 0x71dcec8 '__assert_fail' 'void (const char *, const char *, unsigned int, const char *) __attribute__((noreturn)) noexcept(true)'
            |     |-ImplicitCastExpr 0x71e0ff0 <<scratch space>:22:1> 'const char *' <ArrayToPointerDecay>
            |     | `-StringLiteral 0x71e0dd8 <col:1> 'const char[11]' lvalue "valve == 0"
            |     |-ImplicitCastExpr 0x71e1008 <line:23:1> 'const char *' <ArrayToPointerDecay>
            |     | `-StringLiteral 0x71e0e78 <col:1> 'const char[10]' lvalue "main1.cpp"
            |     |-ImplicitCastExpr 0x71e1020 <line:24:1> 'unsigned int' <IntegralCast>
            |     | `-IntegerLiteral 0x71e0ea0 <col:1> 'int' 7
            |     `-ImplicitCastExpr 0x71e1038 </usr/include/assert.h:129:30, col:44> 'const char *' <ArrayToPointerDecay>
            |       `-UnaryOperator 0x71e0f00 <col:30, col:44> 'const char[11]' lvalue prefix '__extension__' cannot overflow
            |         `-PredefinedExpr 0x71e0ee8 <col:44> 'const char[11]' lvalue __PRETTY_FUNCTION__
            |           `-StringLiteral 0x71e0ec0 <col:44> 'const char[11]' lvalue "int main()"
```

I investigated the issue and I found that this statement is directly generated by the AST.

This is later adjusted by `goto_convertt::generate_ifthenelse`:
```
if (guard)
  other 0;
else
 assert(guard);
 
//convert to
 
assert(guard);
if(!gurad)
  other 0;
```
If we make changes to this special case, it will affect other normal C++ ASTs.  So, I thought we might be able to improve the situation in the code for coverage.
