### ISSUE TITLE
[RFC] Should we start to squash + merge, instead of rebase + merge

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#2112]
I was one of the people who proposed rebase + merge but lately, I changed my mind:
1. Squash + merge should get rid of most (if not all) conflict when merging to master
2. Do we really need a bunch of commits with "addressed comments", "code style", etc. in our commit history?

I remember years since we decided to do rebase + merge and one of the main reasons was to revert individual commits but did we ever do that?

**Comment by XLiZHI** [comment]
I agree with squash + merge

**Comment by lucasccordeiro** [comment]
1. I also agree with squash + merge. 
2. We should squash the commits "fixed code style", "address comments", etc.

**Comment by brcfarias** [comment]
I agree we don’t need that level of granularity, but I’d prefer using squash + rebase for a linear and clean history. Also, having a few commits (ideally 1?) per PR, including the #issue-id, would help with that and make it easier to trace back to discussions and issues.

**Comment by lucasccordeiro** [comment]
I'm also okay with @brcfarias' suggestion.

**Comment by mikhailramalho** [comment]
> I agree we don’t need that level of granularity, but I’d prefer using squash + rebase for a linear and clean history. Also, having a few commits (ideally 1?) per PR, including the #issue-id, would help with that and make it easier to trace back to discussions and issues.

I agree, but I think that's just the github's nomenclature: currently we only enable "Rebase and merge", which doesn't create a merge commit at all.

The other options are: "Squash and merge" (which is what we want) and "Create merge commit" which I think does what it says.

**Comment by mikhailramalho** [comment]
I'll change the repo config
