### ISSUE TITLE
Constant propagation of member variables of struct

### ISSUE THREAD

**Issue by hassan-truscova** [esbmc/esbmc#2119]
I want to know if constant propagation of member variables of a struct is implemented or not?

Consider the following code:
```c
// example.c
#include <assert.h>

struct buffer {
	
	int size;
};

typedef struct buffer buffer;

int main () {

	int counter = 6;
	buffer buff;
	buff.size = 6;
 
	for (int i = 0; i < buff.size; i++) {
		counter--;				
	}
	
	assert (counter == 0);

	return counter;
}
```

If i execute given code without any switches, e.g., `--incremental-bmc` or `--unwind Nr`, it runs infinitely. However, if i replace `buff.size` with a constant value, it runs fine. Hence, my question whether constant propagation happens for member variables or not?

Thanks.

**Comment by lucasccordeiro** [comment]
Hi @hassan-truscova,

ESBMC does not propagate constants for member variables of struct.

I believe @Anthonysdu has implemented this feature in some branches but never merged it into the ESBMC master.

**Comment by lucasccordeiro** [comment]
I think @Anthonysdu's PR is here https://github.com/esbmc/esbmc/pull/1398/.

**Comment by hassan-truscova** [comment]
I read the PR and thought maybe it is now merged. Thanks for the quick response :)

**Comment by lucasccordeiro** [comment]
The PR is not merged :-) I think your question is still valid.

**Comment by Anthonysdu** [comment]
There is a PR preparing to support constant propagation for struct, array etc., but still needs to fix the regression tests first, we will merge that when it's ready.

**Comment by hassan-truscova** [comment]
@Anthonysdu thanks a lot for the update.

**Comment by lucasccordeiro** [comment]
@hassan-truscova: ESBMC should now propagate constants for member variables of the struct.

If you find further optimizations, please let us know.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/2128.

**Comment by hassan-truscova** [comment]
@lucasccordeiro thank you very much. Definitely, i will get in touch.
