### ISSUE TITLE
Question about --parse-tree-only flag

### ISSUE THREAD

**Issue by vanderson-rocha** [esbmc/esbmc#217]
Hello people.
When I use the --parse-tree or --parse-tree-only flags, several FunctionDecl appear, as in the section below, and after the code parse.
Am I right? If so, i would like to know what reason this section appears. Thanks for any feedback.

**ESBMC version 6.2.0 64-bit x86_64 linux
file /var/www/html/out/myesbmc5ee901fc7e3727.31341829.c: Parsing
TranslationUnitDecl 0x4e5de88 <<invalid sloc>> <invalid sloc>
|-TypedefDecl 0x4e5e720 <<invalid sloc>> <invalid sloc> implicit __int128_t '__int128'
| `-BuiltinType 0x4e5e420 '__int128'
|-TypedefDecl 0x4e5e790 <<invalid sloc>> <invalid sloc> implicit __uint128_t 'unsigned __int128'
| `-BuiltinType 0x4e5e440 'unsigned __int128'
|-TypedefDecl 0x4e5ea78 <<invalid sloc>> <invalid sloc> implicit __NSConstantString 'struct __NSConstantString_tag'
| `-RecordType 0x4e5e870 'struct __NSConstantString_tag'
|   `-Record 0x4e5e7e8 '__NSConstantString_tag'
|-TypedefDecl 0x4e5eb10 <<invalid sloc>> <invalid sloc> implicit __builtin_ms_va_list 'char *'
| `-PointerType 0x4e5ead0 'char *'
|   `-BuiltinType 0x4e5df20 'char'
|-TypedefDecl 0x4e5ede8 <<invalid sloc>> <invalid sloc> implicit __builtin_va_list 'struct __va_list_tag [1]'
| `-ConstantArrayType 0x4e5ed90 'struct __va_list_tag [1]' 1 
|   `-RecordType 0x4e5ebf0 'struct __va_list_tag'
|     `-Record 0x4e5eb68 '__va_list_tag'
|-FunctionDecl 0x4ee8e08 <esbmc_intrinsics.h:1:1, col:26> col:6 __ESBMC_assume 'void (_Bool)'
| `-ParmVarDecl 0x4ee8d40 <col:21> col:26 '_Bool'
|-FunctionDecl 0x4ee8f98 <line:2:1, col:18> col:6 used assert 'void (_Bool)'
| `-ParmVarDecl 0x4ee8f08 <col:13> col:18 '_Bool'
|-FunctionDecl 0x4ee91a8 <line:3:1, col:40> col:6 __ESBMC_assert 'void (_Bool, const char *)'
| |-ParmVarDecl 0x4ee9050 <col:21> col:26 '_Bool'
| `-ParmVarDecl 0x4ee90d0 <col:28, col:39> col:40 'const char *'
|-FunctionDecl 0x4ee93f8 <line:4:1, col:53> col:7 __ESBMC_same_object '_Bool (const void *, const void *)'
| |-ParmVarDecl 0x4ee92a0 <col:27, col:38> col:39 'const void *'
| `-ParmVarDecl 0x4ee9320 <col:41, col:52> col:53 'const void *'
|-FunctionDecl 0x4ee94f8 <line:5:1, col:27> col:6 __ESBMC_atomic_begin 'void ()'
|-FunctionDecl 0x4ee95b8 <line:6:1, col:25> col:6 __ESBMC_atomic_end 'void ()'
|-FunctionDecl 0x4ee9740 <line:8:1, col:20> col:5 __ESBMC_abs 'int (int)'
| `-ParmVarDecl 0x4ee9670 <col:17> col:20 'int'
|-FunctionDecl 0x4ee98d0 <line:9:1, col:31> col:10 __ESBMC_labs 'long (long)'
| `-ParmVarDecl 0x4ee9800 <col:23, col:28> col:31 'long'
|-FunctionDecl 0x4ee9a60 <line:10:1, col:42> col:15 __ESBMC_llabs 'long long (long long)'
| `-ParmVarDecl 0x4ee9990 <col:29, col:39> col:42 'long long'
|-FunctionDecl 0x4ee9bf0 <line:13:1, col:45> col:10 __ESBMC_POINTER_OBJECT 'unsigned int (const void *)'
| `-ParmVarDecl 0x4ee9b20 <col:33, col:44> col:45 'const void *'
|-FunctionDecl 0x4efeec0 <line:14:1, col:43> col:8 __ESBMC_POINTER_OFFSET 'int (const void *)'
| `-ParmVarDecl 0x4ee9cb0 <col:31, col:42> col:43 'const void *'
|-VarDecl 0x4eff068 <line:17:1, line:18:22> col:7 __ESBMC_alloc '_Bool [1]'
| `-AnnotateAttr 0x4eff0d0 <line:17:16, col:43> "__ESBMC_inf_size"
|-VarDecl 0x4eff1a8 <line:20:1, line:21:28> col:7 __ESBMC_deallocated '_Bool [1]'
| `-AnnotateAttr 0x4eff210 <line:20:16, col:43> "__ESBMC_inf_size"
|-VarDecl 0x4eff2e8 <line:23:1, line:24:27> col:7 __ESBMC_is_dynamic '_Bool [1]'
| `-AnnotateAttr 0x4eff350 <line:23:16, col:43> "__ESBMC_inf_size"
|-VarDecl 0x4eff470 <line:26:1, line:27:30> col:10 __ESBMC_alloc_size 'unsigned int [1]'
| `-AnnotateAttr 0x4eff4d8 <line:26:16, col:43> "__ESBMC_inf_size"
|-FunctionDecl 0x4eff578 <line:29:1, col:32> col:7 __ESBMC_is_little_endian '_Bool ()'
|-VarDecl 0x4eff630 <line:32:1, col:29> col:5 __ESBMC_rounding_mode 'int' cinit
| `-IntegerLiteral 0x4eff698 <col:29> 'int' 0
|-FunctionDecl 0x4eff6d8 <line:33:1, col:28> col:7 __ESBMC_floatbv_mode '_Bool ()'
|-FunctionDecl 0x4eff860 <line:35:1, col:28> col:8 __ESBMC_fabsd 'double (double)'
| `-ParmVarDecl 0x4eff790 <col:22> col:28 'double'
|-FunctionDecl 0x4eff9f0 <line:36:1, col:39> col:13 __ESBMC_fabsld 'long double (long double)'
| `-ParmVarDecl 0x4eff920 <col:28, col:33> col:39 'long double'
|-FunctionDecl 0x4effb80 <line:37:1, col:26> col:7 __ESBMC_fabsf 'float (float)'
| `-ParmVarDecl 0x4effab0 <col:21> col:26 'float'
|-FunctionDecl 0x4effd08 <line:39:1, col:27> col:7 __ESBMC_isnanf '_Bool (float)'
| `-ParmVarDecl 0x4effc40 <col:22> col:27 'float'
|-FunctionDecl 0x4f01eb8 <line:40:1, col:28> col:7 __ESBMC_isnand '_Bool (double)'
| `-ParmVarDecl 0x4effdc8 <col:22> col:28 'double'
|-FunctionDecl 0x4f02038 <line:41:1, col:34> col:7 __ESBMC_isnanld '_Bool (long double)'
| `-ParmVarDecl 0x4f01f78 <col:23, col:28> col:34 'long double'
|-FunctionDecl 0x4f02188 <line:43:1, col:30> col:7 __ESBMC_isfinite '_Bool (double)'
| `-ParmVarDecl 0x4f020f8 <col:24> col:30 'double'
|-FunctionDecl 0x4f022d8 <line:44:1, col:30> col:7 __ESBMC_isfinitef '_Bool (float)'
| `-ParmVarDecl 0x4f02248 <col:25> col:30 'float'
|-FunctionDecl 0x4f02428 <line:45:1, col:31> col:7 __ESBMC_isfinited '_Bool (double)'
| `-ParmVarDecl 0x4f02398 <col:25> col:31 'double'
|-FunctionDecl 0x4f02578 <line:46:1, col:37> col:7 __ESBMC_isfiniteld '_Bool (long double)'
| `-ParmVarDecl 0x4f024e8 <col:26, col:31> col:37 'long double'
|-FunctionDecl 0x4f026c8 <line:48:1, col:27> col:7 __ESBMC_isinf '_Bool (double)'
| `-ParmVarDecl 0x4f02638 <col:21> col:27 'double'
|-FunctionDecl 0x4f02818 <line:49:1, col:27> col:7 __ESBMC_isinff '_Bool (float)'
| `-ParmVarDecl 0x4f02788 <col:22> col:27 'float'
|-FunctionDecl 0x4f02968 <line:50:1, col:28> col:7 __ESBMC_isinfd '_Bool (double)'
| `-ParmVarDecl 0x4f028d8 <col:22> col:28 'double'
|-FunctionDecl 0x4f02ab8 <line:51:1, col:34> col:7 __ESBMC_isinfld '_Bool (long double)'
| `-ParmVarDecl 0x4f02a28 <col:23, col:28> col:34 'long double'
|-FunctionDecl 0x4f02c08 <line:53:1, col:26> col:7 __ESBMC_sign '_Bool (double)'
| `-ParmVarDecl 0x4f02b78 <col:20> col:26 'double'
|-FunctionDecl 0x4f02d58 <line:54:1, col:26> col:7 __ESBMC_signf '_Bool (float)'
| `-ParmVarDecl 0x4f02cc8 <col:21> col:26 'float'
|-FunctionDecl 0x4f02ec8 <line:55:1, col:27> col:7 __ESBMC_signd '_Bool (double)'
| `-ParmVarDecl 0x4f02e18 <col:21> col:27 'double'
|-FunctionDecl 0x4f03018 <line:56:1, col:33> col:7 __ESBMC_signld '_Bool (long double)'
| `-ParmVarDecl 0x4f02f88 <col:22, col:27> col:33 'long double'
|-FunctionDecl 0x4f03168 <line:58:1, col:30> col:7 __ESBMC_isnormal '_Bool (double)'
| `-ParmVarDecl 0x4f030d8 <col:24> col:30 'double'
|-FunctionDecl 0x4f032b8 <line:59:1, col:30> col:7 __ESBMC_isnormalf '_Bool (float)'
| `-ParmVarDecl 0x4f03228 <col:25> col:30 'float'
|-FunctionDecl 0x4f03408 <line:60:1, col:31> col:7 __ESBMC_isnormald '_Bool (double)'
| `-ParmVarDecl 0x4f03378 <col:25> col:31 'double'
|-FunctionDecl 0x4f03558 <line:61:1, col:37> col:7 __ESBMC_isnormalld '_Bool (long double)'
| `-ParmVarDecl 0x4f034c8 <col:26, col:31> col:37 'long double'
|-FunctionDecl 0x4f036d0 <line:63:1, col:24> col:8 __ESBMC_inf 'double (void)'
|-FunctionDecl 0x4f03840 <line:64:1, col:24> col:7 __ESBMC_inff 'float (void)'
|-FunctionDecl 0x4f039b0 <line:65:1, col:31> col:13 __ESBMC_infld 'long double (void)'
|-FunctionDecl 0x4f03b00 <line:67:1, col:31> col:7 __ESBMC_nearbyintf 'float (float)'
| `-ParmVarDecl 0x4f03a68 <col:26> col:31 'float'
|-FunctionDecl 0x4f03c58 <line:68:1, col:33> col:8 __ESBMC_nearbyintd 'double (double)'
| `-ParmVarDecl 0x4f03bc0 <col:27> col:33 'double'
|-FunctionDecl 0x4f03db0 <line:69:1, col:44> col:13 __ESBMC_nearbyintld 'long double (long double)'
| `-ParmVarDecl 0x4f03d18 <col:33, col:38> col:44 'long double'
|-FunctionDecl 0x4f040a0 <line:71:1, col:39> col:7 __ESBMC_fmaf 'float (float, float, float)'
| |-ParmVarDecl 0x4f03eb0 <col:20> col:25 'float'
| |-ParmVarDecl 0x4f03f30 <col:27> col:32 'float'
| `-ParmVarDecl 0x4f03fb0 <col:34> col:39 'float'
|-FunctionDecl 0x4f04360 <line:72:1, col:43> col:8 __ESBMC_fmad 'double (double, double, double)'
| |-ParmVarDecl 0x4f04170 <col:21> col:27 'double'
| |-ParmVarDecl 0x4f041f0 <col:29> col:35 'double'
| `-ParmVarDecl 0x4f04270 <col:37> col:43 'double'
|-FunctionDecl 0x4f04620 <line:73:1, col:64> col:13 __ESBMC_fmald 'long double (long double, long double, long double)'
| |-ParmVarDecl 0x4f04430 <col:27, col:32> col:38 'long double'
| |-ParmVarDecl 0x4f044b0 <col:40, col:45> col:51 'long double'
| `-ParmVarDecl 0x4f04530 <col:53, col:58> col:64 'long double'
|-FunctionDecl 0x4f04788 <line:75:1, col:26> col:7 __ESBMC_sqrtf 'float (float)'
| `-ParmVarDecl 0x4f046f0 <col:21> col:26 'float'
|-FunctionDecl 0x4f048e0 <line:76:1, col:28> col:8 __ESBMC_sqrtd 'double (double)'
| `-ParmVarDecl 0x4f04848 <col:22> col:28 'double'
|-FunctionDecl 0x4f04a38 <line:77:1, col:39> col:13 __ESBMC_sqrtld 'long double (long double)'
| `-ParmVarDecl 0x4f049a0 <col:28, col:33> col:39 'long double'
|-FunctionDecl 0x4f04ce0 <line:79:1, col:47> col:7 __ESBMC_memset 'void *(void *, int, unsigned int)'
| |-ParmVarDecl 0x4f04af8 <col:22, col:27> col:28 'void *'
| |-ParmVarDecl 0x4f04b78 <col:30> col:33 'int'
| `-ParmVarDecl 0x4f04bf8 <col:35, col:44> col:47 'unsigned int'
|-FunctionDecl 0x4f04ec0 <line:84:1, col:34> col:6 pthread_start_main_hook 'void (void)'
|-FunctionDecl 0x4f04ff8 <line:85:1, col:32> col:6 pthread_end_main_hook 'void (void)'
|-FunctionDecl 0x4f050f0 <line:88:1, col:16> col:5 nondet_int 'int ()'
|-FunctionDecl 0x4f051e0 <line:89:1, col:26> col:14 nondet_uint 'unsigned int ()'
|-FunctionDecl 0x4f052d0 <line:90:1, col:18> col:6 nondet_long 'long ()'
|-FunctionDecl 0x4f053c0 <line:91:1, col:28> col:15 nondet_ulong 'unsigned long ()'
|-FunctionDecl 0x4f054b0 <line:92:1, col:20> col:7 nondet_short 'short ()'
|-FunctionDecl 0x4f055a0 <line:93:1, col:30> col:16 nondet_ushort 'unsigned short ()'
|-FunctionDecl 0x4f05688 <line:94:1, col:18> col:6 nondet_char 'char ()'
|-FunctionDecl 0x4f05780 <line:95:1, col:28> col:15 nondet_uchar 'unsigned char ()'
|-FunctionDecl 0x4f05870 <line:96:1, col:26> col:13 nondet_schar 'signed char ()'
|-FunctionDecl 0x4f05930 <line:97:1, col:19> col:7 nondet_bool '_Bool ()'
|-FunctionDecl 0x4f05a20 <line:98:1, col:20> col:7 nondet_float 'float ()'
|-FunctionDecl 0x4f05b10 <line:99:1, col:22> col:8 nondet_double 'double ()'
|-FunctionDecl 0x4f05bd8 <line:102:1, col:27> col:5 __VERIFIER_nondet_int 'int ()'
|-FunctionDecl 0x4f05ca0 <line:103:1, col:37> col:14 __VERIFIER_nondet_uint 'unsigned int ()'
|-FunctionDecl 0x4f05d68 <line:104:1, col:29> col:6 __VERIFIER_nondet_long 'long ()'
|-FunctionDecl 0x4f066e0 <line:105:1, col:39> col:15 __VERIFIER_nondet_ulong 'unsigned long ()'
|-FunctionDecl 0x4f067a8 <line:106:1, col:31> col:7 __VERIFIER_nondet_short 'short ()'
|-FunctionDecl 0x4f06870 <line:107:1, col:41> col:16 __VERIFIER_nondet_ushort 'unsigned short ()'
|-FunctionDecl 0x4f06930 <line:108:1, col:29> col:6 __VERIFIER_nondet_char 'char ()'
|-FunctionDecl 0x4f069f8 <line:109:1, col:39> col:15 __VERIFIER_nondet_uchar 'unsigned char ()'
|-FunctionDecl 0x4f06ac0 <line:110:1, col:37> col:13 __VERIFIER_nondet_schar 'signed char ()'
|-FunctionDecl 0x4f06b80 <line:111:1, col:30> col:7 __VERIFIER_nondet_bool '_Bool ()'
|-FunctionDecl 0x4f06c48 <line:112:1, col:31> col:7 __VERIFIER_nondet_float 'float ()'
|-FunctionDecl 0x4f06d10 <line:113:1, col:33> col:8 __VERIFIER_nondet_double 'double ()'
|-FunctionDecl 0x4f06dd0 <line:115:1, col:23> col:6 __VERIFIER_error 'void ()'
|-FunctionDecl 0x4f06f48 <line:116:1, col:27> col:6 __VERIFIER_assume 'void (int)'
| `-ParmVarDecl 0x4f06e88 <col:24> col:27 'int'
|-FunctionDecl 0x4f07010 <line:117:1, col:30> col:6 __VERIFIER_atomic_begin 'void ()'
|-FunctionDecl 0x4f070d0 <line:118:1, col:28> col:6 __VERIFIER_atomic_end 'void ()'
|-FunctionDecl 0x4f07398 <line:120:1, col:44> col:7 __ESBMC_overflow_sadd '_Bool (int, int, int *)'
| |-ParmVarDecl 0x4f07188 <col:29> col:32 'int'
| |-ParmVarDecl 0x4f07208 <col:34> col:37 'int'
| `-ParmVarDecl 0x4f072b0 <col:39, col:43> col:44 'int *'
|-FunctionDecl 0x4f076f0 <line:121:1, col:60> col:7 __ESBMC_overflow_saddl '_Bool (long, long, long *)'
| |-ParmVarDecl 0x4f07468 <col:30, col:35> col:38 'long'
| |-ParmVarDecl 0x4f074e8 <col:40, col:45> col:48 'long'
| `-ParmVarDecl 0x4f07590 <col:50, col:59> col:60 'long *'
|-FunctionDecl 0x4f079d8 <line:122:1, col:76> col:7 __ESBMC_overflow_saddll '_Bool (long long, long long, long long *)'
| |-ParmVarDecl 0x4f077c0 <col:31, col:41> col:44 'long long'
| |-ParmVarDecl 0x4f07840 <col:46, col:56> col:59 'long long'
| `-ParmVarDecl 0x4f078f0 <col:61, col:75> col:76 'long long *'
|-FunctionDecl 0x4f07cb8 <line:123:1, col:71> col:7 __ESBMC_overflow_uadd '_Bool (unsigned int, unsigned int, unsigned int *)'
| |-ParmVarDecl 0x4f07aa8 <col:29, col:38> col:41 'unsigned int'
| |-ParmVarDecl 0x4f07b28 <col:43, col:52> col:55 'unsigned int'
| `-ParmVarDecl 0x4f07bd0 <col:57, col:70> col:71 'unsigned int *'
|-FunctionDecl 0x4f07f98 <line:124:1, col:87> col:7 __ESBMC_overflow_uaddl '_Bool (unsigned long, unsigned long, unsigned long *)'
| |-ParmVarDecl 0x4f07d88 <col:30, col:44> col:47 'unsigned long'
| |-ParmVarDecl 0x4f07e08 <col:49, col:63> col:66 'unsigned long'
| `-ParmVarDecl 0x4f07eb0 <col:68, col:86> col:87 'unsigned long *'
|-FunctionDecl 0x4f08278 <line:125:1, col:103> col:7 __ESBMC_overflow_uaddll '_Bool (unsigned long long, unsigned long long, unsigned long long *)'
| |-ParmVarDecl 0x4f08068 <col:31, col:50> col:53 'unsigned long long'
| |-ParmVarDecl 0x4f080e8 <col:55, col:74> col:77 'unsigned long long'
| `-ParmVarDecl 0x4f08190 <col:79, col:102> col:103 'unsigned long long *'
|-FunctionDecl 0x4f084e8 <line:126:1, col:44> col:7 __ESBMC_overflow_ssub '_Bool (int, int, int *)'
| |-ParmVarDecl 0x4f08348 <col:29> col:32 'int'
| |-ParmVarDecl 0x4f083c8 <col:34> col:37 'int'
| `-ParmVarDecl 0x4f08448 <col:39, col:43> col:44 'int *'
|-FunctionDecl 0x4f087a0 <line:127:1, col:60> col:7 __ESBMC_overflow_ssubl '_Bool (long, long, long *)'
| |-ParmVarDecl 0x4f085b8 <col:30, col:35> col:38 'long'
| |-ParmVarDecl 0x4f08638 <col:40, col:45> col:48 'long'
| `-ParmVarDecl 0x4f08700 <col:50, col:59> col:60 'long *'
|-FunctionDecl 0x4f08a10 <line:128:1, col:76> col:7 __ESBMC_overflow_ssubll '_Bool (long long, long long, long long *)'
| |-ParmVarDecl 0x4f08870 <col:31, col:41> col:44 'long long'
| |-ParmVarDecl 0x4f088f0 <col:46, col:56> col:59 'long long'
| `-ParmVarDecl 0x4f08970 <col:61, col:75> col:76 'long long *'
|-FunctionDecl 0x4f08c80 <line:129:1, col:71> col:7 __ESBMC_overflow_usub '_Bool (unsigned int, unsigned int, unsigned int *)'
| |-ParmVarDecl 0x4f08ae0 <col:29, col:38> col:41 'unsigned int'
| |-ParmVarDecl 0x4f08b60 <col:43, col:52> col:55 'unsigned int'
| `-ParmVarDecl 0x4f08be0 <col:57, col:70> col:71 'unsigned int *'
|-FunctionDecl 0x4f08ef0 <line:130:1, col:87> col:7 __ESBMC_overflow_usubl '_Bool (unsigned long, unsigned long, unsigned long *)'
| |-ParmVarDecl 0x4f08d50 <col:30, col:44> col:47 'unsigned long'
| |-ParmVarDecl 0x4f08dd0 <col:49, col:63> col:66 'unsigned long'
| `-ParmVarDecl 0x4f08e50 <col:68, col:86> col:87 'unsigned long *'
|-FunctionDecl 0x4f09160 <line:131:1, col:103> col:7 __ESBMC_overflow_usubll '_Bool (unsigned long long, unsigned long long, unsigned long long *)'
| |-ParmVarDecl 0x4f08fc0 <col:31, col:50> col:53 'unsigned long long'
| |-ParmVarDecl 0x4f09040 <col:55, col:74> col:77 'unsigned long long'
| `-ParmVarDecl 0x4f090c0 <col:79, col:102> col:103 'unsigned long long *'
|-FunctionDecl 0x4f093d0 <line:132:1, col:44> col:7 __ESBMC_overflow_smul '_Bool (int, int, int *)'
| |-ParmVarDecl 0x4f09230 <col:29> col:32 'int'
| |-ParmVarDecl 0x4f092b0 <col:34> col:37 'int'
| `-ParmVarDecl 0x4f09330 <col:39, col:43> col:44 'int *'
|-FunctionDecl 0x4f09640 <line:133:1, col:60> col:7 __ESBMC_overflow_smull '_Bool (long, long, long *)'
| |-ParmVarDecl 0x4f094a0 <col:30, col:35> col:38 'long'
| |-ParmVarDecl 0x4f09520 <col:40, col:45> col:48 'long'
| `-ParmVarDecl 0x4f095a0 <col:50, col:59> col:60 'long *'
|-FunctionDecl 0x4f0a0d8 <line:134:1, col:76> col:7 __ESBMC_overflow_smulll '_Bool (long long, long long, long long *)'
| |-ParmVarDecl 0x4f09f38 <col:31, col:41> col:44 'long long'
| |-ParmVarDecl 0x4f09fb8 <col:46, col:56> col:59 'long long'
| `-ParmVarDecl 0x4f0a038 <col:61, col:75> col:76 'long long *'
|-FunctionDecl 0x4f0a348 <line:135:1, col:71> col:7 __ESBMC_overflow_umul '_Bool (unsigned int, unsigned int, unsigned int *)'
| |-ParmVarDecl 0x4f0a1a8 <col:29, col:38> col:41 'unsigned int'
| |-ParmVarDecl 0x4f0a228 <col:43, col:52> col:55 'unsigned int'
| `-ParmVarDecl 0x4f0a2a8 <col:57, col:70> col:71 'unsigned int *'
|-FunctionDecl 0x4f0a5b8 <line:136:1, col:87> col:7 __ESBMC_overflow_umull '_Bool (unsigned long, unsigned long, unsigned long *)'
| |-ParmVarDecl 0x4f0a418 <col:30, col:44> col:47 'unsigned long'
| |-ParmVarDecl 0x4f0a498 <col:49, col:63> col:66 'unsigned long'
| `-ParmVarDecl 0x4f0a518 <col:68, col:86> col:87 'unsigned long *'
|-FunctionDecl 0x4f0a828 <line:137:1, col:103> col:7 __ESBMC_overflow_umulll '_Bool (unsigned long long, unsigned long long, unsigned long long *)'
| |-ParmVarDecl 0x4f0a688 <col:31, col:50> col:53 'unsigned long long'
| |-ParmVarDecl 0x4f0a708 <col:55, col:74> col:77 'unsigned long long'
| `-ParmVarDecl 0x4f0a788 <col:79, col:102> col:103 'unsigned long long *'
`-FunctionDecl 0x4f0a908 </var/www/html/out/myesbmc5ee901fc7e3727.31341829.c:1:1, line:9:1> line:1:5 main 'int ()'**

**Comment by mikhailramalho** [comment]
These are the internally defined clang types + esbmc intrinsics. The list of esbmc intrinsics can be found here: https://github.com/esbmc/esbmc/blob/master/src/clang-c-frontend/clang_c_language.cpp#L258
