### ISSUE TITLE
WARNING:  no body for function __builtin_va_start

### ISSUE THREAD

**Issue by metamaterialsuit** [esbmc/esbmc#2194]
The code simply uses va_start and va_end. Based on looking at the output from goto2c, it appears an extern function declaration is created, and the function is invoked normally.

Does` the lack of a function body make the analysis unsound? I expect that these types of warnings are generally to alert users to provide source for the missing functions. In this case however, I have no idea what esbmc would expect, considering va_start appears to be tightly coupled to clang.

The command line is simply esbmc --incremental-bmc test.c

Furthermore, though this may be unrelated, incremental-bmc terminates with verification succeeded, solution found by the forward conditin, all states are reachable. k=1. That seems incorrect to me, and so I can't help but think it may be related.

ESBMC version: 7.7
Operating system: Ubuntu 24.10
Exact command line resulting in the issue: esbmc --incremental-bmc test.c
What behaviour did you expect: No warnings
What happened instead: Got warnings

**Comment by lucasccordeiro** [comment]
@metamaterialsuit: can you please share a small C program that exposes the issues mentioned above?

**Comment by metamaterialsuit** [comment]
Yes. sorry,  upon re-reading my issue this morning I realized it was much less clear than I felt it was last night.

void f(int a, int b, char * format, ...){
va_list args; 
va_start(args, format);
vprintf(format, args);
va_end(args);
}

Called from an otherwise empty main function.

**Comment by lucasccordeiro** [comment]
````CPP
#include <cstdio>
#include <cstdarg>

void f(int a, int b, char *format, ...)
{
    va_list args;
    va_start(args, format);
    vprintf(format, args);
    va_end(args);
}

int main()
{
    int x = 10, y = 20;
    char format[] = "Values: %d and %d\n";

    f(x, y, format, x, y); 

    return 0;
}
````

**Comment by lucasccordeiro** [comment]
@metamaterialsuit: could you please check out / test the current master version? If you find additional issues, please don't hesitate to let us know.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/2207.

**Comment by metamaterialsuit** [comment]
Thank you! I will give it a shot! 

EDIT: Is there no release that incorporates the fix? If not, I assume I'll have to build from source?

**Comment by intrigus-lgtm** [comment]
> Thank you! I will give it a shot!
> 
> EDIT: Is there no release that incorporates the fix? If not, I assume I'll have to build from source?

You can try the debug version produced by GitHub Actions if you don't want to build from source: https://github.com/esbmc/esbmc/actions/runs/12548118918
