### ISSUE TITLE
Concurrency flags in esbmc-wrapper

### ISSUE THREAD

**Issue by Anthonysdu** [esbmc/esbmc#2203]
I just noticed that there might be a mistake of concurrency flags in esbmc-wrapper:

ConcurrencySafety-MemSafety:       `--incremental-bmc`
ConcurrencySafety-NoOverflows:    `--k-induction`
ConcurrencySafety-Main:                  `--no-por --context-bound 3 --incremental-bmc`
NoDataRace-Main:                              `--no-por --context-bound 3 --incremental-bmc`

MemSafety and NoOverflows didn't disable the por or bound the context switch, and NoOverflows is using k-induction which is currently not supported for concurrency.

Are the flags particularly for those two categories?  I believe the wrapper just missed the concurrency flags for them.
@rafaelsamenezes @lucasccordeiro

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/2206.
