### ISSUE TITLE
floats-regression/nan test case failing in macOS 

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#228]
```
TEST: /Users/runner/runners/2.263.0/work/esbmc/esbmc/regression/floats-regression/nan
EXPECTED TO FIND: ['^VERIFICATION SUCCESSFUL$']

PROGRAM OUTPUT
ESBMC version 6.4.0 64-bit x86_64 macos
file main.c: Parsing
In file included from main.c:3:
In file included from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//esbmc_clang_headers/inttypes.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/inttypes.h:229:
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//esbmc_clang_headers/stdint.h:248:2: error: unterminated conditional directive
#ifndef __intptr_t_defined
 ^
```

**Comment by mikhailramalho** [comment]
What changed? It was working before.

**Comment by rafaelsamenezes** [comment]
I am not sure which commit gave the problem. For now, I will block merges that it does not pass all CI tests.

**Comment by mikhailramalho** [comment]
We need to fix this or revert the PR. 

A PR should not be merged if it breaks the regression.

**Comment by rafaelsamenezes** [comment]
> A PR should not be merged if it breaks the regression.

I agree, so it is blocked for now. So it will not happen again unless someone commits directly to master

> We need to fix this or revert the PR.

Sure. I do not have any clue on how to detect which commit broke this test case, so I do not think reverting is a good option. About fixing it, that's why I opened this issue.

**Comment by mikhailramalho** [comment]
Any update here?

**Comment by rafaelsamenezes** [comment]
Yes,

The latest master commit broke one more test case: https://github.com/esbmc/esbmc/commit/3b89013e7b0f1256635ba11f57bec9fa3e7f66d7

The one before it was ok: https://github.com/esbmc/esbmc/commit/f021f4fe041c71c00a321a1665a04f5715a1b6d1

I can think of two reasons why:

1. The action is unstable for external reasons. If this is the case I am unsure of how to proceed.

2. The macOS headers are being updated. If this is the case then we could force the usage of clang headers or take advantage of knowing what is working on the latest macOS releases.

Currently broken test cases:

- esbmc/github_213
- floats-regression/nan

@lucasccordeiro may I ask of you to run those tests and see if they are working in your machine? Please, add your macOS version as well.

**Comment by lucasccordeiro** [comment]
Both test cases work fine on my MacOS (Mojave v10.14.6)

* esbmc/github_213

$esbmc main.c --no-div-by-zero-check --force-malloc-success --context-bound 7 --state-hashing -Dldv_assume=__ESBMC_assume --floatbv --unlimited-k-steps --z3 --incremental-bmc --32 --no-pointer-check --no-bounds-check --error-label ERROR --32 > github_213.txt
[github_213.txt](https://github.com/esbmc/esbmc/files/4870094/github_213.txt)

* floats-regression/nan

$esbmc main.c --floatbv main.c > nan.txt
[nan.txt](https://github.com/esbmc/esbmc/files/4870157/nan.txt)

**Comment by mikhailramalho** [comment]
Working with the current master (d645fd464bef)
