### ISSUE TITLE
Ubdate ESBMC 

### ISSUE THREAD

**Issue by fatimahkj** [esbmc/esbmc#235]
Hi everyone, 

I already compiled ESBMC and it works fine. Now, I need to update it. From the build directory, I run ninja and this is what I gote. 

![Screenshot from 2020-07-02 17-39-41](https://user-images.githubusercontent.com/47563480/86471197-db18b500-bd34-11ea-9c3b-1d9f4b94a400.png)

Any idea of whats the problem might be? and how can I fix it? 
I run the dependencies command 
sudo apt-get update && sudo apt-get install build-essential git gperf libgmp-dev cmake bison curl flex gcc-multilib linux-libc-dev libboost-all-dev libtinfo-dev ninja-build python3-setuptools unzip wget

and the ninja again and I got 

ninja: no work to do.

**Comment by mikhailramalho** [comment]
It's not an error, ESBMC was built just fine (that's why you get the "no work to do" from ninja).

LLVM opens some library dynamic to avoid linking, that's why you are getting this message. Don't worry about it.
