### ISSUE TITLE
Question about symbols

### ISSUE THREAD

**Issue by vanderson-rocha** [esbmc/esbmc#238]
Guys, could you explain what would be a symbol of level0, level1 and level2? What would node_num be in a symbol?

Tks.

**Comment by mikhailramalho** [comment]
Sorry for the delay, I missed this message.

It's easier to explain by using the SSA indexes:
* `#`: different variable valuations at different points in the program.
* `@`: different pieces of variable storage, i.e., instances of the same lexical variable, but that have different locations in memory. The obvious example is when the same function is called twice, and it uses a variable `i`; two distinct `i` variables can exist at different locations (in the case of recursion, there will be multiple copies of `i`).
* `&`: different assignments in different multithreaded interleavings. One of the concurrency modes in ESBMC (schedule) encodes all program traces into the same SMT formula: each path through the program gets its ID number, which is put after & to distinguish variables.
* `!`: local variables in different threads. If a function runs in two different threads, then the variable i has to be distinguished.

The `level*` enums translation to the SSA indexes can be found in `irep2.cpp:628`, method `symbol_data::get_symbol_name()`:
```
std::string symbol_data::get_symbol_name() const
{
  switch(rlevel)
  {
  case level0:
    return thename.as_string();
  case level1:
    return thename.as_string() + "?" + i2string(level1_num) + "!" +
           i2string(thread_num);
  case level2:
    return thename.as_string() + "?" + i2string(level1_num) + "!" +
           i2string(thread_num) + "&" + i2string(node_num) + "#" +
           i2string(level2_num);
  case level1_global:
    // Just return global name,
    return thename.as_string();
  case level2_global:
    // Global name with l2 details
    return thename.as_string() + "&" + i2string(node_num) + "#" +
           i2string(level2_num);
  default:
    std::cerr << "Unrecognized renaming level enum" << std::endl;
    abort();
  }
}
```

We could probably get rid of some of theses enums if we try hard enough.
