### ISSUE TITLE
Shall we add support for Clang 10.0 in ESBMC? 

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#241]
Shall we add support for Clang 10.0 in ESBMC? 

It is already available at https://releases.llvm.org/download.html.

**Comment by mikhailramalho** [comment]
Is there any specific feature you need from version 10? 

If there isn't, I suggest we wait for version 11, which should have support for ExtInt (partially implemented in branch ExtInt.

**Comment by lucasccordeiro** [comment]
We can wait for version 11.
