### ISSUE TITLE
ESBMC faced a problem, "Boolector error encountered"

### ISSUE THREAD

**Issue by kaled-alshmrany** [esbmc/esbmc#301]
I have run ESBMC on the program "Loops/string-2.c" in Test-Comp benchmarks and I found this problem "Boolector error encountered [boolector] boolector_slice: 'upper' must not be >= width of 'exp'". 

Here is the output:
[output.txt](https://github.com/esbmc/esbmc/files/5440248/output.txt)

Here is the program:
[string-2.i.txt](https://github.com/esbmc/esbmc/files/5440285/string-2.i.txt)

**Comment by mikhailramalho** [comment]
fixed by PR #320
