### ISSUE TITLE
witness validation for SV-COMP 2021

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#303]
@ericksonalves 

As we talked, could you be responsible for the part of witness validation concerning ESBMC in SV-COMP 2021?

The ESBMC results can be obtained at: https://sv-comp.sosy-lab.org/2021/results/results-verified/iZeCa0gaey.html

The task is to check the generation of our witnesses to identify which elements are missing from our graphml.

In particular, you can check if we are not printing the value of any variable. You can also use the --no-slice option to find out if we need to add more assignments to the witness.

The class that implements our witness is this:

https://github.com/esbmc/esbmc/blob/master/src/goto-symex/witnesses.h
https://github.com/esbmc/esbmc/blob/master/src/goto-symex/witnesses.cpp

As you have already had experience using CPAchecker to validate our witness, I believe that you will have an excellent potential to identify failures and fix them.

Let us know if you have any questions.

**Comment by lucasccordeiro** [comment]
@ericksonalves: we could also check whether this commit https://github.com/esbmc/esbmc/commit/74e3c2b412ba896cde0894b92eedcf6f1427db88 has introduced problems to our witness.

**Comment by mikhailramalho** [comment]
@lucasccordeiro, can we close this one?

**Comment by lucasccordeiro** [comment]
Yes. We have already fixed our witness. This PR https://github.com/esbmc/esbmc/pull/320 implements the improvements.
