### ISSUE TITLE
Extend Clang builtin functions in ESBMC

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#313]
Clang supports a number of builtin library functions with the same syntax as GCC like `__builtin_nan`, `__builtin_constant_p`, `__builtin_choose_expr`, `__builtin_types_compatible_p`, `__sync_fetch_and_add`, etc. 

However, ESBMC does not handle builtin functions in its analysis.

As an example, the builtin function ``__builtin_unreachable()`` that is used in the following code:

```
int main() {
    __builtin_unreachable();
   return 0; 
}
```

Causes ESBMC to generate the following warning message:

**** WARNING: no body for function __builtin_unreachable

**Comment by mikhailramalho** [comment]
We already have an issue for builtins: https://github.com/esbmc/esbmc/issues/42

Closing as duplicated.
