### ISSUE TITLE
Conversion of unsupported clang cast operator: "ToUnion" to expression

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#314]
The ESBMC frontend does not like the conversion from a union type.

Consider this C code:

```
typedef union{
    unsigned long long raw64;
    struct {
        unsigned raw32lo;
        unsigned raw32hi;
    };
    struct {
        unsigned long long    field1:1;
        unsigned long long    field2:1;
    };
} union_t;


unsigned long long foo(unsigned addr) {
    return addr + 100;
}

int main() {
   union_t x = (union_t) foo(100);    
   return 0; 
}
```

ESBMC command line which recreates the issue:
$ esbmc test_cast_to_union.c --function main

ESBMC version 6.4.0 64-bit x86_64 linux
file test_cast_to_union.c: Parsing
Converting
Conversion of unsupported clang cast operator: "ToUnion" to expression
CStyleCastExpr 0x445d0c0 'union_t':'union_t' <ToUnion>
`-CallExpr 0x445d070 'unsigned long long'
  |-ImplicitCastExpr 0x445d058 'unsigned long long (*)(unsigned int)'
<FunctionToPointerDecay>
  | `-DeclRefExpr 0x445cfe8 'unsigned long long (unsigned int)'
Function 0x445cd10 'foo' 'unsigned long long (unsigned int)'
  `-ImplicitCastExpr 0x445d098 'unsigned int' <I
ntegralCast>
    `-IntegerLiteral 0x445d008 'int' 100
CONVERSION ERROR

**Comment by mikhailramalho** [comment]
Does it work as a bitcast or a typecast?

**Comment by lucasccordeiro** [comment]
Typecast.

**Comment by mikhailramalho** [comment]
This is a gcc extension: https://gcc.gnu.org/onlinedocs/gcc/Cast-to-Union.html

The implementation requires changing `clang_c_adjust_*.cpp` to find the correct member to create the assingment.
