### ISSUE TITLE
Conversion of unsupported clang type: "Vector"

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#315]
The ESBMC frontend does not support the conversion of clang type "Vector".

```
#include <stdio.h>

typedef int v4si __attribute__((__vector_size__(16)));
v4si vsi = (v4si){1, 2, 3, 4};

int main() {
    
   return 0; 
}
```
ESBMC command that was used:
$ esbmc test_vector.c --function main

ESBMC version 6.4.0 64-bit x86_64 linux
file test_vector.c: Parsing
Converting
Conversion of unsupported clang type: "Vector
VectorType 0x445b030 '__attribute__((__vector_size__(4 * sizeof(int)))) int' 4
`-BuiltinType 0x4358b60 'int'
CONVERSION ERROR

**Comment by mikhailramalho** [comment]
This should be easily implemented in the frontend, however, this will require changes to every other part of ESBMC. The problematic one would be to implement it on the SMT backend.

CBMC has a similar data type.
