### ISSUE TITLE
[Juliet_Tests] dereference failure: array bounds violated

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#331]
Another juliet error:
```
struct _twoIntsStruct {
  int intOne;
  int intTwo;
};

typedef struct _twoIntsStruct twoIntsStruct;

int main() {
  twoIntsStruct *dataBuffer = malloc(16UL);
  (dataBuffer + 1)->intOne = 1;
}
```
cmd: `esbmc main1.c --force-malloc-success`

The problem here is that ESBMC calculates the size of an object and the alignment/padding, so `(dataBuffer + 1)` ends up with a 16 bytes offset.

The fix here is to rewrite the sizeof calculation, which might affect everything from handling bitfields to alignment checks.

**Comment by lucasccordeiro** [comment]
@ericksonalves: could you please investigate this issue in ESBMC?

**Comment by ericksonalves** [comment]
Hi,

Sure, I will investigate it.

**Comment by lucasccordeiro** [comment]
@ericksonalves: do you have news about this issue?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/commit/d4c0cf85a3df448a66f0c1cf68d4429cc3864f8c.
