### ISSUE TITLE
How to use ESBMC-GPU Scanner and Parser?

### ISSUE THREAD

**Issue by Helderjfl** [esbmc/esbmc#341]
Hi,

I'm looking for a Scanner and Parser for CUDA, I saw that ESBMC-GPU have one, but I'm trying to use just that part of ESBMC and I can't get it to work.
I saw that both scanner and parser are at "ansi-c" folder, I used make command to build, used "flex++ scanner.lpp -lfl" to create "lex.yy.cc" and "g++ lex.yy.cc -I../util/ -I../ -I./" to compile, but I'm getting some errors:

scanner.lpp: In function ‘void make_integer(std::string)’:
scanner.lpp:61:30: error: ‘yytext’ was not declared in this scope; did you mean ‘yy_nxt’?
61 | yyansi_clval.expr->cformat(yytext);
| ^~~~~~
| yy_nxt
scanner.lpp: In function ‘void ansi_c_scanner_init()’:
scanner.lpp:155:3: error: ‘YY_FLUSH_BUFFER’ was not declared in this scope
155 | YY_FLUSH_BUFFER;
| ^~~~~~~~~~~~~~~
lex.yy.cc:127:16: error: ‘yy_start’ was not declared in this scope; did you mean ‘va_start’?
127 | #define BEGIN (yy_start) = 1 + 2 *
| ^~~~~~~~
scanner.lpp:156:3: note: in expansion of macro ‘BEGIN’
156 | BEGIN(0);

I want to use both the scanner and parser output, but I'm not managing to make it work.
Can someone help me?

Thanks.

**Comment by lucasccordeiro** [comment]
Hi Helder,

Many thanks for your interest in the ESBMC-GPU project.

Unfortunately, we didn't continue the development of ESBMC-GPU. The latest version of the sources used in our papers are available at:

https://github.com/ssvlab/esbmc-gpu-source

Did you try to use the version of the above repository?

Fortunately, we have recently been awarded a research grant (https://enncore.github.io/), where we'll resume the development of ESBMC-GPU very soon. 

We plan to use the clang C/C++ frontend to build the new version of ESBMC-GPU.

Please let me know if you have further questions.

Best,
Lucas

**Comment by lucasccordeiro** [comment]
This issue seems to be obsolete. In particular, there was not further follow-up here.
