### ISSUE TITLE
Our slicer is cutting too many instructions when printing the counterexample

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#353]
ESBMC does not print any assignment in the counterexample when verifying this C program:

$esbmc main.c 

```C
#include <stdio.h>

int arr[100];

void foo(unsigned int *p){
    
  //if (!p)
  //    return;
  
    *p = 5;
    arr[0] = 5;
    arr[100] = 7;
}

int main() {
   
   unsigned int *p = NULL;
   foo(p);

   return 0; 
}
```

If we call ESBMC with `--no-slice`, then ESBMC shows:

```
Building error trace

Counterexample:

State 1 file test_basic_checks.c line 3 thread 0
----------------------------------------------------
  arr = ARRAY_OF(0)

State 2 file test_basic_checks.c line 17 function main thread 0
----------------------------------------------------
  p = 0

State 3 file test_basic_checks.c line 10 function foo thread 0
----------------------------------------------------
Violated property:
  file test_basic_checks.c line 10 function foo
  dereference failure: NULL pointer
```

I believe our slicer should still print this assignment since they are relevant to show that we have a NULL pointer dereference.

**Comment by lucasccordeiro** [comment]
This issue also happens if we use `--no-propagation`.

**Comment by mikhailramalho** [comment]
>
>  I believe our slicer should still print this assignment since they are
> relevant to show that we have a NULL pointer dereference.
>
>
>
The slicer doesn't know what is "relevant" or not in the program, it only
cares about removing assignments. If you look at the cex path, you only
have constants, so everything is propagated and sliced away.

When building the cex, however, all the SSA are still there, it is only a
matter of teaching esbmc what is relevant to include in a cex.

-- 

Mikhail Ramalho.

**Comment by lucasccordeiro** [comment]
This issue is obsolete since we have a new option that shows the full counterexample while hiding the internal symbols (see https://github.com/esbmc/esbmc/pull/373).
