### ISSUE TITLE
Add a complementary option to remove all intrisic variables (compact-trace)

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#369]
We need an option to complement `--no-slice` to hide the intrinsic values and methods on the counterexample

**Comment by lucasccordeiro** [comment]
@mikhailramalho and @rafaelsamenezes: I have created this PR https://github.com/esbmc/esbmc/pull/373 to all non-user defined variables assignments.

Could you please review it?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/373.
