### ISSUE TITLE
Data structure padding problems

### ISSUE THREAD

**Issue by shmarovfedor** [esbmc/esbmc#379]
I found a problem with data structure alignment. ESBMC reports "verification failure" for the code below (which is technically correct because SIZE=5). However, when compiled, data.str.p1 will be automatically padded to the nearest 4 bytes. And so data.str.p1 will be allocated 8 bytes. Hence, this code should be bug-free.

```
#include<stdlib.h>
#include<stdio.h>
#define SIZE 5
void main(void)
{
    union {
        int *p0;
        struct {
            char p1[SIZE];
            int p2;
        } str;
    } data;
    data.p0 = (int*) malloc(sizeof(int*));
    data.str.p2 = 1;
    free(data.p0);
}
```
 Although this problem has been already discussed in #378 , I opened a separate issue so we can link to it.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/commit/6bfb3e7367788b3656c09d8ca47b9fe597c08978.
