### ISSUE TITLE
[boolector] boolector_sll: bit-width of 'e1' must be equal to log2(bit-width of 'e0')

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#384]
esbmc file.c --overflow-check

```C
#include <stdint.h>
main() { 0 << UINT64_C(0); }
```

If we use the clang pre-processor, then we get:

```C
main() { 0 << (0ULL); }
```

**Comment by mikhailramalho** [comment]
Hi Lucas, this should fix the issue:

[0001-Cast-the-2nd-operand-of-bvshl-if-there-is-a-width-mi.patch.txt](https://github.com/esbmc/esbmc/files/5988696/0001-Cast-the-2nd-operand-of-bvshl-if-there-is-a-width-mi.patch.txt)

**Comment by lucasccordeiro** [comment]
Thanks, @mikhailramalho. 

This PR, which includes your patch, should fix the problem: https://github.com/esbmc/esbmc/pull/385.

As soon as CI passes, I'll merge it into the master.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/385.
