### ISSUE TITLE
ESBMC debug build?

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#410]
Is there a debug build of ESBMC that is able to show all frame variables without optimizing? 

The build instructions ([here](https://github.com/esbmc/esbmc/blob/master/BUILDING.md)) appears to create an optimized build of ESBMC.  When examining the back trace, some key variables are not available: 

```
(language_filet &) lf = <variable not available>

(languaget &) language = <variable not available>
```

**Comment by mikhailramalho** [comment]
Hi @kunjsong01,

You have a few options to see the full counter-example:
1. `--no-slice`: do not remove unused, constant folded, and/or simplified away assignments in a counter-example path. Note that this does not show all the assignments in the program, only the ones in a path to a bug.
2. `--no-simplify`: disable internal simplifications. Keep stuff like `1+1` or `int a; (int*)(void*)&a` in the counter-example. If the program contains loops and you use this option, you might need to set the max loop unwinds (`--unwind X`) or use `--incremental-bmc`.
3. `--no-propagation`: disables constant folding.
4. `--compact-trace`: hide some internal variables when using `--no-slice`. 

Options 1-3 can impact the tool's performance in unpredicted ways, and `--no-simplify` can particularly cause massive increases in solving time.

**Comment by kunjsong01** [comment]
I'm not a CMAKE expert but the following steps work as expected on my laptop: 
1. If you have a previous release build, run `ninja clean` in esbmc/build directory
2. rm directory esbmc/build
3. rm directory esbmc/../release
4. Add `-DCMAKE_BUILD_TYPE=Debug ` to the CMAKE build command and re-build everything. 

Then esbmc binary should be the debug build showing all frame variables as evidenced by the output below: 
```
(lldb) p lf
(language_filet) $2 = {
  modules = size=0 {}
  language = 0x000000010a4043a0
  filename = "hello_world.c"
}
```

**Comment by mikhailramalho** [comment]
Oh, I thought you were asking something else. Indeed, you need to build ESBMC in debug mode to keep this information.

Most of the internal types (`exprt`, `expr2tc`) can be accessed using the method dump (e.g., `a->dump()`).

**Comment by kunjsong01** [comment]
Hi @mikhailramalho ,

Thanks a lot for the nice explanations of the advanced usage of BMC related options. I reckon I will definitely use some of them in the future when delving into the backend. 

Sorry for the confusion. I should have phrased my question in a more clear way. 

> Most of the internal types (exprt, expr2tc) can be accessed using the method dump (e.g., a->dump()).

Thanks again for this tip!

**Comment by kunjsong01** [comment]
This issue is now resolved.
