### ISSUE TITLE
Port CBMC unit tests to ESBMC

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#413]
CBMC contains lots of unit tests using the `catch` framework. Most of those tests could be reused at ESBMC with minor changes. https://github.com/diffblue/cbmc/tree/develop/unit

Not only that would create a good base suite, it would be helpful to create [property-based](https://github.com/emil-e/rapidcheck) tests and fuzzing targets.

Also, although we already use Boost.Test I wouldn't mind changing it to catch2 since it is way simpler to understand.

**Comment by lucasccordeiro** [comment]
Fine by me.
