### ISSUE TITLE
Some questions and build problems regarding the old frontend (ansi-c?)

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#423]
Hi ESBMC developers, 

I'm trying to build ESBMC with the old frontend by adding the following argument in `cmake` command line: 

```
-DENABLE_OLD_FRONTEND=On 
```

Questions: 
1). Is the "old frontend" referring to `src/ansi-c`?

2). Is the old frontend more self-contained than the new frontend aka. src/clang-c-frontend? 
And by "self-contained" I mean that NO external dependencies on other compiler's frontend (unlike the `clang-c-frontend` that has lots of dependencies on clang11's data structures and functions)

3). When building the old frontend, I got the error message shown below. I don't know what went wrong.... could anyone shed some light please?
 
```
Undefined symbols for architecture x86_64:
  "_pthread_buf", referenced from:
      _headers in libansiccpp.a(hooks.c.o)
  "_pthread_buf_size", referenced from:
      _headers in libansiccpp.a(hooks.c.o)
  "_pthreadtypes_buf", referenced from:
      _headers in libansiccpp.a(hooks.c.o)
  "_pthreadtypes_buf_size", referenced from:
      _headers in libansiccpp.a(hooks.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I used the build command below: 
```
cd esbmc && \
mkdir build && \
cd build && \
cmake .. -GNinja -DBUILD_TESTING=On \
-DCMAKE_BUILD_TYPE=Debug \
-DENABLE_OLD_FRONTEND=On \
-DLLVM_DIR=$PWD/../../clang11 \
-DENABLE_REGRESSION=On -DBUILD_STATIC=On \
-DBoolector_DIR=$PWD/../../boolector-release \
-DZ3_DIR=$PWD/../../z3 \
-DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat \
-DENABLE_YICES=ON -DYices_DIR=$PWD/../../yices \
-DC2GOTO_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release
```
followed by: 
```
cmake --build . && ninja install
```

**Comment by rafaelsamenezes** [comment]
Hi @kunjsong01 

> 1). Is the "old frontend" referring to src/ansi-c

To both `src/ansi-c` and `src/cpp`

> 2). Is the old frontend more self-contained than the new frontend aka. src/clang-c-frontend?

Yes, AFAIK the only "external dependency" are flex and bison.

> 3). When building the old frontend, I got the error message shown below. I don't know what went wrong.... could anyone shed some light please?

This looks like an issuein the flail script (probably at cmake level).

Are you sure that you are using the latest master commit? I've submitted a patch for this same issue a couple of weeks ago. @lucasccordeiro could you try to reproduce it on macOS?

**Comment by kunjsong01** [comment]
Hi @rafaelsamenezes ,

Thanks a lot for your answers. 
> Are you sure that you are using the latest master commit?
I'm now able to build with the old frontend using latest master commit (c3e9fc47e9). The problem only happens with the old frontend. 

### Problem: 
However, it is still using `clang-c-frontend` although I used "--old-frontend" when running esbmc binary. **The program is actually calling clang_c_languaget::parse and clang_c_languaget::typecheck.  I suppose it should be using the functions in src/ansi-c/ansi_c_language.cpp, isn't it?** 

I'm not sure what I've done wrong... Am I missing anything important in the build and run commands below?  

Cmake config command: 
```
cd esbmc && \
mkdir build && \
cd build && \
cmake .. -GNinja -DBUILD_TESTING=On \
-DCMAKE_BUILD_TYPE=Debug \
-DENABLE_OLD_FRONTEND=On \
-DLLVM_DIR=$PWD/../../clang11 \
-DENABLE_REGRESSION=On -DBUILD_STATIC=On \
-DBoolector_DIR=$PWD/../../boolector-release \
-DZ3_DIR=$PWD/../../z3 \
-DENABLE_MATHSAT=ON -DMathsat_DIR=$PWD/../../mathsat \
-DENABLE_YICES=ON -DYices_DIR=$PWD/../../yices \
-DC2GOTO_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release
```

Run command: 
```
./esbmc --old-frontend hw.c
```

### P.S.
I removed `-DClang_DIR` and just added `-DENABLE_OLD_FRONTEND=On` in the `cmake` command. But I didn't remove `-DLLVM_DIR=...`, because if I remove LLVM_DIR `cmake` will report the error: 
```
CMake Error at scripts/cmake/FindLLVM.cmake:15 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:82 (include)
```

**Comment by kunjsong01** [comment]
The problem was caused by wrong index `mode` as in `mode_table[mode].new_language();`

When "old-frontend" is enabled, the `mode` is incremented by 1,  pointing to `LANGAPI_HAVE_MODE_CLANG_CPP`, rather than `LANGAPI_HAVE_MODE_C`. Then we get an object `clang_cpp_languaget` returned by languaget *new_clang_cpp_language(). 

In the mode_table[] array: 
```
  3 const mode_table_et mode_table[] = {
  4   LANGAPI_HAVE_MODE_CLANG_C,
  5   LANGAPI_HAVE_MODE_CLANG_CPP,
  6 #ifdef ENABLE_OLD_FRONTEND
  7   LANGAPI_HAVE_MODE_C,
  8   LANGAPI_HAVE_MODE_CPP,
  9 #endif
 10   LANGAPI_HAVE_MODE_END};
```

When using old-frontend, I believe what we really want is `LANGAPI_HAVE_MODE_C`. 
I fixed this problem using the following patch: 
```
--- a/src/langapi/language_ui.cpp
+++ b/src/langapi/language_ui.cpp
@@ -53,7 +53,10 @@ bool language_uit::parse(const std::string &filename)
   }

   if(config.options.get_bool_option("old-frontend"))
-    mode++;
+  {
+    //mode++;
+    mode = mode + 2;
+  }
```

However, this patch only partially fixed the problem. Now I'm encountering a new problem in goto translation when using old-frontend: 
```
ESBMC version 6.7.0 64-bit x86_64 macos
file hw.c: Parsing
Converting
Generating GOTO Program
error: function `c:@F@pthread_start_main_hook' not found
libc++abi.dylib: terminating with uncaught exception of type int
Process 6644 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff203ac462 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff203ac462 <+10>: jae    0x7fff203ac46c            ; <+20>
    0x7fff203ac464 <+12>: movq   %rax, %rdi
    0x7fff203ac467 <+15>: jmp    0x7fff203a66a1            ; cerror_nocancel
    0x7fff203ac46c <+20>: retq
Target 0: (esbmc) stopped.
```
The new problem is caused by the exception below: 
```
215   if(goto_convert_functions.get_error_found())
216     throw 0;
```

I'm now looking into this bug ...

**Comment by kunjsong01** [comment]
**Cause and Fix:** 
The problem in last comment is caused by unmatch symbol identifiers (`pthread_start_main_hook` vs. `c:@F@pthread_start_main_hook`). This is confirmed by the experiment below: 
I compared the symbol names in the symbol_list generated by ansi-c and clang-c frontend. 
```
safe_logs> ls
ansi-c.failed-symbol.log  ansi-c.log                clang-c.failed-symbol.log clang-c.log
safe_logs> egrep "c:@F@pthread_start_main_hook" ansi-c.log
                  * identifier: c:@F@pthread_start_main_hook
error: function `c:@F@pthread_start_main_hook' not found
safe_logs> egrep "pthread_start_main_hook" ansi-c.log
Symbol......: pthread_start_main_hook
Base name...: pthread_start_main_hook
                  * identifier: c:@F@pthread_start_main_hook
error: function `c:@F@pthread_start_main_hook' not found
safe_logs> egrep "c:@F@pthread_start_main_hook" clang-c.log
Symbol......: c:@F@pthread_start_main_hook
                  * identifier: c:@F@pthread_start_main_hook
safe_logs>
```
The new clang-c frontend uses `c:@F@pthread_start_main_hook`. But the old ansi-c frontend still uses `pthread_start_main_hook`. 

This is now fixed by the patch: 
```
diff --git a/src/ansi-c/c_main.cpp b/src/ansi-c/c_main.cpp
index bc242b4b5..d4a29bb1f 100644
--- a/src/ansi-c/c_main.cpp
+++ b/src/ansi-c/c_main.cpp
@@ -300,10 +300,10 @@ bool c_main(

   code_function_callt thread_start_call;
   thread_start_call.location() = symbol.location;
-  thread_start_call.function() = symbol_exprt("c:@F@pthread_start_main_hook");
+  thread_start_call.function() = symbol_exprt("pthread_start_main_hook");
   code_function_callt thread_end_call;
   thread_end_call.location() = symbol.location;
-  thread_end_call.function() = symbol_exprt("c:@F@pthread_end_main_hook");
+  thread_end_call.function() = symbol_exprt("pthread_end_main_hook");
```
After applying this patch, the old fronend is back to work! :smiley:
I'll create a pull request to submit a single patch to fix the old fronend.

**Comment by kunjsong01** [comment]
closing this ticket as the questions have been answered and got a workaround for old frontend.
