### ISSUE TITLE
Bug in the stack-limit option

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#444]
Bug reported by an ESBMC user:

Below is a simple test case of a main function that allocates a local array 100 elements of int type, i.e. of size 100 x 4 = 400 bytes, However, when we run ESBMC with a stack limit of 3000 bytes it is still failing as shown below.

```C
int main() {
  int arr[100];

  return 0;
}
```
 
$ esbmc test_stack_limit.c --stack-limit 3000

``` 
Counterexample:
 
State 1 file test_stack_limit.c line 5 function main thread 0
----------------------------------------------------
Violated property:
  file test_stack_limit.c line 5 function main
  Stack limit property was violated when declaring arr
 
VERIFICATION FAILED
```

**Comment by mikhailramalho** [comment]
I think the stack limit is being calculated in bits, not in bytes.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: you're correct. We compute in bits, but the command-line option says byes. So I created this PR just to update the command-line: https://github.com/esbmc/esbmc/pull/445.
