### ISSUE TITLE
Replace couts and cerr with messaget calls

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#450]
ESBMC has a lot of calls using `std::cout` and `std::cerr`, we should use the messaget interface which provides more control of the output level and destination

**Comment by mikhailramalho** [comment]
Duplicate of https://github.com/esbmc/esbmc/issues/174?

**Comment by rafaelsamenezes** [comment]
> Duplicate of #174?

Somewhat, I think that this is the first step to solve that. This issue objective is to isolate cout and cerr calls into a messaget specialization, it shouldn't add fmt.
