### ISSUE TITLE
Missing ctype.h 

### ISSUE THREAD

**Issue by christinaburge** [esbmc/esbmc#453]
I've run into an error building ESBMC, specifically:

'ctype.h' file not found

When I look in the folder where I would guess it should be (/esbmc/src/c2goto/library), it is indeed missing.

I am running MacOS 11.4 (Big Sur)

I followed the instructions at https://github.com/esbmc/esbmc/blob/master/BUILDING.md, and everything looks fine up to :

`cmake --build . && ninja install`

When I execute the above command, the process completes up to :

`file /Users/chrbur02/ESBMC_Project/esbmc/src/c2goto/library/ctype.c: Parsing
/Users/chrbur02/ESBMC_Project/esbmc/src/c2goto/library/ctype.c:1:10: fatal error: 'ctype.h' file not found
#include <ctype.h>
         ^~~~~~~~~
PARSING ERROR
[456/509] Building CXX object src/clan...pfrontend.dir/clang_cpp_language.cpp.o
ninja: build stopped: subcommand failed.`

**Comment by mikhailramalho** [comment]
You're probably missing setting `C2GOTO_INCLUDE_DIR`. We usually warning users about that in macOS at config time, could you check it? 

@rafaelsamenezes, since we detect it during config time, can't we simply include the variable to compile on macOS? I would prevent such headaches for our users.

**Comment by christinaburge** [comment]
Yes, echo $C2GOTO_INCLUDE_DIR draws a blank. What should I set this to?

**Comment by mikhailramalho** [comment]
During config time (e.g., `cmake <path-to-esbmc>`), cmake should print the dir it found, something like: `Multi arch found in foobar, please set -DC2GOTO_INCLUDE_DIR=foobar`.

It should work by doing `cmake <path-to-esbmc> -DC2GOTO_INCLUDE_DIR=foobar`

**Comment by christinaburge** [comment]
Wait, I made a mistake! I did not set up Bitwuzla (I don't know how I missed that requirement).  This now gets you as far as 

`[484/509] Building CXX object unit/big...Files/biginttest.dir/bigint.test.cpp.o
ninja: build stopped: subcommand failed`

It fails for the same reason though, 'ctype.h' file not found.

The `-DC2GOTO_INCLUDE_DIR` flag is actually set as part of the instructions, and the command appears to complete just fine. This is the command (from the instructions):

`cd esbmc && mkdir build && cd build && cmake .. -GNinja -DBUILD_TESTING=On -DENABLE_REGRESSION=On -DBUILD_STATIC=On -DClang_DIR=$PWD/../../clang11 -DLLVM_DIR=$PWD/../../clang11 -DBoolector_DIR=$PWD/../../boolector-release -DZ3_DIR=$PWD/../../z3 -DENABLE_MATHSAT=On -DMathsat_DIR=$PWD/../../mathsat -DENABLE_YICES=ON -DYices_DIR=$PWD/../../yices -DC2GOTO_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ -DBitwuzla_DIR=$PWD/../../bitwuzla-release -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../release`


 I have attached the output.
[output.log](https://github.com/esbmc/esbmc/files/6671768/output.log)

**Comment by rafaelsamenezes** [comment]
> Wait, I made a mistake! I did not set up Bitwuzla (I don't know how I missed that requirement).

It shouldn't matter, you should be able to build ESBMC without any solvers.

> I have attached the output.

The CMake output looks ok. Maybe you are missing the xcode?

Could you check if the folder `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/` contains the `ctype.h`?

**Comment by lucasccordeiro** [comment]
I get the following with this command:

```
ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ | grep ctype.h | wc -l
       5
```

@christinaburge: maybe Xcode might be missing on your MacOS.

**Comment by mikhailramalho** [comment]
From the log, she does seem to have the sdk installed:
```
-- Multiarch include for c2goto: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/. You may want to override C2GOTO_INCLUDE_DIR
```

Maybe it's missing 32 bits libs?

Also, if it's only testing that's failing, you can disable testing by `-DBUILD_TESTING=OFF`

**Comment by rafaelsamenezes** [comment]
> From the log, she does seem to have the sdk installed

The CMake scritps does not check if the `ctype.h` is present and neither if the folder itself exists. I've opened an issue for this: https://github.com/esbmc/esbmc/issues/454

**Comment by mikhailramalho** [comment]
> > From the log, she does seem to have the sdk installed
> 
> The CMake scritps does not check if the `ctype.h` is present and neither if the folder itself exists. I've opened an issue for this: #454

What do you mean by "if the folder itself exists"? Then why it prints this message "-- Multiarch include for c2goto: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/. You may want to override C2GOTO_INCLUDE_DIR"?

And it shouldn't check if ctype.h exists, it should check if the 32 bits multi-arch headers/libs are present.

**Comment by christinaburge** [comment]
Hi All,

 I have tried setting -DBUILD_TESTING=OFF, but that does not help. I also have xcode command line tools installed.

**Comment by lucasccordeiro** [comment]
@christinaburge: It seems that our building system is struggling to find the ctype.h file on your MacOS. 

May I ask you whether you could tell us in which directory is ctype.h installed?

Many thanks,
Lucas

**Comment by lucasccordeiro** [comment]
BTW, in my MacOS, it is located at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/`.

**Comment by christinaburge** [comment]
Could the problem be that I only have the command line tools and not the full version of xcode? I keep trying to get xcode from the app store and the download keeps failing, but let me see if I can get it via the command line.

**Comment by christinaburge** [comment]
Because I have the command line tools and not the full version of xcode, ctype.h is located for me at:

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include

I guess I just need to change the file path somewhere and everything should work.

**Comment by rafaelsamenezes** [comment]
> Because I have the command line tools and not the full version of xcode, ctype.h is located for me at:

Could you try replacing the flag c2goto flag with: 

`-DC2GOTO_INCLUDE_DIR=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`

**Comment by christinaburge** [comment]
Aha, that worked, thanks!

**Comment by lucasccordeiro** [comment]
Excellent, @christinaburge. Before I close this issue. Is there something that we could do to improve our documentation?

**Comment by christinaburge** [comment]
I guess just include the solution for those (like me) who don't have the full version of xcode, but it's likely that someone else would have spotted the flag they needed to change!
________________________________

**Comment by lucasccordeiro** [comment]
Thanks, @christinaburge.

I have just pushed some small update to our BUILDING instructions. Closed via https://github.com/esbmc/esbmc/commit/d2877de01e2c0297dc6b03d0cfdb24de65c1ba40.
