### ISSUE TITLE
pkg-config isn't on ubuntu by default

### ISSUE THREAD

**Issue by jmorse** [esbmc/esbmc#48]
I'm experimenting with what people will experience if they install ESBMC on a ubuntu VM by default. The answer is that autoconf acts weird, but I'm not sure it's our fault.

One problem though is that pkg.m4, which provides the ability to look up pkg-config config files, for example for python, doesn't seem to exist on a default ubuntu install unless you ask for it. This is an issue because m4 just won't expand the PKG_* macros, and it'll lead to a crash at configure time, which people typically aren't prepared for. It's difficult to work out the solution too.

There's some kind of magical invocation one can give m4 that tells it to not complete if certain macros remain undefined, we could use that to prevent future pain. This is very much low priority though.

**Comment by rafaelsamenezes** [comment]
I think this should be closed since esbmc is using CMake now
