### ISSUE TITLE
C++ Compatibility?

### ISSUE THREAD

**Issue by ParthGaneriwala** [esbmc/esbmc#489]
I have been looking into the verifier and I am getting continuous errors while running C++ code but it works for C code. I wanted to ask if it is sure that C++ code is verified because it says it does. Yes when I mean C++ code, its the object oriented part which is not working.

**Comment by lucasccordeiro** [comment]
@ParthGaneriwala: You could try out this version https://ssvlab.github.io/esbmc/benchmarks/stvr_2021_experiments.zip.

Our paper that describes this version is available at https://ssvlab.github.io/lucasccordeiro/papers/stvr2021.pdf.

**Comment by ParthGaneriwala** [comment]
Most of the files for ESBMC model checker are coming out to be 'Not Supported'. Is that an expected result for ESBMC?

**Comment by ParthGaneriwala** [comment]
====== SUBSUITE: inheritance ====== 

 ---- ch13_25 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- ch22_1 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- ch22_2 [FALSE INCORRECT] Wall Time: 0.240000s, CPU Time: 0.230000s, Memory: 32436KB
 ---- ch22_4 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast1 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast2_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6852KB
 ---- dynamic_cast3_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast4 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast4_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast5 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast5_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast6 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast_simple [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast_simple2 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- dynamic_cast_simple2_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast_simple3_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- dynamic_cast_simple_bug [FALSE] Wall Time: 0.030000s, CPU Time: 0.030000s, Memory: 10932KB
 ---- dynamic_cast_void [FALSE] Wall Time: 0.030000s, CPU Time: 0.030000s, Memory: 10928KB
 ---- inheritance-cbmc [TRUE] Wall Time: 0.130000s, CPU Time: 0.120000s, Memory: 19288KB
 ---- inheritance01 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance02 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance04 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance05 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance06 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance07 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance08 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance09 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance10 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance11 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance12 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance13 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- inheritance14 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- inheritance15 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- llbmc_multiple_inheritance [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- llbmc_multiple_inheritance-wrong [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- llbmc_virtual_inheritance [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- llbmc_virtual_inheritance-wrong [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- multiple_inheritance [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- multiple_inheritance_2 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- multiple_inheritance_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6852KB
 ---- polymorphism_abstract_base_class [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- polymorphism_common_error_1 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- polymorphism_common_error_2 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- polymorphism_common_error_3 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- polymorphism_common_error_4 [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- polymorphism_dynamic_allocation [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6852KB
 ---- polymorphism_pointer_to_base_class [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- polymorphism_virtual_members [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- single_inheritance [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6844KB
 ---- single_inheritance_bug [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB
 ---- z_inheritance [NOT SUPPORTED] Wall Time: 0.000000s, CPU Time: 0.000000s, Memory: 6848KB

**Comment by feliperodri** [comment]
@ParthGaneriwala Is the ESBMC binary in your path? If you take a look at the scripts, you can see how we call each tool
```c
#define ESBMC_RUN_COMMAND_BASE "/usr/bin/time -v timeout 900s esbmc 2>&1 main.cpp --z3 "
```
So the ESBMC binary must be in your path. Take a look at the README file as well.
```
###### Installation and Execution

* Copy the `esbmc-v2.1.0-linux-static-64` folder from the `tools` folder to your `$HOME` directory.

* Create a symbolic link to `esbmc-v2.1.0-linux-static-64/libraries` from your `$HOME` directory as follows:

cd $HOME
ln -s esbmc/libraries libraries

* Add the binary `esbmc` to your `.bashrc` as follows:

cd $HOME
vi .bashrc
export PATH=$PATH:$HOME/esbmc-v2.1.0-linux-static-64/bin
source .bashrc

* The binary provided in `esbmc-v2.1.0-linux-static-64/bin/` folder is for a 64-bits architecture.
```

**Comment by ParthGaneriwala** [comment]
> @ParthGaneriwala Is the ESBMC binary in your path? If you take a look at the scripts, you can see how we call each tool
> 
> ```c
> #define ESBMC_RUN_COMMAND_BASE "/usr/bin/time -v timeout 900s esbmc 2>&1 main.cpp --z3 "
> ```
> 
> So the ESBMC binary must be in your path. Take a look at the README file as well.
> 
> ```
> ###### Installation and Execution
> 
> * Copy the `esbmc-v2.1.0-linux-static-64` folder from the `tools` folder to your `$HOME` directory.
> 
> * Create a symbolic link to `esbmc-v2.1.0-linux-static-64/libraries` from your `$HOME` directory as follows:
> 
> cd $HOME
> ln -s esbmc/libraries libraries
> 
> * Add the binary `esbmc` to your `.bashrc` as follows:
> 
> cd $HOME
> vi .bashrc
> export PATH=$PATH:$HOME/esbmc-v2.1.0-linux-static-64/bin
> source .bashrc
> 
> * The binary provided in `esbmc-v2.1.0-linux-static-64/bin/` folder is for a 64-bits architecture.
> ```

Yes I have all the necessary binaries for all of the model checkers install in my $HOME directory which is why the confusion. 
I have reinstalled it and still the same issue. Although I am getting results for few of the C++ files. 

```
TRUE: 15
FALSE: 8
TRUE INCORRECT: 1
FALSE INCORRECT: 1
MEMORY OUT: 0
NOT SUPPORTED: 1488
TIMEOUT: 0
TOTAL TIME: Wall time = 9.44s, CPU time = 4.89s | MEMORY: 1.06861e+07 KB
```

**Comment by lucasccordeiro** [comment]
@feliperodri: Could you please take a look at this output?

**Comment by YuJing63** [comment]
I also try it strictly according to the tutorial, but it is close to the above results, and many do not support it

**Comment by YuJing63** [comment]
/stvr_2021_experiments/stvr_2021_experiments/data/benchmarks/stl/map/map_begin$ /usr/bin/time -v timeout 900s esbmc 2>&1 main.cpp --z3 --unwind 4 --no-unwinding-assertions -I ~/libraries/ --memlimit 14000000
ESBMC version 2.1.0 64-bit x86_64 linux
file main.cpp: Parsing
main.cpp:2: error: cannot find 'iostream'

**Comment by lucasccordeiro** [comment]
@xinyuguo1998: I can see from this output that ESBMC is unable to find the operational model of the C++ libraries. Can you double-check whether these OMs are available at ~/libraries/?

**Comment by YuJing63** [comment]
> @xinyuguo1998: I can see from this output that ESBMC is unable to find the operational model of the C++ libraries. Can you double-check whether these OMs are available at ~/libraries/?

Yes, when I added esbmc to the global variable, I did not modify the path of the library, so it failed. Thank you very much

**Comment by lucasccordeiro** [comment]
Is ESBMC working now?

**Comment by YuJing63** [comment]
> Is ESBMC working now?

yes，I tested that the data set you gave can be used normally, and my own C++ code can also be verified. Thank you very much.

**Comment by lucasccordeiro** [comment]
Excellent! I'll close this issue.  If you have further questions, please let us know.
