### ISSUE TITLE
Boost.Python.ArgumentError in callintercept.py

### ISSUE THREAD

**Issue by afilieri** [esbmc/esbmc#5]
Hi,

Thanks for your work on ESBMC. 

I was trying to run the python interface example but got an exception on my machine. Here are the details:

```
Traceback (most recent call last):
  File "/.../esbmc/python/examples/callintercept.py", line 66, in <module>
    esbmc.symex.slice(result.target)
Boost.Python.ArgumentError: Python argument types in
    None.None(equation)
did not match C++ signature:
    None(boost::shared_ptr<symex_target_equationt> {lvalue}, bool)
```

I am using Ubuntu 17.10 64bit. I have installed from the official Ubuntu repo, among the others dependencies:
- libboost-all-dev 1.62.0.1
- libboost-python1.62.0+dfsg-4build3

ESBMC has been configured with the following parameters:
`./configure --disable-werror --enable-esbmc --with-z3=<pathToZ3> CXXFLAGS="-ggdb3 -O0 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS" --enable-python --enable-libesbmc`

Any suggestions?

Thanks

**Comment by lucasccordeiro** [comment]
Hi Antonio,

The signature of the `slice` method has changed to `slice(boost::shared_ptr<symex_target_equationt> &eq, bool slice_assume);`, which now requires modifications to the Python API as well (https://github.com/esbmc/esbmc/blob/master/src/goto-symex/symex_python.cpp#L309). I suspect that there are other methods that have changed signature as well.

@jmorse and @mikhailramalho: Is there some chance to update this Python API to synchronise with recent changes to the code base?

Many thanks,
Lucas

**Comment by jmorse** [comment]
Hi,

It seems some of the equation API has been changed to use boost::shared_ptrs, and some of it hasn't, hence the breakage. These two patches

    https://jmorse.net/~jmorse/esbmc/py/diff.patch
    https://jmorse.net/~jmorse/esbmc/py/diff2.patch

ensure that a boost::shared_ptr wrapped equation gets passed into the relevant functions. The additional C++ mangling is to get around further shared_ptr creep.

**Comment by rafaelsamenezes** [comment]
Since [v6.2](https://github.com/esbmc/esbmc/tree/v6.2) we removed of using esbmc as a python module. I will close this for now.
