### ISSUE TITLE
Update the ESBMC documentation (Solidity verification)

### ISSUE THREAD

**Issue by ssvlab** [esbmc/esbmc#500]
@kunjsong01: could you please update our ESBMC website (https://ssvlab.github.io/esbmc/documentation.html) to describe how ESBMC can be used to verify solidity programs?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/ssvlab/ssvlab.github.io/commit/3c5134e9545510da4add6a3ac831519c03aa60b2.
