### ISSUE TITLE
Invalid floating-point counterexample

### ISSUE THREAD

**Issue by emanino** [esbmc/esbmc#513]
Hi all,
I have an issue running ESBMC on the following minimal example [bug_example.txt](https://github.com/esbmc/esbmc/files/7330463/bug_example.txt):

`int main()`
`{`
`	float x0 = nondet_float();`
`	float x1 = nondet_float();`
`	float x2 = nondet_float();`
`	float x3 = nondet_float();`
`	float x4 = nondet_float();`
`	float x5 = nondet_float();`
`	float x6 = nondet_float();`
`	float x7 = nondet_float();`

`	__ESBMC_assume((x0 >= -5.6e-01f) && (x0 <= -5.5e-01f));`
`	__ESBMC_assume((x1 >= +1.0e+00f) && (x1 <= +1.1e+00f));`
`	__ESBMC_assume((x2 >= -4.0e-01f) && (x2 <= -3.9e-01f));`
`	__ESBMC_assume((x3 >= +1.6e+00f) && (x3 <= +1.7e+00f));`
`	__ESBMC_assume((x4 >= -6.7e-01f) && (x4 <= -6.6e-01f));`
`	__ESBMC_assume((x5 >= +1.3e+00f) && (x5 <= +1.4e+00f));`
`	__ESBMC_assume((x6 >= -2.5e-01f) && (x6 <= -2.4e-01f));`
`	__ESBMC_assume((x7 >= -1.4e+00f) && (x7 <= -1.3e+00f)); `

`	float y = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7;`

`	__ESBMC_assert(y >= +1.1e-02, "Output too low");`
`	__ESBMC_assert(y <= +1.3e-02, "Output too high");`

`	return 0;`
`}`

ESBMC gives me the correct outcome (verification failed) but not a valid counterexample:

<img width="480" alt="bug" src="https://user-images.githubusercontent.com/40175301/136967181-928e8cd4-a6c7-491f-974f-34c63563a8ad.png">

The values of x0, x2, x4 and x7 do not fall in the range I specified with the __ESBMC_assume instruction. It seems that ESBMC chooses some random value very close to 0.0f.

Note that I am running ESBMC with the following flags: `--force-malloc-success --no-bounds-check --no-div-by-zero-check --no-pointer-check --boolector`. However, I get a similar problem even when using Yices instead of boolector.

Any idea?

**Comment by mikhailramalho** [comment]
It looks like querying from the model is broken on boolector, here's the model:
```
(
  (define-fun __ESBMC_ptr_obj_start_0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun __ESBMC_ptr_obj_end_0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun __ESBMC_ptr_obj_start_1 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000001)
  (define-fun __ESBMC_ptr_obj_end_1 () (_ BitVec 64) #b1111111111111111111111111111111111111111111111111111111111111111)
  (define-fun smt_conv::__ESBMC_ptr_addr_range_0..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::__ESBMC_ptr_addr_range_0..end0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::__ESBMC_ptr_addr_range_1..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000001)
  (define-fun smt_conv::__ESBMC_ptr_addr_range_1..end0 () (_ BitVec 64) #b1111111111111111111111111111111111111111111111111111111111111111)
  (define-fun smt_conv::smt_conv::collate_array_vals::0..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::0..end0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::3..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::3..end0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::4..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::4..end0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::7..start0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun smt_conv::smt_conv::collate_array_vals::7..end0 () (_ BitVec 64) #b0000000000000000000000000000000000000000000000000000000000000000)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$1?1!0&0#1 () (_ BitVec 32) #b10111111000011010000000000000000)
  (define-fun nondet$symex::nondet0 () (_ BitVec 32) #b10111111000011010000000000000000)
  (define-fun c:bug_example.c@18@F@main@x0?1!0&0#1 () (_ BitVec 32) #b10111111000011010000000000000000)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$2?1!0&0#1 () (_ BitVec 32) #b00111111100001100111000000000000)
  (define-fun nondet$symex::nondet1 () (_ BitVec 32) #b00111111100001100111000000000000)
  (define-fun c:bug_example.c@47@F@main@x1?1!0&0#1 () (_ BitVec 32) #b00111111100001100111000000000000)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$3?1!0&0#1 () (_ BitVec 32) #b10111110110001111010111001001101)
  (define-fun nondet$symex::nondet2 () (_ BitVec 32) #b10111110110001111010111001001101)
  (define-fun c:bug_example.c@76@F@main@x2?1!0&0#1 () (_ BitVec 32) #b10111110110001111010111001001101)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$4?1!0&0#1 () (_ BitVec 32) #b00111111110100011111101110010011)
  (define-fun nondet$symex::nondet3 () (_ BitVec 32) #b00111111110100011111101110010011)
  (define-fun c:bug_example.c@105@F@main@x3?1!0&0#1 () (_ BitVec 32) #b00111111110100011111101110010011)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$5?1!0&0#1 () (_ BitVec 32) #b10111111001010010000000000000001)
  (define-fun nondet$symex::nondet4 () (_ BitVec 32) #b10111111001010010000000000000001)
  (define-fun c:bug_example.c@134@F@main@x4?1!0&0#1 () (_ BitVec 32) #b10111111001010010000000000000001)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$6?1!0&0#1 () (_ BitVec 32) #b00111111101100101001010010010000)
  (define-fun nondet$symex::nondet5 () (_ BitVec 32) #b00111111101100101001010010010000)
  (define-fun c:bug_example.c@163@F@main@x5?1!0&0#1 () (_ BitVec 32) #b00111111101100101001010010010000)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$7?1!0&0#1 () (_ BitVec 32) #b10111110100000000000000000000000)
  (define-fun nondet$symex::nondet6 () (_ BitVec 32) #b10111110100000000000000000000000)
  (define-fun c:bug_example.c@192@F@main@x6?1!0&0#1 () (_ BitVec 32) #b10111110100000000000000000000000)
  (define-fun c:@F@main::$tmp::return_value$_nondet_float$8?1!0&0#1 () (_ BitVec 32) #b10111111101100000000000000000000)
  (define-fun nondet$symex::nondet7 () (_ BitVec 32) #b10111111101100000000000000000000)
  (define-fun c:bug_example.c@221@F@main@x7?1!0&0#1 () (_ BitVec 32) #b10111111101100000000000000000000)
  (define-fun c:bug_example.c@876@F@main@y?1!0&0#1 () (_ BitVec 32) #b00111111010111000010100100100000)
  (define-fun execution_statet::\guard_exec?0!0 () (_ BitVec 1) #b1)
)
```

Maybe we are building the cex incorrectly only for negative numbers?

While I investigate, may I suggest you use z3? You will get some performance hit but the cex seems to be correct.

**Comment by emanino** [comment]
Thanks for looking into this. I will use z3 as you suggest.

**Comment by lucasccordeiro** [comment]
@emanino: could you please open the issues you have found about our support for FP arithmetic?

**Comment by emanino** [comment]
I am trying to reproduce the bug. So far I stand by my previous report: correct verification outcome, but incorrect counterexamples

**Comment by fbrausse** [comment]
The Z3 frontend has a special implementation `get_fpbv` while the other solvers seem to rely on the default `fp_convt`. The latter constructs a floating-point number by obtaining an integer from the bitstring by treating it as "signed" (that is, two's complement). I believe it should not, i.e., replace `true` by `false` in https://github.com/esbmc/esbmc/blob/493f459f1089317da78d81b81b95b01541f4aa52/src/solvers/smt/fp/fp_conv.cpp#L1162 I'm running tests now to see whether someone is relying on the current behaviour.

**Comment by emanino** [comment]
Hi Franz, thanks for looking into this.

In the meantime, I have run ESBMC on more complex floating-point problems (neural networks). While I cannot be 100% sure (testing is on the way), it seems that the reported counterexample contains a mixture of meaningful and meaningless values. FYI, I am mainly using Yices as it is the fastest solver for neural networks that we found.

**Comment by lucasccordeiro** [comment]
> I'm running tests now to see whether someone is relying on the current behaviour.

Many thanks, @fbrausse.

**Comment by fbrausse** [comment]
> mixture of meaningful and meaningless values.

Is it the case that the non-negative floats in counter-examples are meaningful?

**Comment by emanino** [comment]
> Is it the case that the non-negative floats in counter-examples are meaningful?

At the moment I cannot 100% confirm this (I have to improve my debugging infrastructure). For the subset of floating point variables that I can check, this is true. That is, values that should be negatives are reported incorrectly as number close to zero (in the order of 1e-38 or 1e-39). However, I might be able to give a more complete answer in the next few days.

**Comment by fbrausse** [comment]
Good, that is consistent with the patch, those wrong output representations of negative floats in counter-examples should be fixed (unless I missed a spot, ~still looking~). Many thanks @emanino and @mikhailramalho for your detailed reports, it did help in tracking this down!

Edit: done looking, I think that's all.
