### ISSUE TITLE
Copyright and license of ESBMC benchmarks

### ISSUE THREAD

**Issue by Misasasa** [esbmc/esbmc#525]
Hello, we made experiments on some ESBMC benchmarks (https://ssvlab.github.io/esbmc/benchmarks/cs-benchmarks.zip) in our paper. And we are going to participate in the Software Verification Competition and commit some benchmarks to SVCOMP, including "arithmetic_prog_*", "circular_buffer_*", "din_pil*" and "reorder_*". I wonder if this is permitted to use your benchmarks. If this is OK, could you please tell me their copyright and license? (This repo claims the license of ESBMC, but I am not sure if benchmarks also follow this license)

**Comment by rafaelsamenezes** [comment]
Hi @Misasasa ,

The license is the same as ESBMC (4-clause BSD). You are free to use them.

**Comment by rafaelsamenezes** [comment]
I will close this for now. @Misasasa feel free to reopen it if you need.
