### ISSUE TITLE
ESBMC is unable to dereference function pointer cast for void parameters

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#530]
ESBMC is not able to detect the bug in the following program:

```c
#include <assert.h>

void *foo() {
  assert(0);
  return 0;
}

void call_function(
    void *(*start_routine)(void*),
    void *arg) {
  (*start_routine)(arg);  
}


int main() {
  call_function(&foo, 0);
  return 0;
}
```

By replacing the signature of `foo` to `void *foo(void*)` ESBMC will find the bug. Executing this program with clang causes the program to fail.

**Comment by lucasccordeiro** [comment]
This PR https://github.com/esbmc/esbmc/pull/582 should close this issue.

**Comment by fbrausse** [comment]
It did.

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse  ;-)
