### ISSUE TITLE
Non-static build against system clang

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#535]
A number of Linux distributions don't ship the individual clang components `libclangTooling.a`, `libclangAST.a` and `libclangIndex.a` anymore ([Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1787375), [openSUSE](https://bugreports.qt.io/browse/QTCREATORBUG-23172?focusedCommentId=524992&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-524992), [Arch](https://bugs.archlinux.org/task/66283), [Gentoo](https://bugs.gentoo.org/710306), maybe others) since clang-10. As these are hardcoded in the `CMakeLists.txt`, it leads to build failures when configuring with the system's `LLVM_DIR` and `-DBUILD_STATIC=Off`:
```
FAILED: src/c2goto/c2goto 
: && /usr/bin/c++ -O2 -g -DNDEBUG  src/c2goto/CMakeFiles/c2goto.dir/c2goto.cpp.o src/c2goto/CMakeFiles/c2goto.dir/cprover_blank_library.cpp.o -o src/c2goto/c2goto  src/goto-programs/libgotoprograms.a  src/langapi/liblangapi.a  src/util/libutil_esbmc.a  src/util/message/libdefault_message.a  src/clang-c-frontend/libclangcfrontend_stuff.a  src/goto-programs/libgotoprograms.a  src/pointer-analysis/libpointeranalysis.a  src/util/libutil_esbmc.a  src/util/message/libdefault_message.a  src/util/message/libmessage.a  src/util/libfilesystem.a  src/util/message/libfmt_message_handler.a  src/util/message/libmessage_handler.a  /usr/lib64/libboost_filesystem.so.1.76.0  /usr/lib64/libboost_system.so.1.76.0  /usr/lib64/libboost_date_time.so.1.76.0  /usr/lib64/libboost_program_options.so.1.76.0  _deps/fmt-build/libfmt.a  src/big-int/libbigint.a  src/clang-c-frontend/AST/libclangcfrontendast.a  -lclangTooling  -lclangAST  -lclangIndex  src/clang-c-frontend/headers/libcheaders.a && :
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangTooling
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangAST
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangIndex
collect2: error: ld returned 1 exit status
```
Is it possible to enable linking against `libclang-cpp.so` in the non-static case? I do not know how Windows or OS X builds are handled, but the patch at https://github.com/fbrausse/esbmc/commit/3115dd0f1b113a8d882c84ceb8877e6ebc91a866 works for me (Gentoo, x86_64).

**Comment by rafaelsamenezes** [comment]
I will test this on Windows. I also things that this is related to issue #496

**Comment by rafaelsamenezes** [comment]
@fbrausse are you working on this? 

Do you know if this will also work for Windows?

**Comment by fbrausse** [comment]
Yes, I am working on this; for Linux it's working fine as it is. No idea about Windows (or Mac), don't have those accessible here.

**Comment by fbrausse** [comment]
For static builds nothing should change. However, an extension of this is about #496: either
a) use bundled headers from the ESBMC source (current only option)
b) use bundled headers from system (this is #496)
c) use bundled headers from user-specified location (for #516)
d) do not use bundled headers, and instead rely on system (or user-specified path)
This development is in https://github.com/fbrausse/esbmc/tree/fb/fix-gh496; item c) is not implemented, yet.

**Comment by fbrausse** [comment]
About the clib{32,64}{,_fp} GOTO libs: they should be bundled the same way as the headers, right?

**Comment by rafaelsamenezes** [comment]
> About the clib{32,64}{,_fp} GOTO libs: they should be bundled the same way as the headers, right?

Yes

**Comment by fbrausse** [comment]
What about the c2goto/headers? I understand they are not bundled, even though the libraries are. In particular when cross-compiling this might cause issues. One way out would be to bundle those as well and use as first `-I` parameter in:
https://github.com/esbmc/esbmc/blob/0749b2e72197e62323387f423ceb1ad339c9ae94/src/clang-c-frontend/clang_c_language.cpp#L48

**Comment by fbrausse** [comment]
Option c) above is now handled in #566. The GOTO libs are still missing: are their headers currently used to translating user input sources?
