### ISSUE TITLE
Error on writes to compound literals

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#591]
ESBMC does not fully support compound literals, e.g. it crashes on these constructs:
- `(int){0} = 42` leads to `assignment to constant_int not handled` and abort()
- `int z; memcpy(&(int){0}, &z, sizeof(z));` leads to
  ```
  Unrecognized address_of operand:
  address_of
  * pointer_obj : constant_int
      * value : 0
      * type : signedbv
        * width : 32
  * type : pointer
    * subtype : signedbv
        * width : 32
  Aborted
  ```

**Comment by fbrausse** [comment]
The clang-c-frontend only takes the initializer into account and does not care about the actual automatic storage attached to compound literals. Would the right approach be to allocate a new symbol for it?
https://github.com/esbmc/esbmc/blob/66dbfff29ca19a3948e5942c6a4a02f76a9b68f3/src/clang-c-frontend/clang_c_convert.cpp#L1444-L1449

**Comment by lucasccordeiro** [comment]
@mikhailramalho: do you have any thoughts here?

**Comment by mikhailramalho** [comment]
Reduced testcase:
```
#include<assert.h>

typedef struct {
  int data;
} s1;

typedef struct {
  int raw;
} s2;


int main() 
{ 
  s1 main_x;
  assert((s2){(&main_x)->data}.raw); 
}
```

**Comment by mikhailramalho** [comment]
> @mikhailramalho: do you have any thoughts here?

I'm a bit confused about what's going on, CBMC doesn't seem to create an extra symbol here.

**Comment by mikhailramalho** [comment]
The error is coming from the smt backend, as it doesn't understand dereferences.

I guess there are two possible solutions:
1. Teach the frontend to change the ast so the rest of esbmc understands it.
2. Look at why the pointer analysis/dereference code is not properly rewriting the expression.

**Comment by fbrausse** [comment]
> 2. Look at why the pointer analysis/dereference code is not properly rewriting the expression.

Because it is not parsed into a proper expression. A compound literal does have (automatic) storage within the surrounding block. As mentioned in https://github.com/esbmc/esbmc/issues/591#issuecomment-1030854767, it is converted to a `constant_(struct|union|int|double|...)2t`, which does not model storage, cannot be overwritten, etc.

That's why above I asked: Would the right approach be to allocate a new symbol for it?

**Comment by fbrausse** [comment]
CBMC wrongly reports a verification failure for
```c
#include <assert.h>
int main()
{
	assert(((int){0} = 42) == 42);
}
```
while ESBMC aborts with `assignment to constant_int not handled`.

**Comment by lucasccordeiro** [comment]
@fbrausse: have you considered the examples from this issue https://github.com/esbmc/esbmc/issues/709?
