### ISSUE TITLE
problem with the SMTLIB solver interface

### ISSUE THREAD

**Issue by DonatoClun** [esbmc/esbmc#6]
Hi

I think there is a problem with the SMTLIB interactive text interface. In smtlib_conv.cpp there are functions (e.g. mk_ite) that just call themselves, entering an infinite loop.

To notice the problem it is sufficient to output the verification conditions to a file (parameters `--smtlib --output outfile.smt`). The process will not terminate.

Anyway, thank you for releasing the new version of ESBMC.

Best,
Donato

**Comment by mikhailramalho** [comment]
Thanks for the report! 

We'll release a new version 5.1 soon, with the fix!

**Comment by mikhailramalho** [comment]
Fixed in v5.1. Thanks!
