### ISSUE TITLE
[Concurrency] We should revise our internal pthreadtypes.hs

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#600]
We should discuss further how to deal with our internal pthreadtypes.hs since it does not match the current system definition.

**Comment by fbrausse** [comment]
In #602 we decided to model our own pthread types and get rid of the unions originally from glibc. Our `bits/pthreadtypes.h` now is just a redirection to `<pthread.h>` for compatibility with other glibc headers we don't model, yet, and which do include it (same as `bits/thread-shared-types.h`).

**Comment by fbrausse** [comment]
What else needs to be done here?

**Comment by lucasccordeiro** [comment]
No. Thanks, @fbrausse.

Closed via https://github.com/esbmc/esbmc/pull/602.
