### ISSUE TITLE
Try-catch is broken for simple C++ programs

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#61]
If we run
$ ~/esbmc-v3.0.2-linux-64/bin/esbmc main.cpp

ESBMC fails to detect the assertion violation in the following program:
**\* Exception thrown of type signed_int at file main.cpp line 4
**\* Caught by catch(signed_int) at file  line 
Symex completed in: 0.000s
size of program expression: 12 assignments
Slicing time: 0.000s
Generated 0 VCC(s), 0 remaining after simplification
VERIFICATION SUCCESSFUL
BMC program time: 0.000s
# include <assert.h>

void myfunction () {
  throw 1;
}

int main (void) {
  try {
    myfunction();
  }
  catch (int) { assert(0); }
  return 0;
}

**Comment by lucasccordeiro** [comment]
@kunjsong01: you might get interested in this issue:

Our C++ clang frontend fails with this error message:

```
Conversion of unsupported clang expr: "CXXThrowExpr" to expression
CXXThrowExpr 0x7fe487897458 <main.cpp:2:1, col:7> 'void'
`-IntegerLiteral 0x7fe487897438 <col:7> 'int' 1

CONVERSION ERROR
```

**Comment by kunjsong01** [comment]
@lucasccordeiro  Thanks very much for the information. 

The above error refers to AST node to symbol conversion failure. I managed to run a try-catch example ch13_1 from `regression/esbmc-cpp/try_catch` to check whether we still have the same failure. 

The result is that ESBMC failed with a different error signature. The C++ clang frontend of latest ESBMC master (ea8da5e) failed in the parsing phase, before the symbol conversion phase. 

Here's error log for future reference: 
[latest_error_log.txt](https://github.com/esbmc/esbmc/files/7878177/latest_error_log.txt)

Command used: 
```
./esbmc ch13_1/main.cpp --unwind 10 --no-unwinding-assertions -I ./libraries/ --memlimit 14000000 --timeout 900
```

**Comment by intrigus-lgtm** [comment]
This appears to have been fixed.
