### ISSUE TITLE
ESBMC intrinsic memset enhancement

### ISSUE THREAD

**Issue by shmarovfedor** [esbmc/esbmc#635]
ESBMC uses intrinsic `memset` implementation (`__ESBMC_memset(ptr, val, size)`) to perform a much faster zero'ing of the memory by assigning a zero `expr2tc` directly to the memory addressed by the given pointer `ptr` instead of performing unrolling that is used in the default `memset` implementation. However, at the moment this only works when the allocation size and the size of the pointer type match, and when we allocate a larger block of memory, ESBMC resorts to the default implementation of `memset`. For example, ESBMC will use the intrinsic `memset` in the following piece of code:
```
  1 #include <stdlib.h>
  2
  3 int main()
  4 {
  5   int arr[4];
  6   int *ptr = malloc(sizeof(arr));
  7   ptr = __ESBMC_memset(ptr, 0, sizeof(arr));
  8   return 0;
  9 }
``` 
while when the allocation size in line 6 is increased by 1 (e.g., `int *ptr = malloc(sizeof(arr)+1);`), ESBMC will resort to the default implementation of `memset` that involves unrolling. I think that it should be possible extend the implementation of `__ESBMC_memset` to these kind of scenarios as it significantly outperforms the default `memset` for large allocations.

**Comment by mikhailramalho** [comment]
I wonder if we can simply the implementation by using concats + bitcasts.
