### ISSUE TITLE
Getting the size of a dynamic object

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#636]
Is there a way to reason about the size of a dynamic allocated object?

```c
void *foo() {
  return malloc(MAGIC_NUMBER);
}

int bar(void *ptr) {
  unsigned int size = __ESBMC_object_size(ptr); // Do we have something like this?
  assert(size == MAGIC_NUMBER);
}

int main() {
 bar(foo); 
}

```

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Can I ask you to take a look at this commit https://github.com/esbmc/esbmc/commit/ef4b859a550948966b605e5581f64fccb4343c37?

In particular, the implementation of the method `goto_symext::intrinsic_assert_object_size`.
