### ISSUE TITLE
Assert with dynamic strings don't work

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#645]
Every assert that are using dynamic strings:

```c
assert(0 && oss.str().c_str());
```
I think that we should:

1. Replace them with the default_msg.error
2. Make msg.error abort

Edit: 

List of missing:

- [ ] https://github.com/esbmc/esbmc/blob/master/src/util/type_byte_size.cpp#L142
- [ ] https://github.com/esbmc/esbmc/blob/master/src/util/type_byte_size.cpp#L82
- [ ] https://github.com/esbmc/esbmc/blob/master/src/util/type_byte_size.cpp#L78
- [ ] https://github.com/esbmc/esbmc/tree/master/src/util/migrate.cpp#L1608
- [ ] https://github.com/esbmc/esbmc/blob/master/src/solvers/boolector/boolector_conv.cpp#L9
- [ ] https://github.com/esbmc/esbmc/blob/master/src/solvers/bitwuzla/bitwuzla_conv.cpp#L9
- [ ] There are a few at solidity_grammar.cpp
- [ ] There are a few at irep2_type.cpp
- [ ] https://github.com/esbmc/esbmc/blob/master/src/clang-c-frontend/clang_c_language.cpp#L67

**Comment by fbrausse** [comment]
Are there any such constructs left? I couldn't find one.

**Comment by rafaelsamenezes** [comment]
> Are there any such constructs left? I couldn't find one.

I've updated the issue

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Can I ask you whether you have news about this issue?

**Comment by rafaelsamenezes** [comment]
This issue is no longer valid since we replace the entire message system
