### ISSUE TITLE
Infinite loop (?) on symbolic execution

### ISSUE THREAD

**Issue by mikhailramalho** [esbmc/esbmc#65]
OBS: the new llvm frontend is required in order to reproduce this error.

The program in [1] causes esbmc to hang during symbolic execution. Maybe an infinite loop.

Symex trace shows:

```
    num_total_threads=0;
    num_threads_running=0;
    __ESBMC_deallocated=ARRAY_OF(FALSE);
    __ESBMC_alloc=ARRAY_OF(FALSE);
    p=&{ 2, 4 }[0];
    __ESBMC_alloc_size=ARRAY_OF(0);
    pc=&{ 1f, 10f, 100f }[0];
    __ESBMC_is_dynamic=ARRAY_OF(FALSE);
    FUNCTION_CALL:  pthread_start_main_hook()
    ATOMIC_BEGIN
    num_total_threads=num_total_threads + 1;
    num_threads_running=num_threads_running + 1;
    ATOMIC_END
    END_FUNCTION
    FUNCTION_CALL:  main()
    signed int n;
    n=2;
    signed int * p;
    p=&n;
    p=&{ *p, 0 }[0];
```

**Comment by intrigus-lgtm** [comment]
@mikhailramalho is this still an issue?
I can't reproduce it with the clang frontend (or was there really an LLVM frontend?).

**Comment by mikhailramalho** [comment]
I can no longer reproduce the issue, we should create a PR to add the test case to our code base

**Comment by lucasccordeiro** [comment]
Here it goes: https://github.com/esbmc/esbmc/pull/2014
