### ISSUE TITLE
Create an option to not crash on models extraction

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#656]
When we don't support the model extraction for a specific type, we crash ESBMC. 

```cpp
msg.error(fmt::format(
      "Unimplemented type'd expression ({}) in smt get", type->type_id));
    abort();
```

Since this means that we found a bug, the violation itself can still be useful for the user. We should add an option `--non-supported-models-as-zero` which would replace this code with a `gen_zero`.

Let me know what you think

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: I agree with this option:

```
--non-supported-models-as-zero
```

Can you implement this option and check its impact over the SV-COMP benchmarks?

**Comment by mikhailramalho** [comment]
Sounds good!

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: did you have a chance to run this PR over the SV-COMP benchmarks?
