### ISSUE TITLE
ESBMC can't deal with assumes on three (or more) dimensional arrays

### ISSUE THREAD

**Issue by emanino** [esbmc/esbmc#661]
Hi all,
I have the following issue (see code below). When I declare a three-dimensional non-deterministic array and put assumes on the values of its entries, ESBMC stops checking the validity of later asserts. As an example, the following code returns a successful verification result despite containing an `__ESBMC_assert(0, "");` instruction at the end.

```c
int main()
{
  int x[1][1][3];
  x[0][0][0] = nondet_int();
  x[0][0][1] = nondet_int();
  x[0][0][2] = nondet_int();
  __ESBMC_assume((x[0][0][0] >= 77) && (x[0][0][0] <= 87));
  __ESBMC_assume((x[0][0][1] >= -64) && (x[0][0][1] <= 64));
  __ESBMC_assume((x[0][0][2] >= -64) && (x[0][0][2] <= 64));
  __ESBMC_assert(0, "");
  return 0;
}
```

Additional notes:
- the same code with a two-dimensional array (i.e. `int x[1][3];`) yields a correct verification result (fail).
- the same code with only two entries in the array (i.e. `int x[1][1][2];` and corresponding assumes) yields a correct verification result (fail).
- I confirmed the results above with ESBMC 6.9, but earlier (more complex) experiments make me believe the issue may have existed since at least version 6.7
- the issue appears with a variety of ESBMC flags, or no flags at all (i.e. `~/esbmc <filename.c>`)

**Comment by rafaelsamenezes** [comment]
Even with static values this seems to cause problems:

```c
int main()
{
  int x[1][1][3];
  x[0][0][0] = 80;
  x[0][0][2] = 0;
  __ESBMC_assume((x[0][0][0] >= 77) && (x[0][0][0] <= 87));
  __ESBMC_assume((x[0][0][2] >= -64) && (x[0][0][2] <= 64));
  __ESBMC_assert(0, "");
  return 0;
}
```

Also, can confirm that by removing one dimension, the issue does not happen anymore.

The verification coditions looks OK though:

```
file main.c line 8 function main
assertion
{-1} x?1!0&0#1 == (x?1!0&0#0 WITH [0:=x?1!0&0#0[0] WITH [0:=x?1!0&0#0[0][0] WITH [0:=80]]])
{-2} x?1!0&0#2 == (x?1!0&0#1 WITH [0:=x?1!0&0#1[0] WITH [0:=x?1!0&0#1[0][0] WITH [2:=0]]])
{-3} x?1!0&0#2[0][0][0] >= 77 && x?1!0&0#2[0][0][0] <= 87
{-4} x?1!0&0#2[0][0][2] >= -64 && x?1!0&0#2[0][0][2] <= 64
|--------------------------
{1} !execution_statet::\guard_exec?0!0
```

This might be an issue in the smt convertion.

**Comment by lucasccordeiro** [comment]
@emanino: Could you please check this issue with @rafaelsamenezes?

@fbrausse or @kunjsong01 could also help you solve this issue.

**Comment by rafaelsamenezes** [comment]
Getting the size of the flattened array is being incorrectly computed.

In the example at hand, the array is of type:

```
array
* subtype : array
    * subtype : array
        * subtype : signedbv
            * width : 32
        * array_size : constant_int
            * value : 3
            * type : signedbv
              * width : 32
        * size_is_infinite : false
    * array_size : constant_int
        * value : 1
        * type : signedbv
          * width : 32
    * size_is_infinite : false
* array_size : constant_int
    * value : 1
    * type : signedbv
      * width : 32
* size_is_infinite : false
```

The flattened size of it is being computed as:

```
constant_int
* value : 1
* type : signedbv
  * width : 32
```

Which is wrong, by manually replacing it with the correct number solved the issue.
