### ISSUE TITLE
ESBMC crashes during value set with union or struct dereference

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#669]
Runnig the program with: `esbmc main.i --function func1`

```c
// main.i
typedef union {
} a;
int b;
func1() { a c = *(a *)&b; }
```
Results in:

```
esbmc: ../src/pointer-analysis/value_set.cpp:1018: void value_sett::assign(const expr2tc&, const expr2tc&, bool): Assertion `lhs_type->type_id == rhs->type->type_id' failed.
Aborted (core dumped)
```

**Comment by fbrausse** [comment]
It also happens with `struct`s:
```c
typedef struct { int x;
} a;
int b;
void func1() { a c = *(a *)&b; }
```
unless they are empty, because this special case is caught in https://github.com/esbmc/esbmc/blob/220ed5276c5e204d217551c98dda5d9d8e0173b5/src/goto-symex/symex_assign.cpp#L155-L162 which should probably be extended to unions.

**Comment by fbrausse** [comment]
What is the expected verdict here? Technically, this is type-punning and thus undefined.

**Comment by rafaelsamenezes** [comment]
> What is the expected verdict here? Technically, this is type-punning and thus undefined.

I would say: 
- dereference error (if pointer checks are on)
- return a nondet value

**Comment by fbrausse** [comment]
FYI the PR does not address the requested "return a nondet value".
