### ISSUE TITLE
Doubt on SAME-OBJECT violation during pointer comparison

### ISSUE THREAD

**Issue by RekhaSigma** [esbmc/esbmc#674]
Hi,

  I am trying to understand the SAME-OBJECT violation flagged by ESBMC for the following code.
This is an abstract version of a real library function:
```
#include<stdio.h>

int main(){
        char d[10];
        char* s = "hello";
        if (s > d)
                printf("hello greater\n");
}
```

ESBMC gives the following result:
```
ESBMC version 6.8.0 64-bit x86_64 linux
file issue.c: Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.084s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Symex completed in: 0.000s (14 assignments)
Slicing time: 0.000s (removed 12 assignments)
Generated 1 VCC(s), 1 remaining after simplification (2 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.001s
Solving with solver Boolector 3.2.1
Encoding to solver time: 0.001s
Runtime decision procedure: 0.067s
Building error trace

Counterexample:

State 1 file issue.c line 6 function main thread 0
----------------------------------------------------
Violated property:
  file issue.c line 6 function main
  Same object violation
  SAME-OBJECT(s, &d[0])


VERIFICATION FAILED
```

I am curious as to why the SAME-OBJECT violation is flagged on a pointer comparison.
When the comparison in line 6 is equality, the program goes through.

Any clarification is highly appreciated.

Thanks.

**Comment by fbrausse** [comment]
Hi Rekha,

I do currently not have the actual logic as implemented in ESBMC at hand, but according to the C standard, relational comparisons (`<`,`<=`,`>`,`>=`) between pointers to different objects are undefined. At the same time, equality/disequality (`==`,`!=`) of pointers to different objects is defined. See e.g. https://en.cppreference.com/w/c/language/operator_comparison for details. I can look up the corresponding clause in the standard, if you're interested.

Undefined for at least one run of course means it is not possible to verify the given program.

**Comment by fbrausse** [comment]
What you can do however, is cast the pointers to an appropriate integer type, e.g.
```c
#include <stdint.h>
[...]
if ((intptr_t)s > (intptr_t)d) [...]
```
Note though, that C declares existence of `intptr_t` "optional", i.e., some implementations may choose not to define it. At some point the MCS-51 port of [sdcc](http://sdcc.sourceforge.net/) used to not define it, but they added it later. In case it doesn't exist I guess you are out of luck, meaning there is no universally portable way to determine order between objects in C.

**Comment by RekhaSigma** [comment]
Great Franz!
Yes. I checked the Standard.
Now it makes sense.

Thanks once again.

And yes, it works as 'expected' when the pointers are type casted.
