### ISSUE TITLE
Missing case in smt_convt::convert_terminal to deal with expr2t::member_id

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#687]
When converting a terminal, there is no case in our SMT converter to deal with `expr2t::member_id`. 

### Error message:
```
### ERROR:
Converting unrecognized terminal expr to SMT
```

### Preliminary investigations:
```
(gdb) p expr->expr_id
$5 = expr2t::member_id
(gdb) p expr.get()->dump()
member
* source_value : symbol
    * name : c:@real_if_function1_inlined_1
    * renamelev : Level 2 (global)
    * level1_num : 0
    * level2_num : 4
    * thread_num : 0
    * node_num : 0
    * type : struct
      * members :
        0: floatbv
          * fraction : 23
          * exponent : 8
        1: signedbv
          * width : 32

      * member_names :
        0: x
        1: z

      * member_pretty_names :
        0: x
        1: z

      * typename : __real_if_function
      * packed : false
* member_name : x
* type : floatbv
  * fraction : 23
  * exponent : 8
$6 = void
```

### Info to Re-produce the Bug:
ESBMC mainline commit ee09a0755. 

Test case: 
```c
#include <stdbool.h>
typedef struct {
	float x;
	bool z;
} myStruct;

int main(void) {
  myStruct testObj;
  testObj.x = 0.0;
  testObj.z = false;

  if (testObj.x > 10.0)
  {
    testObj.z = true;
  }

  assert(testObj.z); // fail
  return 0;
}
```

Command lines used: 
```
./esbmc main.c --ir --z3
``` 

This bug was revealed by commit e4dca2c0d30d827, after we updated the SMT conversion flow to encode the original fp term in real mode when using "--ir" and "--floatbv" together.

**Comment by lucasccordeiro** [comment]
@kunjsong01: I believe @fbrausse could help you with this issue.

**Comment by kunjsong01** [comment]
I've replaced the original test case with a much simpler one that is also capable of reproducing the bug.

### More investigations: 
```
ASSIGNMENT (HIDDEN)
goto_symex::guard?0!0&0#1 == (double)testObj?1!0&0#2.x > 10.000000
```  
In the above SSA statement, ESBMC doesn't know how to encode struct member typecasting `(double)testObj.x` using real/int mode. Previously, our patch e4dca2c0d3 just fixeed the scalar variable typecasting encoding, e.g. `(double)x` where x is a float. 

I reckon the fix should be similar to the fix in PR https://github.com/esbmc/esbmc/pull/660. I'm going to have a go at the fix and submit another PR.

**Comment by fbrausse** [comment]
`convert_terminal` only handles leafs of the expression tree. I believe this fixes the issue:

```patch
--- a/src/solvers/smt/smt_casts.cpp
+++ b/src/solvers/smt/smt_casts.cpp
@@ -579,7 +579,7 @@ smt_astt smt_convt::convert_typecast(const expr2tc &expr)
   {
     // When using --ir mode and --floatbv, we ignore the fp-to-fp typecasting
     // and the just encode the original fp term using real mode
-    return convert_terminal(cast.from);
+    return convert_ast(cast.from);
   }
 
   if(cast.type == cast.from->type)
```

With that patch, the given example will be fail when extracting the counter-example from the SMT model:
```
Building error trace
esbmc: src/solvers/z3/z3_conv.cpp:1224: virtual ieee_floatt z3_convt::get_fpbv(smt_astt): Assertion `Z3_get_ast_kind(z3_ctx, e) == Z3_APP_AST' failed.
```
hinting at a problem in `smt_convt::get_by_ast()` for the `floatbv` case: it should take `int_encoding` into account (or maybe better yet, do the case distinction not based on the expr2t's type, but on the smtt's one)

**Comment by kunjsong01** [comment]
Closed via PR https://github.com/esbmc/esbmc/pull/689
