### ISSUE TITLE
Detect whether we can build 32/64 bit C libraries

### ISSUE THREAD

**Issue by jmorse** [esbmc/esbmc#69]
Prior to 7989562d, the sv-comp benchmark pthread/sigma_false-unreach-call.i croaked saying that time_t's definition differed between the benchmark and the machine esbmc was compiled on. This seems really really unlikely, because it used to work, and nothing has really changed. Except, uh, autotools.

This is really really fishy, but I can't look at it at this exact moment.

**Comment by fbrausse** [comment]
I think this has been taken care of by #602 (if not earlier). We're using our own headers now and --32 and --64 both work for c2goto.
