### ISSUE TITLE
ESBMC crashes with array of unions

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [esbmc/esbmc#691]
Example:

``` c
#include <assert.h>

#define ARR_SIZE 1

typedef unsigned char uint8_t;
typedef unsigned int uint32_t;

typedef union {
  uint32_t dwords[2];
  uint8_t bytes[8];
} qword_t;

uint32_t nondet_uint32_t() {
  uint32_t val;
  return val;
}

int main() {

  qword_t a[ARR_SIZE];
  qword_t b[ARR_SIZE];
  
  for (int i = 0; i < ARR_SIZE; i++) { 
    for (int j = 0; j < 2; j++) {
      a[i].dwords[j] = nondet_uint32_t();
    }
    b[i] = a[i];
  }

  assert(b[0].bytes[0] == 0);

  return 0;
}
```

ESBMC output:

``` bash
Segmentation fault (core dumped)
```

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please take a look at this issue?

**Comment by fbrausse** [comment]
With current master I'm getting a segfault using CVC4, but not with Boolector, Z3 or Yices.

@Bo-Yuan-Huang Which version of ESBMC and what command line flags (if any) have you been using? *Edit*: never mind, I think I found the cause.

> @fbrausse: could you please take a look at this issue?

Sure, I'm on it. Looks like some bug in the cex extraction with CVC4.

**Comment by lucasccordeiro** [comment]
@fbrausse: can you please add the test case in this issue as a regression to your PR https://github.com/esbmc/esbmc/pull/697?
