### ISSUE TITLE
Seg fault with union, array, struct, and loop

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [esbmc/esbmc#704]
Segmentation fault with the below example

``` c
typedef union uni_s {
  int data;
} uni_t;

typedef struct arr_s {
  int data[2];
} arr_t;

typedef struct top_s {
  uni_t u; 
  arr_t a;
} top_s;

int main() {
  top_s t;
  arr_t* a = &t.a;

  for (int i = 0; i < 2 ; i++) {
    a->data[i] = i;
  }

  return 0;
}
``` 

Version: ESBMC version 6.9.0 64-bit x86_64 linux
(Current master `d206ccc8dfdb026d3ff115abb2f30fe11e156111` )

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please take a look at this issue?

**Comment by fbrausse** [comment]
Thanks for stress-testing our dereference code! ;)

I've added a quick fix and will open a PR once the CI passes. To me it looks more and more like a kind of consolidation of the entire dereference code is required. There are duplications, with all their problems like fixes potentially only being applied to one instance and so on... At some point I may start reorganizing this.
