### ISSUE TITLE
Assertion `uni_type.members.size() != 0' failed

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#716]
ESBMC fails in the following program:

```c
#include <stdbool.h>
#include <stdint.h>
 
typedef union{
} union1;
 
typedef union{
    struct {
        uint32_t    union2_var:1;
    };
} union2;
extern union2 u2;
 
typedef struct {
    bool struct1_flag;
} struct1;
 
typedef struct {
    union1 u1;
    struct1 struct2_var1;
    struct1 struct2_var2;
 
} struct2;
 
typedef struct {
    struct2 struct3_var1;
} struct3;
 
extern struct3 struct3_extern;
 
void main(void) {
    bool flag;
 
    struct1 *struct1_p;
 
    if (flag) {
        struct1_p = &(struct3_extern.struct3_var1.struct2_var2);
    } else {
        struct1_p = &(struct3_extern.struct3_var1.struct2_var1);
    };
 
    struct1_p->struct1_flag = (u2.union2_var) != 0;
}
```

Reduced version:

```c
typedef union {
  struct {
    int a : 1
  };
} b;
b c;
main() { c.a; }
```

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please take a look at this issue?

**Comment by fbrausse** [comment]
With neither of these examples I'm getting the error in the title with eff35eb1700838c5af8d619a70b6910ac84d4c0a.
The first version results in an error related to the empty union type `union1`. The "reduced" version gives me `VERIFICATION SUCCESSFUL`.

**Comment by rafaelsamenezes** [comment]
I will confirm tomorrow if I did a mistake xD. As of now, the assertion itself is in `#ifndef NDEBUG` and the original issue had a `--no-pointer-check` (which shoudn't matter). So:

1. Could you confirm that you are running in a DEBUG build?
2. Could you try adding the `--no-pointer-check`?

**Comment by fbrausse** [comment]
Yes to both :)

**Comment by rafaelsamenezes** [comment]
Now I am using eff35eb1700838c5af8d619a70b6910ac84d4c0a 

The reduced version does not have the problem anymore. But now the original program still has: ```Assertion `uni_type.members.size() != 0' failed```
