### ISSUE TITLE
Aborted with empty union and struct of array

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [esbmc/esbmc#719]
Version: current master (`eff35eb1700838c5af8d619a70b6910ac84d4c0a`)

Command:
``` bash
esbmc main.c --compact-trace
```

Input program:
``` c
#include <assert.h>

typedef union {
  struct {};
} s1;

typedef struct {
  int x[2];
} s2;

s1 v1;
s2 v2;

int main() {
  for (int i = 0; i < 2; i++) {
    v2.x[i] = 0;
  }

  int x = 0;
  for (int i = 0; i < 2; i++) {
    x++;
  }
  assert(x == 0);

  return 0;
}
```

**Comment by lucasccordeiro** [comment]
@fbrausse: does this PR https://github.com/esbmc/esbmc/pull/717 already fixes the issue reported here by @Bo-Yuan-Huang?

**Comment by fbrausse** [comment]
@lucasccordeiro it does not. I'm getting errors in smt_conv related to empty unions: BVs of width 0 are not supported in SMT-LIB.

**Comment by fbrausse** [comment]
I suppose one way to cleanly model those is to represent unions as a tuple containing either a single BV or being the empty tuple. That would bring it in line with what we do for empty structs, though it would require touching all places dealing with unions in smt_conv and would probably be less efficient than just using a single BV of `max(1, union_bit_width)` bits - the value of the single bit won't be accessible anyway.

**Comment by lucasccordeiro** [comment]
@Bo-Yuan-Huang: BTW, please let us know if the proposed fix by @fbrausse allowed you to go further with your verification effort.

**Comment by Bo-Yuan-Huang** [comment]
@lucasccordeiro Thanks, it does help make it one step further. There's a new issue and I'm working on it to distill a litmus test for sharing.
