### ISSUE TITLE
ESBMC 6.10

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#724]
We should prepare for the next release of ESBMC. @fbrausse has solved lots of union problems recently.

So, which open PRs should we wait for the next release? Is there any other features that we should add before it?

**Comment by lucasccordeiro** [comment]
@fbrausse still has one PR to be merged. Once that PR is merged, I’m okay to release a new version of ESBMC.

I want to thank @fbrausse for his huge effort to fix many issues concerning our memory model.

**Comment by mikhailramalho** [comment]
I agree with making a new release, thanks @fbrausse for the effort.

I have one last issue that I wanted @fbrausse to look at before creating the release, should be an easy fix and it will improve our cex slightly.

**Comment by mikhailramalho** [comment]
I created issue #725

**Comment by fbrausse** [comment]
Many thanks! :)

I would like to see whether #723 could be addressed easily (guess it'll be important for C++'s `this` on empty classes).

@mikhailramalho I'll take a look.

**Comment by fbrausse** [comment]
I'd suggest not to treat #725 as a blocker for a release. It definitely has a worthy goal, but it is my understanding that it either requires more discussion ("massage" expressions in cex generation or cex presentation) or relaxing assumptions on the irep2 expression `index2t`, which could have lots of side effects.

**Comment by mikhailramalho** [comment]
I'm fine with that. 

I think we'll only see real benefits from #725 in SV-COMP and witness validation.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Can I ask you to prepare the release 6.10 of ESBMC?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: this release does not show up at https://github.com/esbmc/esbmc/releases.
