### ISSUE TITLE
[ESBMC++ Dev Tracking] Incorrect verification result for lvalue reference

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#736]
Incorrect verification result for reference. 

### Test case (global variable reference): 
```cpp
  1 #include <cassert>
  2 int g;
  3 void function(int &t) { t = 2;}
  4
  5 int main()
  6 {
  7   int &r = g;
  8   r = 1;
  9   assert(g == 1);
 10   function(r);
 11   assert(g == 2);
 12 }
```

Output: 
```yaml
Counterexample:

State 1 file main.cpp line 9 function main thread 0
----------------------------------------------------
Violated property:
  file main.cpp line 9 function main // <--- should not fail
  assertion g == 1
  g == 1


VERIFICATION FAILED
```

### Test case (local variable reference): 
```cpp
  1 #include <cassert>
  2 void function(int &t) { t = 2;}
  3
  4 int main()
  5 {
  6   int g;
  7   int &r = g;
  8   r = 1;
  9   assert(g == 1);
 10   function(r);
 11   assert(g == 2);
 12 }
```

Output: 
```yaml
Counterexample:

State 2 file main_local.cpp line 11 function main thread 0
----------------------------------------------------
Violated property:
  file main_local.cpp line 11 function main
  assertion g == 2
  g == 2


VERIFICATION FAILED
```

### Info to reproduce the bug:
esbmc mainline 884a7ad184198 + `gh pr checkout 733` 

commandline: ./esbmc <program_under_test>.cpp

**Comment by kunjsong01** [comment]
AST of `int &r = g;`: 

```cpp
    |-DeclStmt 0x8a20f58 <line:7:3, col:13>
    | `-VarDecl 0x8a20ed0 <col:3, col:12> col:8 used r 'int &' cinit
    |   `-DeclRefExpr 0x8a20f38 <col:12> 'int' lvalue Var 0x8a20e38 'g' 'int'
```

The frontend created irep tree: 
```yaml
    1: code
        * type: code
            * arguments: 
        * operands: 
          0: code
              * type: code
                  * arguments: 
              * operands: 
                0: symbol      # ---> this should be converted to "pointer" with subtype==signedbv
                    * type: signedbv      
                        * width: 32
                        * #cpp_type: signed_int
                    * name: r
                    * identifier: c:ref.cpp@76@F@main#@r
                1: symbol     # ---> this operand should wrapped in an "address_of" node
                    * type: signedbv    
                        * width: 32
                        * #cpp_type: signed_int
                    * name: g
                    * identifier: c:ref.cpp@67@F@main#@g
                    * #location: 
                      * file: ref.cpp
                      * line: 7
                      * function: main
                    * #lvalue: 1
              * statement: decl
              * #location: 
                * file: ref.cpp
                * line: 7
                * function: main
        * statement: decl-block
```

**Comment by kunjsong01** [comment]
A generalised method to handle lvalue reference in C++: 

1. For `VarDecl` of the type lvalue reference (see VarDecl AST example below), convert to a `pointer` subtree.
```cpp
200     |-DeclStmt 0x8b25518 <line:7:3, col:13>
201     | `-VarDecl 0x8b25490 <col:3, col:12> col:8 used r 'int &' cinit
202     |   `-DeclRefExpr 0x8b254f8 <col:12> 'int' lvalue Var 0x8b253f8 'g' 'int'
```
2. For `DeclRefExpr` of the type lvalue reference (see DeclRefExpr AST example below), convert to `dereference` subtree. 
```cpp
203     |-BinaryOperator 0x8b25570 <line:8:3, col:7> 'int' lvalue '='
204     | |-DeclRefExpr 0x8b25530 <col:3> 'int' lvalue Var 0x8b25490 'r' 'int &'
205     | `-IntegerLiteral 0x8b25550 <col:7> 'int' 1
```

3. For `ParmVarDecl` of the type lvalue reference (see ParmVarDecl AST example below), follow Rule 1.
```cpp
190 |-FunctionDecl 0x8b251c0 <ref.cpp:2:1, col:31> col:6 used function 'void (int &)'
191 | |-ParmVarDecl 0x8b10e28 <col:15, col:20> col:20 used t 'int &'
```

Illustration of Rule 1: 
![generalized_ref_handling drawio](https://user-images.githubusercontent.com/32592800/173812128-afb647e6-e7d0-4d0a-9765-8aa3a09977fa.png)

**Comment by kunjsong01** [comment]
After implementing Rule 1, 2 and 3, there is another problem: 

```cpp
Symbol......: c:@F@main#
Module......: ref
Base name...: main
Mode........: C (0)
Type........: signed int ()
Value.......: 
{
signed int g;

signed int * r=(signed int *)g; //---> should be &g

*r = 1;
```

Solution: 
Need to convert 'g' to address_of subtree in the DeclStmt: 
```
200     |-DeclStmt 0x879d518 <line:7:3, col:13>
201     | `-VarDecl 0x879d490 <col:3, col:12> col:8 used r 'int &' cinit
202     |   `-DeclRefExpr 0x879d4f8 <col:12> 'int' lvalue Var 0x879d3f8 'g' 'int'
```

**Comment by kunjsong01** [comment]
The problem in https://github.com/esbmc/esbmc/issues/736#issuecomment-1157082683 has been fixed by commit 7f77c4b71623482234a324ceaba199da9c523569. 

We are able to verify C++ reference *without* funtion call: 
```cpp
     1	#include <cassert>
     2
     3	int main()
     4	{
     5	  int g;
     6	  int &r = g;
     7	  r = 1;
     8	  assert(g == 1); // pass
     9	  r = 2;
    10	  assert(g == 0); // fail
    11	}
```

Symbols look good: 
```yaml
2853 @@ Done printing value for: c:@F@main#
2854 Symbol......: c:@F@main#
2855 Module......: ref
2856 Base name...: main
2857 Mode........: C (0)
2858 Type........: signed int ()
2859 Value.......:
2860 {
2861 signed int g;
2862
2863 signed int * r=&g; # ---> VarDecl of lvalue reference is converted to pointer and RHS is address_of
2864
2865 *r = 1;  # ---> DeclRef of lvalue reference is converted to pointer
2866
2867 g == 1 ? 0 : __assert_fail(&"g == 1"[0], &"ref.cpp"[0], 8, &"int main()"[0]);
2868
2869 *r = 2; # ---> DeclRef of lvalue reference is converted to pointer
2870
2871 g == 0 ? 0 : __assert_fail(&"g == 0"[0], &"ref.cpp"[0], 10, &"int main()"[0]);
2872
2873 }
```

Verification result: 
```yaml

Counterexample:

State 1 file ref.cpp line 6 function main thread 0
----------------------------------------------------
  r = &g

State 2 file ref.cpp line 7 function main thread 0
----------------------------------------------------
  *r = 1 (00000000 00000000 00000000 00000001)

State 3 file ref.cpp line 9 function main thread 0
----------------------------------------------------
  *r = 2 (00000000 00000000 00000000 00000010)

State 4 file ref.cpp line 10 function main thread 0
----------------------------------------------------
Violated property:
  file ref.cpp line 10 function main
  assertion g == 0
  g == 0


VERIFICATION FAILED
```

**Comment by kunjsong01** [comment]
Still need to fix the function call site: 
```cpp
2988 Value.......:
2989 {
2990 signed int g;
2991
2992 signed int * r=&g;
2993
2994 *r = 1;
2995
2996 g == 1 ? 0 : __assert_fail(&"g == 1"[0], &"ref2.cpp"[0], 9, &"int main()"[0]);
2997
2998 function((signed int *)(*r)); // ---> lvalue ref param should be like `function(r)`
2999
3000 g == 2 ? 0 : __assert_fail(&"g == 2"[0], &"ref2.cpp"[0], 11, &"int main()"[0]);
3001
3002 }
```

**Comment by kunjsong01** [comment]
The problem in https://github.com/esbmc/esbmc/issues/736#issuecomment-1157607950 has been resolved by commit 84178f23b13459155305a1eff5fbf5acec2055e9. 

```cpp
2988 Value.......:
2989 {
2990 signed int g;
2991
2992 signed int * r=&g;
2993
2994 *r = 1;
2995
2996 g == 1 ? 0 : __assert_fail(&"g == 1"[0], &"ref.cpp"[0], 10, &"int main()"[0]);
2997
2998 function(&(*r));  // ---> wrap DeclRef in a &(.) 
2999
3000 g == 1 ? 0 : __assert_fail(&"g == 1"[0], &"ref.cpp"[0], 12, &"int main()"[0]);
3001
3002 }
```

### Solution:
Converting to `function(r)` would conflict with Rule3 in https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386. As a result, the solution is to wrap it in an `address_of` exprt.

**Comment by kunjsong01** [comment]
This issue is resolved by PR https://github.com/esbmc/esbmc/pull/753. 
It will be closed when PR is merged.

**Comment by kunjsong01** [comment]
The conversion should follow the two-step rule rather changing the usual flow of conversion. (as explained in review comment https://github.com/esbmc/esbmc/pull/753#pullrequestreview-1010183020)

### Solution
Mark the irep tree using "#reference: 1"  and adjust the code in `clang_cpp_adjuster`. 

```yaml
    1: code
        * type: code
            * arguments: 
        * operands: 
          0: code
              * type: code
                  * arguments: 
              * operands: 
                0: symbol  # ---> this should be converted to "pointer" with subtype==signedbv in clang_cpp_adjuster
                    * type: signedbv      
                        * width: 32
                        * #cpp_type: signed_int
                    * name: r
                    * identifier: c:ref.cpp@76@F@main#@r
                1: symbol     # ---> this operand should wrapped in an "address_of" node in clang_cpp_adjuster
                    * type: signedbv    
                        * width: 32
                        * #cpp_type: signed_int
                    * name: g
                    * identifier: c:ref.cpp@67@F@main#@g
                    * #location: 
                      * file: ref.cpp
                      * line: 7
                      * function: main
                    * #lvalue: 1
              * statement: decl
              * #reference: 1 // ---> mark this irep tree as a reference for clang_cpp_adjuster
              * #location: 
                * file: ref.cpp
                * line: 7
                * function: main
        * statement: decl-block
```

**Comment by kunjsong01** [comment]
### Generalised method to handle C++ reference based on two-step conversion (i.e. convert-adjust): 
Updated rules originally posted in https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386:
1. For `VarDecl` of the type lvalue reference (see VarDecl AST example below), convert LHS of decl-block to a `pointer` subtree. If it has initialization, **adjust** the RHS of the decl-block irep to `address_of` subtree. (Done in commit 797c91bead). Note that if we have an lvalue reference on RHS, it must be a DeclRefExpr, otherwise the compiler will report an error "undeclared identifier" or something similar. So it will be handled by _Rule 2_ below.  

2. For `DeclRefExpr` of the type lvalue reference, **mark** the irep during conversion with `reference: 1`. Then **adjust** the corresponding irep part to `dereference` subtree.  e.g.: 
```yaml
                  * operands: 
                    0: symbol   # ---> Condition 1: it must be a symbol, because DeclExprRef refers to a previously defined symbol. 
                        * type: pointer
                            * subtype: signedbv
                                * width: 32
                                * #cpp_type: signed_int
                        * name: r
                        * identifier: c:main.cpp@78@F@main#@r
                        * reference: 1 # ---> Condition 2: it must be marked by "reference: 1"
                        * #location: 
                          * file: main.cpp
                          * line: 8
                          * function: main
                        * #lvalue: 1 # ---> Condition 3: To be more defensive, it has to be an lvalue. 
```

3. (remains the same) For `ParmVarDecl` of the type lvalue reference (see ParmVarDecl AST example below), follow Rule 1.

**Comment by kunjsong01** [comment]
One big problem about "marking-adjusting" is that the symbol we try to adjust does not preserve the original marking: 
![not_preserving_marking](https://user-images.githubusercontent.com/32592800/176714570-87550927-b719-484d-accb-08bc70dfdd9a.png)


Need to solve this problem, otherwise we won't be able to locate the DeclRefExpr symbol.

**Comment by mikhailramalho** [comment]
Yeah, you have to figure it out why we are dropping this attribute.

**Comment by kunjsong01** [comment]
> ### Generalised method to handle C++ reference based on two-step conversion (i.e. convert-adjust):
> 
> Updated rules originally posted in [#736 (comment)](https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386):
> 
>     1. For `VarDecl` of the type lvalue reference (see VarDecl AST example below), convert LHS of decl-block to a `pointer` subtree. If it has initialization, **adjust** the RHS of the decl-block irep to `address_of` subtree. (Done in commit [797c91b](https://github.com/esbmc/esbmc/commit/797c91bead26a77da9f0b981b250b683c2701c1b)). Note that if we have an lvalue reference on RHS, it must be a DeclRefExpr, otherwise the compiler will report an error "undeclared identifier" or something similar. So it will be handled by _Rule 2_ below.
> 
>     2. For `DeclRefExpr` of the type lvalue reference, **mark** the irep during conversion with `reference: 1`. Then **adjust** the corresponding irep part to `dereference` subtree.  e.g.:
> 
> 
> ```yaml
>                   * operands: 
>                     0: symbol   # ---> Condition 1: it must be a symbol, because DeclExprRef refers to a previously defined symbol. 
>                         * type: pointer
>                             * subtype: signedbv
>                                 * width: 32
>                                 * #cpp_type: signed_int
>                         * name: r
>                         * identifier: c:main.cpp@78@F@main#@r
>                         * reference: 1 # ---> Condition 2: it must be marked by "reference: 1"
>                         * #location: 
>                           * file: main.cpp
>                           * line: 8
>                           * function: main
>                         * #lvalue: 1 # ---> Condition 3: To be more defensive, it has to be an lvalue. 
> ```
> 
>     3. (remains the same) For `ParmVarDecl` of the type lvalue reference (see ParmVarDecl AST example below), follow Rule 1.



> ### Generalised method to handle C++ reference based on two-step conversion (i.e. convert-adjust):
> 
> Updated rules originally posted in [#736 (comment)](https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386):
> 
>     1. For `VarDecl` of the type lvalue reference (see VarDecl AST example below), convert LHS of decl-block to a `pointer` subtree. If it has initialization, **adjust** the RHS of the decl-block irep to `address_of` subtree. (Done in commit [797c91b](https://github.com/esbmc/esbmc/commit/797c91bead26a77da9f0b981b250b683c2701c1b)). Note that if we have an lvalue reference on RHS, it must be a DeclRefExpr, otherwise the compiler will report an error "undeclared identifier" or something similar. So it will be handled by _Rule 2_ below.
> 
>     2. For `DeclRefExpr` of the type lvalue reference, **mark** the irep during conversion with `reference: 1`. Then **adjust** the corresponding irep part to `dereference` subtree.  e.g.:
> 
> 
> ```yaml
>                   * operands: 
>                     0: symbol   # ---> Condition 1: it must be a symbol, because DeclExprRef refers to a previously defined symbol. 
>                         * type: pointer
>                             * subtype: signedbv
>                                 * width: 32
>                                 * #cpp_type: signed_int
>                         * name: r
>                         * identifier: c:main.cpp@78@F@main#@r
>                         * reference: 1 # ---> Condition 2: it must be marked by "reference: 1"
>                         * #location: 
>                           * file: main.cpp
>                           * line: 8
>                           * function: main
>                         * #lvalue: 1 # ---> Condition 3: To be more defensive, it has to be an lvalue. 
> ```
> 
>     3. (remains the same) For `ParmVarDecl` of the type lvalue reference (see ParmVarDecl AST example below), follow Rule 1.


Let's forget about these hack rules as explained in https://github.com/esbmc/esbmc/pull/753#issuecomment-1171509890.

**Comment by kunjsong01** [comment]
### Old frontend's Conversion Fules: 

1. `int &r = g;` is converted to `int &r = &g;`
LHS of irep tree's operands refers to the symbol `r`, RHS of irep tree's operands refers to the dereference of the a declaration reference to a previously declared symbol `g`. 
```yaml
     1: code
        * type: code
            * arguments: 
        * operands: 
          0: code
              * type: code
                  * arguments: 
              * operands: 
                0: symbol
                    * type: pointer
                        * subtype: signedbv
                            * width: 32
                            * #cpp_type: signed_int
                        * #location: 
                          * file: ref.cpp
                          * line: 5
                        * #reference: 1
                    * identifier: main::main()::1::r
                1: address_of
                    * type: pointer
                        * subtype: signedbv
                            * width: 32
                            * #cpp_type: signed_int
                        * #reference: 1
                    * operands: 
                      0: symbol
                          * type: signedbv
                              * width: 32
                              * #cpp_type: signed_int
                          * identifier: main::main()::1::g
                          * #location: 
                            * file: ref.cpp
                            * line: 5
                          * #lvalue: 1
                    * #location: 
                      * file: ref.cpp
                      * line: 5
              * statement: decl
              * #location: 
                * file: ref.cpp
                * line: 5
        * statement: decl-block
```

2. `r = 1;` is converted to `*r = 1;` 
LHS of irep tree's operands refers to the symbol `r`, RHS of irep tree's operands refers to the dereference of the a declaration to an lvalue reference symbol. 
```yaml
    2: code
        * type: code
            * arguments: 
        * operands: 
          0: dereference
              * type: signedbv
                  * width: 32
                  * #cpp_type: signed_int
              * operands: 
                0: symbol
                    * type: pointer
                        * subtype: signedbv
                            * width: 32
                            * #cpp_type: signed_int
                        * #location: 
                          * file: ref.cpp
                          * line: 5
                        * #reference: 1
                    * identifier: main::main()::1::r
                    * #location: 
                      * file: ref.cpp
                      * line: 6
              * #location: 
                * file: ref.cpp
                * line: 6
              * #implicit: 1
              * #lvalue: 1
          1: constant
              * type: signedbv
                  * width: 32
                  * #cpp_type: signed_int
              * value: 00000000000000000000000000000001
              * #location: 
                * file: ref.cpp
                * line: 6
              * #cformat: 1
        * statement: assign
        * #location: 
          * file: ref.cpp
          * line: 6
```

This is pretty much the same to the rules we developed in [previous comment](https://github.com/esbmc/esbmc/issues/736#issuecomment-1156324386). This probably explains why our previous rules worked (but in a really hacky way).

**Comment by kunjsong01** [comment]
### Preliminary Investigation of GOTO conversion error: 
```
Generating GOTO Program
### ERROR:
expression statement takes one operand
```

The above error was caused by old frontend add an empty operand: 
```
(gdb) p code.dump()
code
  * type: code
      * arguments:
  * operands:
    0:
      * type:
    1: sideeffect
        * type: signedbv
            * width: 32
            * #constant: 0
            * #cpp_type: signed_int
            * #member_name: tag.t1
        * operands:
          0: member
              * type: signedbv
                  * width: 32
                  * #constant: 0
                  * #cpp_type: signed_int
                  * #member_name: tag.t1
              * operands:
......
......
```

In clang cpp frontend, we should avoid adding an empty operand tree node.

**Comment by kunjsong01** [comment]
Basic support for lvalue reference is done in https://github.com/esbmc/esbmc/pull/804 

We'll fix the bugs and/or add more supports on the fly after running a full benchmark.

**Comment by kunjsong01** [comment]
Basic support for lvalue reference is done in https://github.com/esbmc/esbmc/pull/804. 

We'll fix the bugs and/or add more supports on the fly after running a full benchmark. 

Closing the issue....
