### ISSUE TITLE
With the new https://github.com/Z3Prover/z3/commit/ab9aee189b7be07d6c0ad6eb218693c534b405d6 (probably going to be part of v4.8.18) both, mem and time performance of Z3 are much better:

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#761]
@rafaelsamenezes Is there a way to let the Windows CI run on Z3 master?

_Originally posted by @fbrausse in https://github.com/esbmc/esbmc/pull/760#issuecomment-1162400017_

Basically, lets update the actions to use this commit of Z3.

**Comment by fbrausse** [comment]
Hi Rafael, thanks! Actually, there has been another fix ontop of that commit which affects running time (positively) and from the description looks like being about correctness: https://github.com/Z3Prover/z3/commit/41deed59a3201375c5c31513c06a4020f594e2a5

**Comment by rafaelsamenezes** [comment]
> Hi Rafael, thanks! Actually, there has been another fix ontop of that commit which affects running time (positively) and from the description looks like being about correctness: https://github.com/Z3Prover/z3/commit/41deed59a3201375c5c31513c06a4020f594e2a5

I've updated to use the latest from today.
