### ISSUE TITLE
Duplicated information in `__ESBMC_alloc` and `__ESBMC_deallocated`?

### ISSUE THREAD

**Issue by fbrausse** [esbmc/esbmc#774]
It seems that both arrays tracking whether objects have been de-/allocated store equivalent information, that is, `__ESBMC_alloc[i] == true` <-> `__ESBMC_deallocated[i] == false`.

They're updated at the same time as well: https://github.com/esbmc/esbmc/blob/e34eacf04f4103962d18d0cd37292072d9dbe489/src/goto-symex/builtin_functions.cpp#L243-L248 and https://github.com/esbmc/esbmc/blob/e34eacf04f4103962d18d0cd37292072d9dbe489/src/goto-symex/builtin_functions.cpp#L342-L347

Can we remove one of them? This would simplify the formulas ESBMC generates.

**Comment by lucasccordeiro** [comment]
> Can we remove one of them?

I would say yes; both arrays seem to store identical information.

**Comment by mikhailramalho** [comment]
I don't really remember why we do that... maybe related to the memory leak check?

If we don't regress any test case, I'd say go for it.
