### ISSUE TITLE
Test for oversized or negative shift operands

### ISSUE THREAD

**Issue by jmorse** [esbmc/esbmc#79]
C99's 6.5.7.3 dictates that if the right hand operand of a shift operation is either negative or >= the bitwidth of the operand, then the behaviour is undefined. However, we don't assert for or against this.

This is an issue because boolector will only accept shift operands where the shift amount is a of width log2(lhs_bitwidth), i.e. neither negative nor large enough to shift a number all the way out of a variable. So it's likely to have diverging behaviour from Z3 and other solvers.

**Comment by lucasccordeiro** [comment]
@brcfarias: could you please check whether this issue is already implemented with your `--ub-shift-check` option?

**Comment by brcfarias** [comment]
@lucasccordeiro: Yes, it is handled by `--ub-shift-check`.

**Comment by lucasccordeiro** [comment]
Thanks, @brcfarias.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/970.
