### ISSUE TITLE
C++17

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#792]
Should we update the repository into it? If so, we can finally replace the `gnu unused` with `maybe_unused`

**Comment by kunjsong01** [comment]
I concur. 

### As a side note:

https://github.com/esbmc/esbmc/blob/f3d0b40e21ba08f32cfd2fea689b0585a16cd7aa/scripts/cmake/Options.cmake#L56-L58

Should we add the following lines?  
```
set(CMAKE_CXX_EXTENSIONS OFF) # ---> turn off compiler's own extentions of the language for cross-platform compatibility
set(CMAKE_CXX_STANDARD_REQUIRED OFF) # ---> CXX_STANDARD is NOT enforced although we specified C++17
```
Set CMAKE_CXX_STANDARD_REQUIRED true until we really use a C++17 feature. 

### A minor reminder:
Is clang11's `clang_format` able to analyse C++17 syntax?

**Comment by rafaelsamenezes** [comment]
> Set CMAKE_CXX_STANDARD_REQUIRED true until we really use a C++17 feature.

Just the act of replacing the attribute already forces this usage

**Comment by rafaelsamenezes** [comment]
> Is clang11's clang_format able to analyse C++17 syntax?

We can also update the clang-format for 13 then. As this seems to be the latest stable version (Ubuntu 22.04, macOS M1)

**Comment by fbrausse** [comment]
I would welcome moving to C++17! clang-11 understands `-std=c++17`.

>> Set CMAKE_CXX_STANDARD_REQUIRED true until we really use a C++17 feature.

> Just the act of replacing the attribute already forces this usage

I do not understand. If you replace the gnu:: attribute, are there any other non-std constructs the code depends upon?

**Comment by rafaelsamenezes** [comment]
> clang-11 understands -std=c++17.

We only use clang as the CC for the libfuzzer tests. The release uses MSVC (Windows) and GCC (Linux).

> I do not understand. If you replace the gnu:: attribute, are there any other non-std constructs the code depends upon?

No, I think only this. Still, the code won't compile unless the compiler uses C++17.

**Comment by fbrausse** [comment]
> The release uses MSVC (Windows) and GCC (Linux).

Right. I meant this as an answer to @kunjsong01's question

> Is clang11's clang_format able to analyse C++17 syntax?

It might still be worth testing a build of ESBMC using clang-11. Reducing dependencies ;)
