### ISSUE TITLE
Naming inconsistency in build instructions

### ISSUE THREAD

**Issue by orionpapadakis** [esbmc/esbmc#868]
https://github.com/esbmc/esbmc/blob/fe155f36c5563c6f67f8660364c816d53e3d9a0b/scripts/ESBMC-Linux.dockerfile#L17

Consider changing :
```
mv clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04 clang
```
to :
```
mv clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04 clang11
```
or, change this 
https://github.com/esbmc/esbmc/blob/fe155f36c5563c6f67f8660364c816d53e3d9a0b/BUILDING.md?plain=1#L237 
accordingly.

**Comment by lucasccordeiro** [comment]
Thanks, @orionpapadakis. This issue has already been fixed in the master d3da20252fccac8329e5583bd14365040c1b8468.
