### ISSUE TITLE
Adding CITATION.cff to repository

### ISSUE THREAD

**Issue by jossmoff** [esbmc/esbmc#869]
See discussion [here](https://github.com/polywit/polywit/issues/21) between Lucas and I about adding this citation to the repo. 

**What?**
Add `CITATION.cff` to repository with the contents to produce the bibtex entry similar to the citation at http://esbmc.org/ 

**Why?**
People can directly copy either the APA/Bibtex entry straight from the repo. Example can be seen in the Polywit repository sidebar [here](https://github.com/polywit/polywit).

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/875.
