### ISSUE TITLE
Memory Corruption in ESBMC

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#873]
Running the following code with `--no-slice --incremental-bmc`.

```c
typedef struct {
  int b
} d;
union {} f[];
d *a;
void main() 
  { a->b; }
```

Causes esbmc to abort with `double free or corruption (!prev)`, segmentation fault, or `Corrupted size Vs. prev_size`. This is the reduced program from this file [cyc_ver2.zip](https://github.com/esbmc/esbmc/files/10113837/cyc_ver2.zip)

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes : I can't reproduce this issue with ESBMC v7.1.

**Comment by lucasccordeiro** [comment]
I could reproduce this issue with Boolector.

@fbrausse : can I ask you to check this issue? It involves union.
