### ISSUE TITLE
Crash during migrate

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#879]
The following code fails during Convertion into GOTO:

```c
int main()
{
    float r[1][1];
    (*(&r))[0][0];
    return 0;
}
```

The code fails with:

```
Converting
Generating GOTO Program
esbmc: /home/rafaelsa/esbmc/src/irep2/irep2_expr.h:2872: index2t::index2t(const type2tc&, const expr2tc&, const expr2tc&): Assertion `is_array_type(source) || is_string_type(source) || is_vector_type(source)' failed.
Aborted
```

While debugging, it seems that the index type is being carried over incorrectly

```
....
code
  * type: code
      * arguments: 
  * operands: 
    0: index
        * type: nil
```

@mikhailramalho  Do you have any suggestions? This is a high priority as there are other researchers trying ESBMC on their experiments with a deadline coming up shortly.

**Comment by lucasccordeiro** [comment]
@mikhailramalho:can I ask you whether you could check this issue?

**Comment by mikhailramalho** [comment]
Tentative fix in PR #880

**Comment by lucasccordeiro** [comment]
Thanks, @mikhailramalho. Let's rebase https://github.com/esbmc/esbmc/pull/880 and run your PR over the SV-COMP benchmarks.

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/880.
