### ISSUE TITLE
Get rid of c_link

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#883]
> > The c_link is quite messy, I wonder if we could ever get rid of it... I remember seeing some code in clang to merge ASTs, if that's possible we could merge all ASTs before calling convert + adjust.
> 
> I tried the [ASTImporter] (https://clang.llvm.org/docs/LibASTImporter.html) approach a bit. It is a bit tricky though, we have to create matchers for everything that needs merging.

I'm not an expert on the importer but maybe you only need to import the `TranslationUnitDecl` and everything inside will be merged: https://clang.llvm.org/doxygen/ASTMerge_8cpp_source.html

>  From what I understood, the `ASTs` that we have are for the current TU, so we would also need to refactor the frontend so that we have ASTs from every module.

Yeah, although I think it shouldn't be that big of a change. 

IIRC, we do the following:
1. `clang_c_languaget::parse`: generates clang AST.
2. `clang_c_languaget::typecheck` converts, adjust, and merge ASTs (using c_link).
3. `clang_c_languaget::final` adds model + some small changes to __ESBBMC_main.

My idea is:
1. 1. `clang_c_languaget::parse`: generates clang AST.
2. `clang_c_languaget::typecheck` merges clang AST using ASTImporter.
3. `clang_c_languaget::final` converts, adjust, adds model + some small changes to __ESBBMC_main.

That way we could get rid of the c_link, WDYT?

_Originally posted by @mikhailramalho in https://github.com/esbmc/esbmc/issues/881#issuecomment-1384337809_

**Comment by rafaelsamenezes** [comment]
Also, we could remove language specific linkers and implement a goto-linker (like CBMC does)

**Comment by XLiZHI** [comment]
> From what I understood, the ASTs that we have are for the current TU, so we would also need to refactor the frontend so that we have ASTs from every module.

Hi @rafaelsamenezes,

May I ask your thoughts on this point? I tried to create a new variable to store them, but the code structure was too complex for me to find a suitable solution.

**Comment by rafaelsamenezes** [comment]
> > From what I understood, the ASTs that we have are for the current TU, so we would also need to refactor the frontend so that we have ASTs from every module.
> 
> Hi @rafaelsamenezes,
> 
> May I ask your thoughts on this point? I tried to create a new variable to store them, but the code structure was too complex for me to find a suitable solution.

Yeah, this code structure is quite old (and inherited from cbmc, so about 20 years old). I suggest first understanding the languaget class at util/language.h . 

As a refactoring... what comes to my mind is:

1. Add a function to parse a list of files.
2. Add a default implementation where it basically calls the function to parse a single file.
3. Override this new function in the clang frontend. Then you should be able to keep the asts.

**Comment by XLiZHI** [comment]
closed via https://github.com/esbmc/esbmc/pull/1875
