### ISSUE TITLE
Add timestamp and location to LOG messages

### ISSUE THREAD

**Issue by rafaelsamenezes** [esbmc/esbmc#886]
It would be very helpful if:

- `log_debug`: preappended with `__FILE__, __FUNCTION__, __LINE__, or/and __PRETTY_FUNCTION__`
- all log messages had a timestamp associated.

**Comment by kushalnl7** [comment]
Hi, can I work on this?

**Comment by lucasccordeiro** [comment]
That’s okay.Sent from my iPhoneOn 30 Jan 2023, at 18:46, Kushal Lahoti ***@***.***> wrote:﻿
Hi, can I work on this?

**Comment by rafaelsamenezes** [comment]
Relevant file: https://github.com/esbmc/esbmc/blob/master/src/util/message.h

**Comment by fbrausse** [comment]
For me, it would *not* be helpful, if
> - all log messages had a timestamp associated.

*edit* Can we make this opt-in via an envvar or a cmd-line flag?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/2097.
