### ISSUE TITLE
More multi-dimensional-array tests

### ISSUE THREAD

**Issue by jmorse** [esbmc/esbmc#89]
Given how often we run into errors with these, there should be many many more tests that feature them.

**Comment by lucasccordeiro** [comment]
I have just enabled this test case with multi-dimensional array: https://github.com/esbmc/esbmc/commit/5d90c9137fa214f5d6a7c778c7b6841b1949b10d

**Comment by lucasccordeiro** [comment]
In addition to enabling one existing regression test, I have created four additional test cases for multi-dimensional arrays via https://github.com/esbmc/esbmc/commit/f625a2558f937ab5e5d345284cffd88cfd29c29b.
