### ISSUE TITLE
[C++ Verification] ERROR: elidable copy/move is not supported in get_expr

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#896]
```
class Foo {
  public:
    Foo() {};
    ~Foo() {};
    void Execute() {};
};

int main()
{
  auto foo = Foo();
  foo.Execute();
  return 0;
}
```

```
% ~/esbmc/build/src/esbmc/esbmc main2.cpp -I ~/esbmc/src/cpp/library
ESBMC version 7.0.0 64-bit x86_64 macos
Target: 64-bit little-endian x86_64-unknown-macos with esbmclibc
Parsing
main2.cpp:10:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto foo = Foo();
  ^
Converting
ERROR: elidable copy/move is not supported in get_expr
```

**Comment by kunjsong01** [comment]
@mikhailramalho 
A quick question: what does `cmt_lvalue`  mean? as in: 
https://github.com/esbmc/esbmc/blob/d8813f248a7b13b72a172b43f6121ef3efc5da7e/src/clang-c-frontend/clang_c_convert.cpp#L2406

Also, what's the difference between `cmt_lvalue` and `lvalue` ? 
https://github.com/esbmc/esbmc/blob/d8813f248a7b13b72a172b43f6121ef3efc5da7e/src/util/irep.h#L568-L576

**Comment by mikhailramalho** [comment]
Just a flag to mark the variable as lvalue. It was used to do typechecking,
we probably don't need it anymore.
