### ISSUE TITLE
[license] we must update the ESBMC license 

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#932]

**Comment by mikhailramalho** [comment]
Can you give some context?

**Comment by lucasccordeiro** [comment]
The license file misses the IBEX license and the yices license is outdated. 

There might be other software packages we used, where the license is not updated.

**Comment by mikhailramalho** [comment]
Do we need the yices license? We don't release it with esbmc, only z3 and boolector are included.

Same applies for IBEX I think.

**Comment by lucasccordeiro** [comment]
I see. What about the other SMT solvers?

Boolector has changed to MIT. Did we update it?

The idea is to double-check whether everything is updated.

**Comment by lucasccordeiro** [comment]
Boolector is not updated: https://github.com/esbmc/esbmc/blob/master/COPYING#L24

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/946.
