### ISSUE TITLE
[CUDA] Converting: Segmentation fault

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#934]
**Command:**
esbmc datar.cu -I ~/libraries/

```
#include <cuda.h>
#define tid threadIdx.x
#define N 2

__device__ inline void inlined(int *A, int offset) {
int temp = A[tid + offset];
A[tid] += temp;
}

__global__ void inline_test(int *A, int offset) {
inlined(A, offset);
}

int main( ) {
int *a;
int *dev_a;
int size = N*sizeof(int);

cudaMalloc((void**)&dev_a, size);

a = (int*)malloc(N*size);

for (int i = 0; i < N; i++)
a[i] = i;

cudaMemcpy(dev_a,a,size, cudaMemcpyHostToDevice);

ESBMC_verify_kernel_intt(inline_test, 1, N, dev_a, 2);

cudaMemcpy(a,dev_a,size,cudaMemcpyDeviceToHost);
free(a);
cudaFree(dev_a);
return 0;
}
```

**Library:**
https://github.com/XLiZHI/esbmc/tree/cuda

**Comment by kunjsong01** [comment]
Closed due to the following reasons:
1. This problem was probably caused by the unclear modifications of OMs in https://github.com/esbmc/esbmc/pull/937
2. The segfault is not reproducible

**Comment by lucasccordeiro** [comment]
@kunjsong01: can we already verify this CUDA program?

**Comment by kunjsong01** [comment]
> @kunjsong01: can we already verify this CUDA program?

I didn't try any. I'm currently focusing on C++ benchmarks. 
@XLiZHI any CUDA test cases passing?

**Comment by XLiZHI** [comment]
> > @kunjsong01: can we already verify this CUDA program?
> 
> I didn't try any. I'm currently focusing on C++ benchmarks. @XLiZHI any CUDA test cases passing?

I'm afraid not, but I don't think there are any C++OM bugs blocking CUDA validation at the moment. I'm currently working on COM to investigate the cause.
