### ISSUE TITLE
[C++ verification] Virtual functions inside namespaces cause segmentation fault

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#942]
esbmc main.cpp

```
#include <cassert>

namespace std{

class exception {
public:
  exception() throw (){};
 
  virtual ~exception() throw (){}
};

}

int main()
{
  assert(1);
  return 0;
}
```
esbmc version: commit 1b7475b

It works fine if I take the exception class out of the namespace or delete 'virtual'.

**Comment by kunjsong01** [comment]
Unable to reproduce the segfault. 

Got the following assertion failure instead of seg fault: 
```
ESBMC version 7.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
esbmc: ../src/clang-cpp-frontend/clang_cpp_adjust_code_gen.cpp:146: exprt clang_cpp_adjust::gen_vptr_init_rhs(const struct_union_typet::componentt&, const code_typet&): Assertion `vtable_var_symb' failed.
Aborted (core dumped)
```

**Comment by lucasccordeiro** [comment]
@kunjsong01: I get this assertion failure. Is it a bug or a feature on our C++ frontend?

**Comment by kunjsong01** [comment]
> @kunjsong01: I get this assertion failure. Is it a bug or a feature on our C++ frontend?

It's a bug. Our clang_cpp_convert_vft module is unable to handle a virtual function if its parent class is within a namespace. 
We don't any existing test case in our test suite for this code structure.

**Comment by kunjsong01** [comment]
@XLiZHI What's the impact of this issue? Which OM(s) does this issue affect?

**Comment by XLiZHI** [comment]
@kunjsong01 Thanks for your reply, this problem will lead to the `src/cpp/library/exception` and `istream` error, for now I've removed "virtual" and can continue to run, but I am not sure whether this will change the behavior of the code

**Comment by kunjsong01** [comment]
> esbmc main.cpp
> 
> ```
> #include <cassert>
> 
> namespace std{
> 
> class exception {
> public:
>   exception() throw (){};
>  
>   virtual ~exception() throw (){}
> };
> 
> }
> 
> int main()
> {
>   assert(1);
>   return 0;
> }
> ```
> 
> esbmc version: commit [1b7475b](https://github.com/esbmc/esbmc/commit/1b7475bd2abb95ae0b7bf10ebe46a5d0514a574e)
> 
> It works fine if I take the exception class out of the namespace or delete 'virtual'.

@lucasccordeiro OK I managed to reproduce the Segfault while fixing our `exception` OM on my private dev branch https://github.com/kunjsong01/esbmc/commits/OM-fix-exception . So the test case provided in this issue doesn't generate segfault but rather an assertion failure. 

The segfault was caused by a nullptr in the VFT building procedure between `class exception` and `class bad_exception`.  

@XLiZHI Was the segfault caused by your modified `exception` OM rather than the test case provided in this issue?

**Comment by XLiZHI** [comment]
@kunjsong01 In fact, both of them show seg fault when I test them, but I wrote this test case to try to find the problem in the exception, so I thought it would be good to focus only on the exception and other file in OMs. Thanks for your help!

**Comment by kunjsong01** [comment]
closed via https://github.com/esbmc/esbmc/pull/947
