### ISSUE TITLE
[Concurrency] pthread_join doesn't wait threads to end in SSA  

### ISSUE THREAD

**Issue by Anthonysdu** [esbmc/esbmc#950]
The source program:

> unsigned int x1, x2, n;
> 
> void* thread1() {
>   while (x1 < n) {
>     x1 = x1 + x1;
>   }
> 
>   return 0;
> }
> 
> void* thread2() {
>   while (x2 < n) {
>     x2 = x2 + x2;
>   }
> 
>   return 0;
> }
> 
> int main() {
>   pthread_t t1, t2;
> 
>   // initialize global variables
>   x1 = __VERIFIER_nondet_uint();
>   x2 = __VERIFIER_nondet_uint();
>   n  = __VERIFIER_nondet_uint();
> 
>   // main method
>   assume_abort_if_not( x1 == x2 && x1 > 0 );
> 
>   pthread_create(&t1, 0, thread1, 0);
>   pthread_create(&t2, 0, thread2, 0);
>   pthread_join(t1, 0);
>   pthread_join(t2, 0);
> 
>   assume_abort_if_not( x1 != x2 );
>   reach_error();
> 
>   return 0;
> }
> 

Command: `esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --z3 bench-exp1x3.wvr.c --32  --no-por --context-bound 2 --no-pointer-check --no-bounds-check --no-unwinding-assertions --unwind 3`

However, there is an interleaving which looks suspicious:

> *** Thread interleavings 132 ***
> Unwinding loop 2  iteration  1   file bench-exp1x3.wvr.c line 46 function thread2
> Unwinding loop 2  iteration  2   file bench-exp1x3.wvr.c line 46 function thread2
> Not unwinding 
> Unwinding loop 1  iteration  2   file bench-exp1x3.wvr.c line 38 function thread1
> Not unwinding 
> Symex completed in: 0.010s (126 assignments)
> Slicing time: 0.000s (removed 86 assignments)
> Generated 1 VCC(s), 1 remaining after simplification (40 assignments)
> Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
> Thread 0 file pthread_lib.c line 35
> ASSIGNMENT (HIDDEN)
> __ESBMC_pthread_thread_ended&0#1 == ARRAY_OF(0)
> 
> Thread 0 file bench-exp1x3.wvr.c line 57 function main
> ASSIGNMENT ()
> x1&0#2 == nondet_symbol(symex::nondet0)
> 
> Thread 0 file bench-exp1x3.wvr.c line 58 function main
> ASSIGNMENT ()
> x2&0#2 == nondet_symbol(symex::nondet1)
> 
> Thread 0 file bench-exp1x3.wvr.c line 59 function main
> ASSIGNMENT ()
> n&0#2 == nondet_symbol(symex::nondet2)
> 
> Thread 0 file bench-exp1x3.wvr.c line 62 function main
> ASSIGNMENT (HIDDEN)
> cond?1!0&0#1 == ((signed int)(x1&0#2 == x2&0#2 && x1&0#2 > 0))
> 
> Thread 0 file bench-exp1x3.wvr.c line 32 function assume_abort_if_not
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!0&0#1 == (cond?1!0&0#1 == 0)
> 
> Thread 0 file stdlib.c line 20 function abort
> ASSUME
> !goto_symex::guard?0!0&0#1
> 
> Thread 0 file pthread_lib.c line 199 function pthread_create
> ASSIGNMENT (HIDDEN)
> __ESBMC_pthread_thread_ended&0#2 == (__ESBMC_pthread_thread_ended&0#1 WITH [1:=0])
> 
> Thread 0 file pthread_lib.c line 208 function pthread_create
> ASSUME
> execution_statet::\guard_exec?0!0&0#1 => 1
> 
> Thread 0 file pthread_lib.c line 194 function pthread_create
> ASSUME
> execution_statet::\guard_exec?0!1&1#1 => 1
> 
> Thread 0 file pthread_lib.c line 199 function pthread_create
> ASSIGNMENT (HIDDEN)
> __ESBMC_pthread_thread_ended&1#3 == (__ESBMC_pthread_thread_ended&0#2 WITH [2:=0])
> 
> Thread 0 file pthread_lib.c line 208 function pthread_create
> ASSUME
> execution_statet::\guard_exec?0!2&2#1 => 1
> 
> Thread 1 file pthread_lib.c line 164 function pthread_trampoline
> ASSUME
> execution_statet::\guard_exec?1!326&326#1 => 1
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!1&326#1 == x1&0#2 < n&0#2
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSUME
> execution_statet::\guard_exec?1!332&332#1 => goto_symex::guard?0!1&326#1
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSIGNMENT ()
> x1&332#3 == x1&0#2 + x1&0#2
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!1&332#2 == x1&332#3 < n&0#2
> 
> Thread 2 file pthread_lib.c line 164 function pthread_trampoline
> ASSUME
> execution_statet::\guard_exec?2!365&365#1 => goto_symex::guard?0!1&326#1
> 
> Thread 2 file bench-exp1x3.wvr.c line 47 function thread2
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!2&365#1 == x2&0#2 < n&0#2
> 
> Thread 2 file bench-exp1x3.wvr.c line 47 function thread2
> ASSIGNMENT ()
> x2&365#3 == x2&0#2 + x2&0#2
> 
> Thread 2 file bench-exp1x3.wvr.c line 47 function thread2
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!2&365#2 == x2&365#3 < n&0#2
> 
> Thread 2 file bench-exp1x3.wvr.c line 47 function thread2
> ASSIGNMENT ()
> x2&365#4 == x2&365#3 + x2&365#3
> 
> Thread 2 file bench-exp1x3.wvr.c line 47 function thread2
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!2&365#3 == x2&365#4 < n&0#2
> 
> Thread 2 file bench-exp1x3.wvr.c line 46 function thread2
> ASSUME
> !(goto_symex::guard?0!2&365#1 && goto_symex::guard?0!2&365#2 && goto_symex::guard?0!2&365#3)
> 
> Thread 2 file bench-exp1x3.wvr.c line 50 function thread2
> ASSIGNMENT (HIDDEN)
> x2&365#6 == x2&365#4
> 
> Thread 2 file bench-exp1x3.wvr.c line 50 function thread2
> ASSIGNMENT (HIDDEN)
> x2&365#7 == (!goto_symex::guard?0!2&365#2 ? x2&365#3 : x2&365#6)
> 
> Thread 2 file bench-exp1x3.wvr.c line 50 function thread2
> ASSIGNMENT (HIDDEN)
> x2&365#8 == (!goto_symex::guard?0!2&365#1 ? x2&0#2 : x2&365#7)
> 
> Thread 2 file pthread_lib.c line 173 function pthread_trampoline
> ASSIGNMENT (HIDDEN)
> __ESBMC_pthread_thread_ended&365#4 == (__ESBMC_pthread_thread_ended&1#3 WITH [2:=1])
> 
> Thread 0 file pthread_lib.c line 273 function pthread_join_noswitch
> ASSIGNMENT (HIDDEN)
> ended?1!0&366#1 == __ESBMC_pthread_thread_ended&365#4[1]
> 
> Thread 0 file pthread_lib.c line 274 function pthread_join_noswitch
> ASSUME
> ended?1!0&366#1
> 
> Thread 0 file pthread_lib.c line 273 function pthread_join_noswitch
> ASSIGNMENT (HIDDEN)
> ended?2!0&366#1 == __ESBMC_pthread_thread_ended&365#4[2]
> 
> Thread 0 file pthread_lib.c line 274 function pthread_join_noswitch
> ASSUME
> ended?2!0&366#1
> 
> Thread 0 file bench-exp1x3.wvr.c line 69 function main
> ASSIGNMENT (HIDDEN)
> cond?2!0&366#1 == ((signed int)(x1&332#3 != x2&365#8))
> 
> Thread 0 file bench-exp1x3.wvr.c line 32 function assume_abort_if_not
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!0&366#4 == (cond?2!0&366#1 == 0)
> 
> Thread 0 file stdlib.c line 20 function abort
> ASSUME
> !goto_symex::guard?0!0&366#4
> 
> Thread 0 file bench-exp1x3.wvr.c line 21 function reach_error
> ASSERT
> !execution_statet::\guard_exec?0!0
> assertion 0
> 
> Thread 0 file bench-exp1x3.wvr.c line 73 function main
> ASSUME
> 0
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSIGNMENT ()
> x1&367#4 == x1&332#3 + x1&332#3
> 
> Thread 1 file bench-exp1x3.wvr.c line 39 function thread1
> ASSIGNMENT (HIDDEN)
> goto_symex::guard?0!1&367#3 == x1&367#4 < n&0#2
> 
> Thread 1 file bench-exp1x3.wvr.c line 38 function thread1
> ASSUME
> !(goto_symex::guard?0!1&326#1 && goto_symex::guard?0!1&332#2 && goto_symex::guard?0!1&367#3)
> 
> Encoding to solver time: 0.003s
> Solving with solver Z3 v4.8.9
> Encoding to solver time: 0.003s
> Runtime decision procedure: 0.000s
> BMC program time: 0.015s

In this interleaving, `thread2` has terminated and `thread1` hasn't when executing `assume_abort_if_not( x1 != x2 );` in the `main` thread, but is it means `pthead_join` didn't wait `thread1` to end?

**Comment by lucasccordeiro** [comment]
@Anthonysdu: could you please provide the implementation of `assume_abort_if_not`?

For debugging, I suggest looking at our operational model of the `pthread_join` at https://github.com/esbmc/esbmc/blob/master/src/c2goto/library/pthread_lib.c#L233 and https://github.com/esbmc/esbmc/blob/master/src/c2goto/library/pthread_lib.c#L265, particularly the content of the array `__ESBMC_pthread_thread_ended`.
