### ISSUE TITLE
[C++ verification] seg fault occurred during assignment

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#951]
esbmc main.cpp --data-races-check

```
struct curandStateTest {
    unsigned int v;
};

typedef struct curandStateTest curandStateTest_t;

unsigned int curand(curandStateTest_t *state)
{
    unsigned int r = state->v++;
    return r;
}

int main( ) {
return 0;
}
```
Error occurred in  `unsigned int r = state->v++;`

ESBMC version: d7f754f5e1b5eaf7cd161d5bb1dd10df896d8295

**Comment by kunjsong01** [comment]
Unable to reproduce the segfault. Got the assertion instead: 
```
Generating GOTO Program
esbmc-new: ../src/irep2/irep2_expr.h:2844: member2t::member2t(const type2tc&, const expr2tc&, const irep_idt&): Assertion `source->type->type_id == type2t::struct_id || source->type->type_id == type2t::union_id' failed.
Aborted (core dumped)
```

Run in Ubuntu 20.04 LTS. 

@XLiZHI Could you confirm the error signature please?

**Comment by XLiZHI** [comment]
Sorry, I forgot the flag, please try `esbmc main.cpp --data-races-check`

```
Generating GOTO Program
GOTO program creation time: 0.056s
Adding Data Race Checks
Segmentation fault
```
Modified to the following error disappeared.
```
unsigned int curand(curandStateTest_t *state)
{
    return state->v++;
}
```
So I think errors can occur during the assignment process.

**Comment by XLiZHI** [comment]
It seems possible to rewrite the code in the following form to avoid errors.

```
unsigned int curand(curandStateTest_t *state)
{
    unsigned int r; 
    r = state->v++;
    return r;
}
```
It's not sure if it's due to a feature of the front end or a bug.

**Comment by kunjsong01** [comment]
Closed due to the following reasons: 
1. This problem was probably caused by the unclear modifications of OMs in https://github.com/esbmc/esbmc/pull/937 
2. It appears a simple fix in the corresponding OM will work around this issue
