### ISSUE TITLE
[C++ verification] Migrate to C++14 standard

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#972]
Since our verification target uses upto C++14 standard, ESBMC shall also be upgraded to this level. The clang AST &ast;might&ast; contain more information to facilitate the conversion flows. 

### Evaluation: 
1. Benchmarks for core language features - `inheritance_bringup`, `polymorphism_bringup`
3. Benchmarks for OMs - `stream` or `string`

We'll probably need to migrate to C++14 as soon as we have a good passing rate in either `stream` or `string` benchmark. Further code extensions on IR conversion flows based on C++98/03 ASTs might give us surprises when migrating to C++14. 

### Preliminary Experiment:
For sure we have to deal with some new AST nodes, e.g. the implicit move constructor and rvalue reference...
```cpp
class Bird {
  public:
  virtual int do_something(void) { return 21; }
};
```
```cpp
254 |   `-CXXConstructorDecl 0x556bf45732c0 <col:7> col:7 implicit constexpr Penguin 'void (std::Penguin &&)' inline default noexcept-unevaluated 0x556bf45732c0
255 |     `-ParmVarDecl 0x556bf45733f0 <col:7> col:7 'std::Penguin &&'
```
```python
Converting
ERROR: Conversion of unsupported clang type: "RValueReference
RValueReferenceType 0x55b393235110 'std::Bird &&'
`-RecordType 0x55b393234c60 'std::Bird'
  `-CXXRecord 0x55b393234bc8 'Bird'
```

**Comment by fbrausse** [comment]
I would recommend adding an option that specifies the given language including its version. It could be similar to `-x` supported by Clang and GCC and a second option similar to `-std=`.

**Comment by kunjsong01** [comment]
This issue currently has the highest priority as there's verification request from our research partners. 

TODOs:
- Migrate to C++11 (or preferably C++14) standard 
- Add cstdint OM

**Comment by kunjsong01** [comment]
For the time being, we can probably "bypass" those nodes related to move semantics in the AST, because there's no verification request using that feature. The rest of the conversion flow shall not be affected. 

Original estimate: 1w for this ticket.

**Comment by kunjsong01** [comment]
closed via https://github.com/esbmc/esbmc/pull/1047
