### ISSUE TITLE
Support for M1 and M2 architecture

### ISSUE THREAD

**Issue by A-m-anuel** [esbmc/esbmc#985]
MacBook Pro
Chip - Apple M2
macOS Ventura 13.3
Apple clang version - 14.0.3

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: does our build support this version?

**Comment by rafaelsamenezes** [comment]
I am able to do a custom build on M1 by setting a custom clang and flags.

So, it is probably possible but it will require thinkering and no guarantees.

**Comment by lucasccordeiro** [comment]
@A-m-anuel: Is there some chance that you can use the Linux or Windows version?

**Comment by A-m-anuel** [comment]
@lucasccordeiro: I tried it on a Linux virtual machine on my Mac, but it didn't work. So, I will attempt to work on the seminar with my group members' PCs

**Comment by rafaelsamenezes** [comment]
I am closing this as we currently have no plans to offer support for either M1 nor M2.
