### ISSUE TITLE
[C++ OM] header file "new“

### ISSUE THREAD

**Issue by XLiZHI** [esbmc/esbmc#987]
C++ operational model `new` currently contains an error.

Reference to https://en.cppreference.com/w/cpp/header/new
1. Namespaces should not include operators.
[example](https://github.com/XLiZHI/esbmc/blob/Cuda/src/cpp/library/new)

After the modification, we encountered the following error message:
```
ESBMC version 7.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
ERROR: file new line 24: The virtual method isn't pure virtual and hasn't a method implementation
ERROR: CONVERSION ERROR
Aborted
```
Reference to https://en.cppreference.com/w/cpp/memory/new/bad_alloc
I followed the reference and tried to change it as follows, but still got an error.
```
struct bad_alloc : public exception {
	public:	    
		bad_alloc() throw ();
		bad_alloc( const bad_alloc& other ) throw();
		bad_alloc& operator=( const bad_alloc& other ) throw();		
		virtual const char* what() const throw();		
	};
```
May I ask if this is a feature or a bug?

**Comment by XLiZHI** [comment]
esbmc main.cpp -I src/cpp/library

```
#include "new"

int main()
{
    return 0;
}
```
ESBMC version: 1991d6fac6d92e07b202033eb498a078bd6df62b

**Comment by kunjsong01** [comment]
fixed via https://github.com/esbmc/esbmc/pull/995 
No further actions needed.
