### ISSUE TITLE
[C++ verification] Various issues in nested class members and object composition

### ISSUE THREAD

**Issue by kunjsong01** [esbmc/esbmc#991]
TC:
```cpp
#include <cassert>

char x = 'X';

class string
{
public:
  class iterator
  {
  public:
    char* pointer;
    void do_something()
    {
      iterator buffer;
      buffer.pointer = &x;
      pointer = buffer.pointer;
    }
  };

  iterator itr;
};

int main()
{
  string myString;
  myString.itr.do_something();
  assert(myString.itr.pointer == &x);
  //assert(myString.itr.pointer != &x); // FAIL, as should be identical
  return 0;
}
```

ESBMC version:  5e6db517094c
cmd line: ./esbmc main.cpp -I library/

**Comment by kunjsong01** [comment]
This issue blocks `string` OM include: 
```
Converting
Generating GOTO Program
ERROR: Looking up index of nonexistant member "pointer" in struct/union "std::string::iterator"
Aborted (core dumped)
```

**Comment by kunjsong01** [comment]
The root cause is incomplete and inconsistent struct type in symbols, possibly due to the recursive calls in our conversion flows --- class types cannot be synced in this way. So only after executing `get_struct_union_class` can we get a complete class' type. But this is not always the case - the conversion flow would stop and return in the middle leaving an incomplete type which is also inconsistent with the actual class' type symbol.  
```cpp
// For DeclRefExpr type to a class `iterator`
0: symbol
* type: struct 
  * tag: string::iterator
  * components:  <--- components being empty as a result of recursive calls to `get_struct_union_class` and `get_type`
* identifier: c:main.cpp@163@S@string@S@iterator@F@do_something#@buffer
```

Symbols referring to a struct type should be simplified to: 
```
0: symbol
    * type: symbol <--- this refers to the type symbol for class `iterator`
        * identifier: tag-string::iterator 
    * identifier: c:main.cpp@163@S@string@S@iterator@F@do_something#@buffer
```

**Comment by kunjsong01** [comment]
There are two issues found here: 

**1. Nested class member access issue:** 
Failed to access nested class member due to incomplete and inconsistent type as explained in https://github.com/esbmc/esbmc/issues/991#issuecomment-1521833420 and https://github.com/esbmc/esbmc/issues/991#issuecomment-1523413991. 

**2. Obejct composition issue:** 
Goto-symex failed to instantiate due to missing argument:
```
Counterexample:

State 1  thread 0
----------------------------------------------------
Violated property:

  function call: not enough arguments


VERIFICATION FAILED
```
in GDB: 
```
(gdb) p function_identifier.as_string()
$1 = "c:@S@string@S@iterator@F@iterator#"
```
Need to adjust the decl block parent class constructor in symbol table: 
```
Symbol......: c:@S@string@F@string#
Module......: main
Base name...: string
Mode........: C++ (1)
Type........: constructor  (struct string *)
Value.......: 
{
this->itr = iterator();  // no argument for iterator constructor

}
```

TC: 
```cpp
#include <cassert>

char x = 'X';

class string
{
public:
  string() {}
  class iterator
  {
  public:
    iterator() {}
    char* pointer;
  };

  iterator itr;
};

int main()
{
  string myString;
  assert(0);
  return 0;
}
```

**Comment by kunjsong01** [comment]
TC: 
```cpp
#include <cassert>

class string
{
public:
  class iterator
  {
  public:
    int data;
  };

  iterator itr;
};

int main()
{
  string str;
  assert(1);
  return 0;
}
```

### Evaluate the idea to get a reference to structs/unions/classes instead of a copy:
At `get_type` code,  `clang::Type::Record`, we copy the entire type of `iterator` class for `iterator itr;` in the above TC.
https://github.com/esbmc/esbmc/blob/ca247ebd9c2e7a5d7b07a102ba373ee15ecedf92/src/clang-c-frontend/clang_c_convert.cpp#L995

It breaks the `add_padding` flow at https://github.com/esbmc/esbmc/blob/ca247ebd9c2e7a5d7b07a102ba373ee15ecedf92/src/clang-c-frontend/padding.cpp#L300-L301

and would give an error: 
```
ERROR: Symbolic type id in type_byte_size
symbol
* symbol_name : tag-string::iterator
```

For the time being, we just leave it. A copy is easier than "bridging" the type2t files below: 

[copied_type_for_itr_migrated.txt](https://github.com/esbmc/esbmc/files/11399607/copied_type_for_itr_migrated.txt) ---> `add_padding` is happy about this one
[referenced_type_for_itr_migrated.txt](https://github.com/esbmc/esbmc/files/11399609/referenced_type_for_itr_migrated.txt) ---> `add_padding` is NOT happy about this one

**Comment by lucasccordeiro** [comment]
I think Mikhail and Franz worked on this code about the padding.Do you have any thoughts here?Sent from my iPhoneOn 4 May 2023, at 17:46, KSong ***@***.***> wrote:﻿
TC:
#include <cassert>

class string
{
public:
  class iterator
  {
  public:
    int data;
  };

  iterator itr;
};

int main()
{
  string str;
  assert(1);
  return 0;
}
Evaluate the idea to get a reference to structs/unions/classes instead of a copy:
At get_type code,  clang::Type::Record, we copy the entire type of iterator class for iterator itr; in the above TC.
https://github.com/esbmc/esbmc/blob/ca247ebd9c2e7a5d7b07a102ba373ee15ecedf92/src/clang-c-frontend/clang_c_convert.cpp#L995
It breaks the add_padding flow at https://github.com/esbmc/esbmc/blob/ca247ebd9c2e7a5d7b07a102ba373ee15ecedf92/src/clang-c-frontend/padding.cpp#L300-L301
and would give an error:
ERROR: Symbolic type id in type_byte_size
symbol
* symbol_name : tag-string::iterator

For the time being, we just leave it. A copy is easier than "bridging" the type2t files below:
copied_type_for_itr_migrated.txt ---> add_padding is happy about this one
referenced_type_for_itr_migrated.txt ---> add_padding is NOT happy about this one

**Comment by fbrausse** [comment]
> The root cause is incomplete and inconsistent struct type in symbols, possibly due to the recursive calls in our conversion flows --- class types cannot be synced in this way. So only after executing `get_struct_union_class` can we get a complete class' type. But this is not always the case - the conversion flow would stop and return in the middle leaving an incomplete type which is also inconsistent with the actual class' type symbol.

@kunjsong01 This description to me sounds like #637.

**Comment by fbrausse** [comment]
@mikhailramalho has proposed a fix for that in the `adjust_type` branch.

**Comment by kunjsong01** [comment]
closed via https://github.com/esbmc/esbmc/pull/1180
